### ISSUE TITLE
Polaris Port - 9000 Guns

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#10]
- [x] Really, just make a checkbox for each gun.
- [x] MWPSB Dominator
- [x] Eluger
- [x] Aro's gun
- [x] SVD
- [x] Battlerifle
- [x] STG
- [x] UNSC shotgun
- [x] FN Five Seven
- [x] <s>Mindflayer (should already be in the code in zresearchlabs.dm)</s>
- [x] <s>HL2_Pistol (altered silenced pistol)</s>
- [x] <s>M14</s>
- [x] <s>M41A</s>
- [x] STS35 (probably already in the code)
- [x] Derringer (might be in the code because I know /tg/ added one)
- [x] Judge (under revolver/shotgun)
- [x] Rifle (bolt action rifle, under pump/ directory, requires changes to the base shotgun code)
- [x] Mosin
- [x] Snipers and Pulse Rifles now use the "gauss_shoot.ogg" sound effect from S.T.A.L.K.E.R.

**Comment by JoanRisu** [comment]
- [ ] FN Five Seven
- [ ] MWPSB Dominator

**Comment by SpadesNeil** [comment]
- [] Eluger
- [] Aro's gun
- [] Mindflayer (should already be in the code in zresearchlabs.dm)
- [] SVD
- [] Battlerifle
- [] HL2_Pistol (altered silenced pistol)
- [] M14
- [] M41A
- [] STG
- [] STS35 (probably already in the code)
- [] Derringer (might be in the code because I know /tg/ added one)
- [] Judge (under revolver/shotgun)
- [] Rifle (bolt action rifle, under pump/ directory, requires changes to the base shotgun code)
- [] Mosin
- [] UNSC shotgun


Most if not all weapons have had their sound effects changed at some point. Ensure the sound effects are correct.
- [] All normal lasers use the star wars "blaster" sound effect.
- [] All guns have had their sounds changed, most using a default shot sound that sounds less horrible than the original SS13 one.
- [] Snipers and Pulse Rifles now use the "gauss_shoot.ogg" sound effect from S.T.A.L.K.E.R.

**Comment by Arokha** [comment]
I'll leave the rest up to you if you insist! But remember: Don't edit any .dm files that aren't ours (ask me if you think you have to). I'd suggest literally just replacing their sound .ogg files with renamed ones of your chosing.

**Comment by SpadesNeil** [comment]
I'm hoping this to be settled by a Polaris PR I made.

https://github.com/PolarisSS13/Polaris/pull/1811

**Comment by SpadesNeil** [comment]
Closing this since it's done except for a few things that aren't required.
