### ISSUE TITLE
Landing while moving in a shuttle causes the landing console to lock up

### ISSUE THREAD

**Issue by knoxon1** [VOREStation/VOREStation#10011]
If you land a moving shuttle while still in motion, the short range jump console permanently locks up

Landing as normal

Even if the screen says moving at 0 gm/h per hour, if you even have .00001 movement it will still lock up

#### Steps to reproduce
- (Step 1)Go fast
- (Step 2)Try to Land
- (Step 3) Fail to ever take off again

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Very-Soft** [comment]
Every time this comes up in ahelps I picture this in my head.

![it won't fly](https://user-images.githubusercontent.com/24854483/112739649-01762480-8f44-11eb-9d9c-6b687030c8e7.png)

I know it's a bug but this is what I think of. XD

**Comment by Novacat** [comment]
I did find the root cause of this, apparently the maploader can only handle 32 Z levels max so if the server is at or close to 32 Z levels, it is possible that the maploader just breaks which also breaks shuttle transitions. Ever since I cut down on the number of active Z levels this bug has completely disappeared.

**Comment by Novacat** [comment]
This started cropping up again as soon as I closed this. Heck.
