### ISSUE TITLE
Can't Supply Autolathe with Plasteel

### ISSUE THREAD

**Issue by ShudderEve** [VOREStation/VOREStation#10231]
#### Brief description of the bug

The autolathe has recipes that require plasteel. However, clicking on Autolathe with Plasteel instead supplies it with Platinum, and not Plasteel.

#### What you expected to happen

Inserting Plasteel into the autolathe supplying it with plasteel.

#### What actually happened

The autolathe instead converts the plasteel sheets into platinum.

#### Steps to reproduce
- Click autolathe with any amount of plasteel sheets.

**Comment by Arokha** [comment]
It appears to have some pretty janky ideas about what it can accept. It uses the item's matter var, which for plasteel is some steel and some platinum. I thought maybe that's intentional, it can only accept base materials (there's only one item that requires plasteel to make, I thought maybe THAT was the mistake), but if you put in durasteel, which is made of pasteel and diamond, it puts in plasteel!

**Comment by Arokha** [comment]
Not actually fixed, that PR wasn't merged
