### ISSUE TITLE
Things I gotta do

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#1032]
Am playing right now, so just a quick list
- [x] Make infections good
- [x] Make backup implants show on HUD
- [x] Make flavor/taste for people
- [x] Lick verb for above
~~- [ ] Gutter?~~
- [x] Fix map thing below
![image](https://cloud.githubusercontent.com/assets/15028025/23286845/2cf56844-fa08-11e6-9fc2-79ef13addb32.png)

**Comment by Dhaeleena** [comment]
Add be inside cat

**Comment by Wickedtemp** [comment]
- Have infections cause mild toxins, potentially increasing as the infection grows in severity
- "You feel an irritating itch in your [limb]/The skin on your [limb] looks inflamed." for mild infections.
- "You feel an aching pain in your [limb]." for acute infections.
- "IT HURTS SO MUCH." tier pain messages for final stage infections. 
- Dead organs need to be detectable. 
- Dead limbs (final stage infection) should probably not work, or at least, not work as well. It's difficult to walk when your foot is literally rotting. 
- Maybe alter the way heart damage works, so a dead heart doesn't instantly kill you with toxins? 
- Make the 'lick' verb replaceable with 'mlem'! : D
- Put the backup HUD on the right side of the health bar, so the AR-M HUD can see it. 
- Dead lungs currently cause less damage than popped lungs. It's worse to have damaged lungs than no lungs at all. I figure it's worth putting here, because infections lead to dead organs. 
- Mlem
