### ISSUE TITLE
Pulling item out of pocket while resting vaporizes it

### ISSUE THREAD

**Issue by Slovakiani** [VOREStation/VOREStation#10883]
#### Brief description of the bug
If you're at rest (Hotkeymode U) and pull an item into your hand while at rest, it vaporizes.

This seems severe.

#### What you expected to happen
.. Items to.. not vaporize. I have yet to test this on a player. I hope it doesn't vaporize people too lol

#### What actually happened
Items vaporize, delete from the game if dropped from your pocket at rest.

#### Steps to reproduce
- (Step 1) Walk through the door
- (Step 2) Get on the floor
- (Step 3) Everybody vaporize them dinosaurs (drop dinosaur from pocket)

**Comment by Very-Soft** [comment]
To add to this issue since it's related:

it seems like click dragging things onto your character to open their interface, such as PDAs/Communicators, may also disappear them. 

These items still exist, they just get lost in the character's contents, and can be retrieved with var editing. But it seems like the inventory references to them get lost somewhere along the way, while their position is not updated.
