### ISSUE TITLE
Moving diagonally over open space with lattice results in falling down sometimes

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#10965]
#### Brief description of the bug
if you move diagonally over an open space with a lattice over it, you will fall to the floor below. Seems like moving diagonally doesn't take lattices into account.

#### What you expected to happen
not falling down if there is a lattice

#### What actually happened
falled down

#### Steps to reproduce
- (Step 1)move diagonally over an open space with a lattice on it like this one
![image](https://user-images.githubusercontent.com/24854483/124853143-65f94480-df73-11eb-8fe1-6fd2eb154ce5.png)

#### Code Revision
- B:release D:
Commit: 0384f1be0b0583b364d3a9f02f7f35a25c0f5a62

**Comment by Very-Soft** [comment]
After further testing, it seems like this doesn't always happen, but seems more localized to situations like the one depicted in the screenshot.

**Comment by Arokha** [comment]
The diagonal moves are two moves, and it always tries the same order every time. If there's nothing in the way then it just sticks with that, otherwise it tries the other way. So, depending on which corners are blocked and if it has to try two different ways, you may fall.

I should note that setting yourself to 'walk' prevents this since you can't walk into dangerous turfs, minecraft crouching style.

I think the bug is that it's unpredictable, even if you have a clear path to walk on. If there's NO clear path, like the lattices are only touching by the corners and there's not a lattice diagonally, I don't think it should block your movement. You should just fall, in that case. ... Unless you have traceur? ;o

**Comment by Very-Soft** [comment]
> The diagonal moves are two moves, and it always tries the same order every time. If there's nothing in the way then it just sticks with that, otherwise it tries the other way. So, depending on which corners are blocked and if it has to try two different ways, you may fall.
> 
> I should note that setting yourself to 'walk' prevents this since you can't walk into dangerous turfs, minecraft crouching style.
> 
> I think the bug is that it's unpredictable, even if you have a clear path to walk on. If there's NO clear path, like the lattices are only touching by the corners and there's not a lattice diagonally, I don't think it should block your movement. You should just fall, in that case. ... Unless you have traceur? ;o

I think you might be misunderstanding somewhat:

![image](https://user-images.githubusercontent.com/24854483/124875396-d796ba00-df96-11eb-842d-a2072d6d4779.png)

They fell down here, where there should be no unsafe turf to walk on. There is only the 1 open space turf with a lattice built over it. It shouldn't be possible to fall down on this turf unless the lattice was missing.

Testing it in the other screenshot (along the cyan lines) showed that it wasn't just all diagonal movement over open space, it seems to work rather predictably on those cyan lines

But in that tiny bit of hallway, the person who reported it originally fell down when moving diagonally, and I fell down when moving diagonally when I tested it.

**Comment by Arokha** [comment]
O, weird!

**Comment by Zeldazackman** [comment]
CItadel had this issue for a while, even moreso whenever catwalks are involved like the previous upper floors of the tether (above engineering lobby mostly) before it was all squashed to one station floor
