### ISSUE TITLE
Nanopaste is not very usefull for FBP

### ISSUE THREAD

**Issue by drexample** [VOREStation/VOREStation#1105]
#### Brief description of the issue
Nanopaste works only with opened cover (which cannot be opened by synth themselve), what makes it quite useless, because you can just repair yourself with welder/wires

#### What you expected to happen
Nanopaste actually healing brute/burn damage without opened cover.

#### What actually happened
I couldn't heal myself from external burns with nanopaste.
#### Steps to reproduce
- (Step 1)
Get damaged
- (Step 2)
Try to use the nanopaste
- (Step 3)
Suffer.

#### Code Revision
Server revision: release - 2017-03-05
ad434b6f0072b3f1b9959d4b63707c6afc0b6c13

**Comment by Wickedtemp** [comment]
I don't play Robitics or Science, or any synth characters, so my thoughts on this would of course be a little less valid than someone who DOES. But, IIRC, nanopaste is meant purely for "synth surgery". I don't think you should be able just apply nanopaste to any external injury, in the same manner you shouldn't be able to do the same with bonegel.

But at the same time, I think it should be an option for full body prosthetics. Is there no way to perform a "surgery" on them as you can with other synths/androids/robots/cyborgs/whatever-they're-all-just-machines-anyways?

**Comment by drexample** [comment]
@Wickedtemp 
Nanopaste's description : "A tube of paste containing swarms of repair nanites. Very effective in repairing robotic machinery." 
I think repair nanites can be applied just about anywhere, since they're y'know, nanites.

**Comment by Arokha** [comment]
I think it's just a balance thing. It's true it's not super useful, though. Since any damage over 30 (I think?) requires the synth surgery thing, and nanopaste is just a way of doing it without needing torch and wires internally.

Could just make nanopaste behave exactly the same as both torch and wires externally, so it won't heal damage that requires surgery, but you can use it internally/externally.

I admit it's kind of shitty being a synth, accidentally hit self with something, or throw something and have it bounce, and now I'm damaged until I can go to robotics, or, obtain welding goggles for myself and a torch.

**Comment by drexample** [comment]
@Arokha Nobody uses nanopaste, ever. People just forget about it existing at all and use wires+welder. Making nanopaste fixing at least external damage would be really amazing.

**Comment by Arokha** [comment]
I mean it'd still have to be external damage 'up to a point'. I don't want to have something that just lets you IGNORE synth surgery. That'd be like adding a drug in the lobby of medical that just fixes all bones/organ damage.

**Comment by Wickedtemp** [comment]
Medbay sometimes has nanopaste spawn, when it does, I always stock it in the OR in case we need to repair a mechanical heart or eyes, etc. However, I've never had that happen. Either that or it has and they went to the roboticist to get cut open and healed and then later die of infection because roboticists never wash their hands.

I think stopping nanopaste's external healing ability when damage drops below 21/31 would balance enough, whichever is the one that requires 'synth surgery'. However, I don't think it should be instant. Otherwise, a synth could potentially solo the gateway or just tank infinitely, nanopasting themselves to a functioning health. If it's like the advanced trauma/burn kits, that'd be good I think.
