### ISSUE TITLE
Some NPC radio messages inconsistent with ship-side operations and crew transfer procedures.

### ISSUE THREAD

**Issue by SigholtStarsong** [VOREStation/VOREStation#11750]
#### Description of the bug
Some random event messages (Such as the pretty ion storm) still reference a station on the _Stellar Delight._ Crew Transfer message refers to the shuttle as the Evacuation Shuttle, when it should just be a Transfer Shuttle.

#### Code Revision
Server revision: B:release D:
Commit: ed596993545df7242a7a0f6dcf51c003d4055b18

**Comment by KillianKirilenko** [comment]
The shuttle name is set in the mapdefines. It should either just be "Transfer Shuttle", or it can have a proper name like the other ships (formatting permitted). I leave that up to @Very-Soft as it's their baby.

Storms/etc. events will need a little rewriting, but should be manageable.

**Comment by Very-Soft** [comment]
I can peek at it, though I will say, I left 'station' alone because it's generic enough to allow for some wiggle room. Your 'station' can be a position on a starship. It is a little cumbersome, but I tried to ensure that the messages I could peek were generic enough that they would work for the SD, and for the Tether, without having to figure out how to make unique ones for both, since, that would also require making unique sounds for both, and setting the system to make those different depending on the map, which I am not confident to on how to do, and would be a process we would have to repeat if/when we make another new map.

Also, I could give the evac shuttle a name, I'll just have to think about it a bit.

**Comment by KillianKirilenko** [comment]
I'm figuring the simplest way to handle it would be a `map_type` var in the map defines, which can either be `"facility"`, `"station"`, or `"ship"`, and then the event procs will check that and fire the relevant audio/text using a simple `switch` or `if` statement. Shouldn't be too hard to set up.
