### ISSUE TITLE
Maint Pred Random Species at Spawn

### ISSUE THREAD

**Issue by RadishArchmage** [VOREStation/VOREStation#12034]
#### Brief description of the bug
When spawning a maint pred role from the ghost pod menu, the game asks if you are sure you want to spawn and then offers a list of options. It option list offers a confirmation or cancel button, but the cancel button seems to select a random species and then spawn, rather than cancelling the spawn.

#### What you expected to happen
I except the menu to close and reset

#### What actually happened
I've replicated this a couple of times, highlighting different species and selecting cancel seems to randomize the result.

#### Steps to reproduce
- Select maintenance hole
- Select "yes" for the question "are you sure"
- Select "cancel" on the species menu

**Comment by Heroman3003** [comment]
That is intentional behaviour. Once you agree to be maint pred, you're locked into being one. At a point where you select which kind, you cannot back out.

**Comment by Very-Soft** [comment]
It doesn't seem unreasonable to me that, if you push cancel, it should probably not spawn you as the maint pred, and add the maint pred pod thingy to the ghost pods list again.

I know if I oopsed and clicked yes on accident, or even clicked yes on purpose and got the prompt, and then decided against, it, I would expect cancel to back me out of the selection, rather than pick one at random.
