### ISSUE TITLE
Deconstructing, and then re-constructing the Advanced Shield Generator increases powerdraw massively

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#12057]
#### Brief description of the bug
Normally, the Advanced Shield Generator, set to range 55, only draws around 3000-4000 kW of power while Active using settings of Hull, Warp and Hyperkinetic projectiles.

Due to the shield being "Overloaded", I had to deconstruct it, then reconstruct so to fix it. This skyrocketed power draw to 11 000+ kW

#### What you expected to happen
At the above described settings, Adv. Shield Gen should draw 3000-4000 kW

#### What actually happened
It drew 11 000+

#### Steps to reproduce
- Turn shield generator on, activate it
- Forget to deactivate it so it drains fully
- Shield says "Overloaded", cycling it doesn't do anything
- Use screwdriver, crowbar on shield that's turned off
- Place the parts it ejected inside, screwdriver closed
- Set: range 55, max powerdraw 6 000, Hull shield, multi-dimensional warp, Hyperkinetic projectiles, 10 passive power
- Turn on, notice it takes around 200-300 kW on stand-by
- Activate, it's now 11 000 kW

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
- Server revision: B:release D:
Commit: 82228c1d70685413010d476abf9f116a1d8562b3 
 

#### Anything else you may wish to add:
- The Advanced Shield Generator was not moved from its location near the HoP's office.
- The Advanced Shield Generator was hotwired to the engine using a separate cable running to the shield room. On previous rounds, this caused no issues.

**Comment by ResidentCody** [comment]
If I recall correctly, the shield generator that the ship starts with is specifically mapped and varedited to have reduced power draw. So when you disassembled and reassembled the shield generator, you created a "new" unmodified one that doesn't have this quality of life feature.

In essence, this isn't really a bug. Just that the actual advanced shield generator is truly a gigantic power hog by default and we get a somewhat tweaked one for the Stellar Delight. If you lose that initial one, you're only able to replace it with the high-cost generator.

**Comment by Very-Soft** [comment]
yeah this isn't a bug so much as you made a new shield generator, and a new shield generator uses the default values, the one that is mapped in has a lower power draw, so that it is more possible to run the shield indefinitely. 

I should also note, that using hull shielding uses more power than not. So if you wanted to run it more cheaply you can do away with that, as it actually doesn't do anything positive for the ship if you aren't holding the air in.

At the default settings, if you use the bare necessities (multi dimensional and hyperkinetic) the shield uses around 6.4 MW to run indefinitely. We determined that, with the normal engine setup, while making the shield run indefinitely was and is not at all meant to be mandatory or even nessisarily desirable, but people kept treating it as if it was, and kept holding up other ship operations until they had achieved it. So! The shield generator's power draw was nerfed to make it more reasonable to achieve somewhat quickly. 

That is why the ship's mapped in shield gen is the way it is. If you take it apart and put it back together though, it will use the default values though.
