### ISSUE TITLE
Lack of the HELMET OF JUSTICE ingame.

### ISSUE THREAD

**Issue by Somekindofpony** [VOREStation/VOREStation#1206]
Ace told me to make an issue for this because it blocks him from putting it on a random foxgirl and make her say "AWOO AWOO AWOO" down the hallway. Blame Ace, please.

**Comment by SpadesNeil** [comment]
This pleases me.

**Comment by MASMC** [comment]
Uh... this is not a feature, it is note severe... nor is it really a blocker... why does it have these tags? *Sigh* We need to check this over...

**Comment by SpadesNeil** [comment]
This has exactly as many tags as my brilliant administration believes it needs. :)

**Comment by MASMC** [comment]
... this needs to be rethought, imo...

**Comment by SpadesNeil** [comment]
You just don't understand the glory of the **HELMET OF JUSTICE**. It requires no thinking. In fact, it requires the opposite of thinking.

(I'm also not sure if you've realized that the tag spam is part of the joke.)

**Comment by MASMC** [comment]
I know. Still, I don't want to see this in  my emails constantly. :P Don't
mind me, though.

**Comment by Screemonster** [comment]
Mute the thread :v

**Comment by MASMC** [comment]
Eh. Really good point there... don't mind me...

**Comment by chaoko99** [comment]
Close this. Please.

**Comment by SpadesNeil** [comment]
_no_

**Comment by Arokha** [comment]
As much as I want to say "This isn't the place to just put up post-it notes of everything you'd like to have", it sort of is, out of necessity, since we don't have anywhere to put feature requests. :/

Even so, that being the case, it's also the place for actual important issues that aren't 50% joke, so if there's a feature nobody's going to implement then I'm just gonna close it to clean up the list.

**Comment by SpadesNeil** [comment]
-reopens-

... ok not really Aro makes a good point and this has been here for months
