### ISSUE TITLE
Catslugs on Rascals Pass will let anyone into their department.

### ISSUE THREAD

**Issue by FartMaster69420** [VOREStation/VOREStation#12836]
#### Brief description of the bug
If someone calls a catslug, it will try to get to them. If it has access, it will open doors in it's way.

#### What you expected to happen
For restricted areas to remain restricted.

#### What actually happened
Catslugs will open doors for anyone who asks.

#### Steps to reproduce
- Go to security.
- Stand by the door, ensure you are in earshot of officer gatslug.
- pspspspspspspspsps
- The door is now open.

#### Anything else you may wish to add:
This should be a simple fix, just don't give the catslugs access until a ghost spawns in and remove it if they ghost out. That way the AI wont open doors that shouldn't open.

**Comment by Very-Soft** [comment]
ohhh we should make the department slugs check your department for pspsps XD

**Comment by BonniePandora** [comment]
Ah, yeah the thought of _that_ manner of getting entry to departments never crossed my mind when I gave them their departmental access. _Woops._

**Comment by BonniePandora** [comment]
Okay, I did some testing with this on live and wasn't able to repeat them opening the respective department doors with _just_ a "pspsps", they simply bonk the doors harmlessly rather than actually bumping it.
What I _suspect_ happened for you, was that the 'slug followed the "pspsps" sound, ended their follow period right beside the door and then had a random move that caused them to properly bump it and made them open up.
Not _ideal_, sure, but not really a confirmed method of breaking in via innocently trusting catslug behaviour.

**Comment by lm40** [comment]
you can also use captain crumsh to waltz into the captain's office by pushing him into the door
