### ISSUE TITLE
Splitting stack of 1 to 1 deletes any stacks on the floor

### ISSUE THREAD

**Issue by Raeschen** [VOREStation/VOREStation#12840]
Brief description of the issue
stacks of a mat on the floor gets deleted if you split a stack of one into a stack of one

Steps to reproduce
Have a stack of mats on the floor, and ONE piece of the mat in your hand, the other hand free
With free hand, click on the mat, and split the 1 stack into 1.
The mat beneath you will of been deleted.

This was reported upstream but tested and reproduced as of this bug report on a locally run version of the codebase. 
#https://github.com/CHOMPStation2/CHOMPStation2/issues/4153

**Comment by ItsSelis** [comment]
This bug appears to be also reproduceable, if 2 stacks of a given material get merged inside the hand.

For example: Stack of 3 Steel get merged into stack of 5 steel. The stack of 5 steel on the floor disappears, but the hand will only have 8 steel merged in the end instead of the 13 that it should have in the end.
