### ISSUE TITLE
Rascal Pass xenobotany weirdness

### ISSUE THREAD

**Issue by lm40** [VOREStation/VOREStation#12871]
Xenobotanists don't have access to the xenobotany lockers inside xenobotany (for some reason they have access to the ones in the airlock tho??) neither do they have access to the windoor to their desk (which is called research desk, although funnily they do have access to the actual research desk). Also just as an aside it's kinda strange to have a full on reinforced wall proper airlock between xenobotany and the rest of the department when elsewhere they are only a reinforced window away from the outside.

**Comment by ItsSelis** [comment]
I had left the windows in for now, since there are also privacy shutters that could be lowered.
Of course, if wanted, they could be also replaced with the same walls or the privacy shutters replaced with actual blast doors.
Another choice is replacing some of the airlock walls to reinforced windows (though that would make the airlock itself more insecure).
