### ISSUE TITLE
You literally fall down from hologram weapons in the thunderdome, holodeck

### ISSUE THREAD

**Issue by WinterDarkraven** [VOREStation/VOREStation#13021]
!--Please provide a clear and concise description of what the bug is.--
You fall down.

!--What normally happens when this occurs? Keep in mind that behavior may be different on other servers.--
You fall down.

!--Please use as much detail as possible when describing the bug behavior, including any context (things you did before) that might be relevant.--
You fall down.

!-- Same here, please include any context that might have contributed, such as actions taken right before.--

Steps to reproduce
* (Step 1) Go to the thunderdome, holodeck.
* (Step 2) Pick up the hologram sword
* (step 3) Hit someone, they fall down after 1--2 hits. They aren't in stamina crit, it just does knockdown.

Why has the thunderdome became even more RNG? Return to 4 hit competitive thunderdome.

**Comment by WinterDarkraven** [comment]
I rest my case.

**Comment by Runa-Dacino** [comment]
I have a hypothesis:

You take halloss damage, this manifests as 2xhalloss as traumatic_shock, however traumatic shock does not exceed 80.

Instead, the amount of halloss causes health to drop below "soft_crit" value.

Because you go into soft_crit, hallos clears fast enough to reduce traumatic_shock under 80.

Because you only feel pain if traumatic shock is 80 or higher, no pain messages are given

No idea if true, gonna test

**Comment by Runa-Dacino** [comment]
### Did testing extra:

The holosword has a variable chance to instantly knock you down. Like, that's it. Your health, halloss, shock everything is below treshold. This can take 1 hit, 3 hit, 

### If you land 4 hits in a row (starting at 0 hallos, 0 shock, 0 shock_stage), you get:
        Anika has been attacked in the upper body with weapon by Anika! x4
        
        You scream! 
        
        You're in too much pain to keep going... 
        
        Anika slumps to the ground, too weak to continue fighting. 


***
### **Not a bug**
As such, I feel this is not a bug, nor an issue. You "fell down" because the holosword has a variable chance to knock you down IF you are targetting the chest.

I repeated this for hand, arm, leg, foot, head. All of those took 4-5 hits to get the "you're in too much pain to keep going." Except for the head, 1 hit and I went down with 100 halloss.

**Comment by WinterDarkraven** [comment]
It didn't used to do this before. I ruins the 4 hit to win, now you win randomly.

Is this getting reverted or what.

**Comment by Runa-Dacino** [comment]
> 

Did you look at the linked file?

![image](https://user-images.githubusercontent.com/20523270/171154174-0d86530f-fe52-4a4b-bdb5-5790ce39cd7d.png)
https://github.com/VOREStation/VOREStation/blame/afd673c6f6962a4721617bda8ba8384179be2f03/code/modules/mob/living/carbon/human/human_defense.dm#L324-L347

This was a thing for years.  SEVEN YEARS.

https://github.com/VOREStation/VOREStation/blame/d902406ea10a670d2ce04a43661d203772f5f26e/code/modules/mob/living/carbon/human/human_defense.dm

![image](https://user-images.githubusercontent.com/20523270/171154386-d44db2e2-738d-4da9-b4b6-fd10ffd3b7b1.png)

**Comment by WinterDarkraven** [comment]
> > 
> 
> Did you look at the linked file?
> 
> Actually, did you even read my post?
> 
> ![image](https://user-images.githubusercontent.com/20523270/171154174-0d86530f-fe52-4a4b-bdb5-5790ce39cd7d.png) https://github.com/VOREStation/VOREStation/blame/afd673c6f6962a4721617bda8ba8384179be2f03/code/modules/mob/living/carbon/human/human_defense.dm#L324-L347
> 
> This was a thing for years. SEVEN YEARS.
> 
> https://github.com/VOREStation/VOREStation/blame/d902406ea10a670d2ce04a43661d203772f5f26e/code/modules/mob/living/carbon/human/human_defense.dm
> 
> ![image](https://user-images.githubusercontent.com/20523270/171154386-d44db2e2-738d-4da9-b4b6-fd10ffd3b7b1.png)
> 
> The only change that happened was fixing targetting for to use defines.
> 
> [81abd2f](https://github.com/VOREStation/VOREStation/commit/81abd2f6e34fc75ba12adca33fa4712be72b7b09)
> 
> Literally nothing changed. #12934
> 
> When I played on Baystation12 in 2016, I had knocked people down by punching them in the chest.

**Comment by WinterDarkraven** [comment]
The new targeting broke it.

If you've been in the thunderdome then you know it is a competitive area where you must land 4 (30 damage) hits to win.

I've had to resort to fist fights to crit because its more balanced. If the thunderdome doesn't get fixed at least make it so when I punch people I can't break bone, I've broken three ribs so far it sucks.

**Comment by WinterDarkraven** [comment]
Also I'm not talking about punches, I'm talking about thunderdome swords. They didn't do knockdown months ago

**Comment by Runa-Dacino** [comment]
> Also I'm not talking about punches, I'm talking about thunderdome swords. They didn't do knockdown months ago

They did do knockdown. This is not a bug. If you want it adjusted, bring it to #General-feedback on discord, don't claim it's a bug.

It's working as intended. Holoswords have 3 force, which gives them them good strength.

And if you looked at code, you'd see if you targetted the groin rather than torso, it'll not knock them down.
