### ISSUE TITLE
Some ideas for managing antagonism~

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#1323]
(There's a bit of a TL;DR a few comments down.)

#### So I had a couple of ideas~

Basically, there's already a fair little list of options in the antagonism panel of character creation, to enable one to be all kinds of things. but for Virgo, I think there's one missing, that could sort out a lot of uncertainty when it comes to allowing people in on antagonist agendas. Something that would be out of place on pretty much any other server;

What if there was a "Target" or "Victim" or something similar, role, in the antagonist screen, something to flag that person as someone who is okay with antagonism happening to them. Since one of the biggest issues with potential antagonism on virgo is figuring out who is and isn't okay with participating. This would be a way of opting in to such things, which I feel, would make it a lot more crystal clear to all involved as to who is 'Valid' and who is not. You might even be able to make game modes or event types or some such that could generate antagonists who's targets and objectives only have to do with those in the "Targets" list.

Now, I don't know if Virgo has antag huds, but I know some servers do, to show who's on your team and that. 

If you were to couple this with adding the "Targets" to all relevant antagonist roles huds, then it would be plainly visible to those who do get into antagonist positions, who has and hasn't opted in to such things. 

Additionally, it would be ideal to include a means of opting into the list midround, in case you decide you want to be included in something going on.

I would think that these things could make it really clear for everyone involved, and as long as the rules are clearly defined, anyone with half a brain ought to be able to follow with such a system. Of course, it should still be used responsibly I imagine, admin managed and that, since Virgo is mainly an RP server.

But for those of us like myself who do like participating in such things, it might be really cool to see some more of those kinds of events on the station, and these changes, I feel could help manage it, and potentially opens the door to some more Virgo specialized event, and gametypes.

I mean, I could see this used to essentially run a traitor round, where the traitor targets are only picked from the 'Targets' list. Of course, it would be preferable if there was at least the suggestion of Vore being the mode of going after the target. And perhaps there might be an indigestable token on their person, that is what the traitor is actually after?

Or further, an event where something affects everyone on the 'Targets' list. Perhaps a group of NPC voremobs gets on station, and only really go after people carrying weapons, or people on the 'Targets' list? 

There could even be an event where someone on the 'Targets' list is framed for something, to give sec something to do if they are being especially rowdy for no raisen, as occasionally happens. Though for this one, the admin might want to make sure the target isn't in the middle of something else first, since there'd technically not really be a real antagonist involved.

These are just a few ideas I had off of the top of my head, that I think could really liven up the station, and open the door to more possibilities in what admins could do with events, since a targets list would be distinctly in place.  

I know this is all probably a lot more complicated to actually implement than I understand, but I thought I would lay it out here for all to see, and see what you all think of it~ c:

**Comment by Screemonster** [comment]
I've wanted a "be pred" and "be prey" option for _ages_ so people can browse in-game and find people who wanna be eaten without them having to make an LFRP post. As it stands, if the person in the circuits lab is a prey character who wants to be hunted down and devoured, the only people who have any chance of actually knowing this are ghosts.

Having a player _and_ an admin version of these preferences would be fantastic. Player version would just list OOC info and basic profiles of the people on the list.

**Comment by Very-Soft** [comment]
It would indeed be neat if there was a sort of list to access for players too, yes~ If opted in to, listing their character name and a button to view their flavortext and OOC notes?

**Comment by Treasa729** [comment]
This sounds like an awesome idea. There is one thing though that I would want to be added if this was going to be a thing: I would want to be able to have an option to pick like "vore target" (or like RP target) and "target(/robust target)". I personally would love to be involved in vore related antag events, but I really don't enjoy stuff that comes down to robusting and such. If there were to be some event with a vore antag, I would be glad to participate in it, but if it was something which is combat focused, I would want to opt out. Essentially, it would be asking to have the encounter RP based rather than robust. Even if this wasn't an option though, I would be very in favor of this kind of feature being implemented.

**Comment by Arokha** [comment]
I like this idea! I don't think there should be "robust targets" though. The problem being that once an antag finds a robust target somewhere, sure, they have consented to no-RP toolboxing, but other people could get pulled in who might not be okay with that and it's not really fair to them. Should probably stick to RPing stuff and just use stuff like LOOC if you want to negotiate no-RP stuff.

**Comment by Very-Soft** [comment]
Yeah, Virgo is RP server, so ideally, most antag interactions should at least start with RP stuff. And tbh, I think that still enforcing OOC notes sort of eliminates the need for distinctions between vore and nonvore targets? I mean, if you took the time to start RPing a scene with someone, you probably ought to have given their OOC notes a read and taken them into proper consideration.

Having such a distinction could be helpful though I suppose in sorting out targets to match play preferences better. After all, some folk might want to play antag, but not be a pred. So they get assigned targets from the no vore list. That makes sense. They might even be a prey character seeking to cause trouble and end up eaten as a result. Or you know, some men just want to watch the world burn, or whatever.

It should be generally understood though that what we are talking about here IS essentially an "I'm okay with being killed/abused" list. It should come with the understanding that your character _may very well_ meet an unpleasant end, or may be paired up with someone who's prefs don't really match all that well. Obviously, OOC notes should be followed even in such a case as this. But I think that ensuring that those who enable these proposed options understand that they are volunteering themselves to participate in unexpected hostile situations. 

What I am saying is, it's not in anyone's prefs to be shot in the face with a gun.*1 Or mugged at knife point in maints.*2 But I would think that signing up to be an antagonist target may very well lead to such a thing happening. There's a difference between running in and mechanics robusting someone, and RPing out a proper scene (And **then** mechanics robusting them), of course. But it's important to understand with this; Things may not go quite how you want them to. And anyone who expects them to in the terms of being included in a list of targets for characters who's objectives are very likely to be related to killing or stealing stuff from the people on that list are... Well, I don't think they have much room to complain, unless specific terms of their OOC notes are broken, though...

Someone who's OOC notes say that they don't want to be eaten, killed, or harmed, who enables such options as these... I mean, what're you expecting to happen? I'm rambling a little, I know. But thinking about it, it's important for people to understand that they need to have realistic expectations for how things might end up. The person who wants no harm coming to their character, signing up to such a thing as this, their notes might not be able to be followed while also allowing an antag to complete assigned objectives. 

(*1 - Well I mean it probably is in some people's prefs let's be honest)
(*2 - This one's definitely in some people's prefs but I'm trying to make a point, geeze)

**Comment by Very-Soft** [comment]
So, to clarify what exactly I am talking about in more... Brief terms;

-Adding an extra option or two to the Antagonist panel of the character creator
-"Target" or something similar, 
-Adds you to a list only accessible by admins
-This list is intended to be your means of 'Opting in' to be the victim in any events or antagonists admins happen to run.
-If relevant to player antagonists, this list could update the antagonist hud to show a marker over people on the list, to show who is 'valid'
-Admins could manually select targets for antags, or if possible, configure a system to automatically assign people to the antags who are on the list if enabled by the admins.
-Add a button into the OOC tab for players, to opt in to being a Target mid round

----Maybe have "Target", and "Non Prey Target" role options to populate independent lists, to better suit the prefs of those involved (That way you could assign Pred only characters as targets, involve people who aren't too interested in vore, or assign prey characters as antagonists)

It would ideally be a set of tools that would make running events with potentially hostile forces on the station more easy for the admins, as they would have a list of people to look at, to gauge how much interest there is, and to use to give directives to those forces.

If admins notice that the list is small, could remind people that the opt in button is there, in case they are interested. See if the list changes, make decisions based on that info~

Just thought I would give this here more briefly as a summary.

**Comment by Screemonster** [comment]
Okay, I'm now liking this latest idea more than having an LFRP-list, so we can avoid the problems of people just ignoring anyone they don't see as LFRP.

"be traitor" is already an option. The "be pred" "be prey" and "be target" options sound fine too.

For now, just have it an adminbutton that lets them pick a pred and prey (or traitor and target) from their respective lists, assign the appropriate objective to the pred/traitor, and let 'em go.

_Later_ we can worry about whether to do things like, say, a major event that picks out a pred and gives them a prey to eat.

**Comment by ArbyTheDragon** [comment]
Anyone who has been here for some time knows that even the random events system has been carefully grinded and restrained such that nothing that could happen on the list could possibly affect anyone who wants to have a romantic moment somewhere in the station. This can make for some rather dreary rounds for the players who do erotic roleplay or vore less frequently, such as myself. Antags may also fear infringing upon someone's preferences. This new feature could help remedy all of that. While effectively the same as OOC notes enforcement, it functionally makes it much more clear that whatever might follow in the round will not violate any strong preference of anyone. We NEED A FEATURE LIKE THIS. **But I'm afraid we are in danger of taking the wrong approach to how players consent to it.** 
So, bear with me, and please read carefully. I feel strongly about my position, and took my time to write this. There is no TL:DR.

I'm not at home to check in the server to see if the options are still there, but I do recall seeing some options for being a target during antag rounds- namely three that are "Prey", "Kidnapped", and "Killed". _I kinda knew what they meant, but I didn't want to turn them on. Hell, I might have even fabricated it in a dream, but within this lies a problem of psychology. I really felt afraid at that moment, and I'm positive others will feel the same way_. Call me a snowflake, but **I think we need to word these character-setup options carefully if we want anyone to accept them. If we're not careful, people will be afraid (in a technically meta-gaming sort of way) and just not enable the option. Having too few players consenting to being a target can reinforce the fear, or simply cause this new feature to fail in making it clear who's actually okay with what.** Let me explain why this will happen.

**First, here's the circumstances that I base my reasoning on.**
As far as I have seen, there does exist a few players who actively want to get killed, kidnapped, or eaten in a round. But I'm going to suggest that some, if not most players on Virgo, are not like this. Even though they're not seeking out their next demise, these players might not be completely opposed to it, and wouldn't raise a stink if the unsafe nature of Space Station 13 and VORE had them meet an unexpected end. Drama, unfortunate events, sometimes catastrophe and death, _all in a heavy roleplay setting especially_ are part of what makes SS13, and this server in particular, incredibly fun to me. I'm sure I'm not the only one who thinks this way.

**The issue is the player inherently becomes wary of these dangers that could face them with a player enabled character setup option. Yes, it's meta. You can try your best to act oblivious, but there's a rationale behind it**. If I select the "Be Killed" option, I'm going to be OOCly aware that my name is on the kill list for whatever mercenary, antag, or ninja that's lurking about. Normally, this is just the reality of SS13 and I play the game knowing possible sudden doom is a necessary evil and maybe even part of the fun, but Virgo is _somewhat_ different. Yes I acknowledge that this isn't an "action" server, but that's besides the point. Anyways- people have OOC preferences, and have scenes that are best not interrupted. The random events system has also been carefully crafted to not inadvertently halt anyone who's in the moment. Not all players are eligible targets for antags due to OOC preferences and whether or not they're in a scene. The code currently doesn't consider that. Yes, it still means if anyone is going to be killed, it's going to be the people who consent in OOC preferences, but I believe there's a silver lining for those people. The odds that they're on the list is low- and gets lower for every player that's currently on the server. If the stars align and they are on the list, there's nothing they can do about it without consciously changing OOC preferences. But they wouldn't change OOC preferences, since they're already not opposed- unless they feel it's okay to abuse the OOC preferences system in this way. This feature we're proposing to add will change the code to (As far as I understand it) only pick targets who ARE ELIGIBLE based on their character settings. This eligible targets list may be very short. The psychological issue is I can hardly imagine players actively wishing that demise upon themselves by enabling a character setup option. **Thus, few people will enable the option. This makes matters worse ten-fold**. Those who enable the option in good faith not only will be the only ones who will certainly face possible doom, but the list of people who do this will be VERY SHORT. Maybe as short as only 1-3 players. **This will effectively mean that if the server assigns an antag with a kill order, you've got a good 30%-100% chance that the person who dies this round is YOU.** This reality petrifies me, and while I wouldn't be opposed to any happenings, come as they may, I would never enable an option that mutually assures my 'end'. There can be remedies, such as having the server roll every player randomly to pick who will be a target. If the person the server rolled doesn't have the preference enabled, then the server doesn't give the antag a player target order at all. This would make me more at ease, and antags could be more confident in their objectives, but I still don't think it's the best solution because it doesn't solve the possibility of players being afraid to choose the option.

An objection to my argument may be that "You already couldn't violate OOC preferences or interrupt scenes in an undesirable way. This feature will just ensure the code doesn't set antag objectives that may do that." To this counter, I say you are absolutely right, but that's not my point. My argument isn't about logic, it's about player psychology. OOC/meta knowledge is something every player can't ignore to some higher or lesser degree. The best players can block it out, but they're still subconsciously aware. While players may not mind OOCly if a terrible end finds them, seeing and enabling an option that has the distinct function of putting them on "the list" worries me, and it might worry others.

**If this is gonna work, we need to be able to expect that people who wouldn't be opposed a particular situation actually enable the relevant options**

**Comment by Very-Soft** [comment]
While I agree with you that very few people are likely to want to be on the 'kill' list. There are a wide variety of prey leaning characters across the station with some mention of being kidnapped in their ooc notes already.

And further, while I do like the idea of random events automatically assigning people from the list to random antagonists based on prefs. The main basic idea here is in the title; These are meant to be tools for trusted members of our community, the admins, to use responsibly to manage antagonism. 

Having lists like this would make it a lot more easy to see if there -is- anyone interested in being a target, and what kind of targets are available for those admins. And they could ideally use that information to run a wider variety of events that can more directly affect a portion of the crew, as they have essentially consented to it before hand. (Within reason and such, to do with ooc notes and whether or not they are in some kind of scene that makes them otherwise unavailable, of course.)

I'm looking at the Event Pref dialogue right now, and it lays out the basic gist of what the feature is intended to be used for, and rules that will be associated with it. Namely that the events will feature admin selected players who will respect your ERP prefs, and will RP scenes with you, though those scenes might be shorter than an ordinary scene, depending on the situation.

I think that the dialogue is relatively clear, the options available are also pretty clear.

While I respect the that there are some people who simply will not enable these options because they do not want unexpected things to happen to them, I also know that there are a number of people who, based on their OOC notes, _would_ like unexpected things to happen to them. There are many kinds of people with a variety of mindsets. Some of them will look at these options and shy away, or become paranoid. Those ones likely will not enable them. 

Going into slightly more opinionated territory;

Ultimately, I too want to see more events happen. I want to see more **_kinds_** of events too. The biggest problem with events though in general I would think, based on what I have seen and heard, is figuring out who wants to participate in them or not. Because let's face it. As it is, if an admin runs an event with hostile forces, it is usually confined to a small out of the way spot, and security is on top of it in an matter of moments, and nearly instantly murders it before it CAN affect anyone else. 

And that's fine and stuff, if you like to play sec and robust things.

It's lame though for basically everyone else on the station. There's not really any room for one to participate in such an event outside of those specific circumstances. Where a tool that basically says you are cool with playing a part in antagonism has a lot more potential to allow for more varied kinds of events, should the admins decide to allow them. It allows options for that antagonism to have a directive, to actually effect the crew, rather than just being security's punching bag.

It would in my opinion at least, be much more fun in general, and to hear about, if a group of player controlled mercs arrived on the station with the goal of finding and kidnapping the one person who has those options enabled, especially if they succeeded, than it is to hear about that there was a gunfight on the docks. 

I do appreciate this discussion though. I hadn't considered the psychological aspect of such lists as these. But I mean, if you're already playing a character who's OOC notes clearly define that you are fine with kidnapping and/or grab and gulp stuff, then I would imagine that you'd either already suffer from such paranoia, or would not be bothered by being included on such a list as these.
