### ISSUE TITLE
Human bodies should not spawn as black!!

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1363]
#### Brief description of the issue
I could have sworn I reported this. When a human body is spawned by the game, because of our skin coloring system, the bodies are black by default. **They should not be black by default.** This is most noticeable whenever syndie or Russian or clown mobs are spawned and killed. They spawn a black corpse which makes absolutely no sense.

#### What you expected to happen
For the victim to have a skin color of the spawned body to matches the body they were previously in, albeit maybe a bit more pale.

#### What actually happened
I get someone blacker than Baristo's fat aunt Sibonakaliso.

#### Steps to reproduce
- Spawn Russian, Pirate, Syndie, or Clown mob.
- Kill it.
- Observe blackness of corpse.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/48648cc35c1d2b564846f87c9ea7caa34f037712
 
#### Anything else you may wish to add:
- I have tried repeatedly to fix this and nothing seems to fucking work because I misunderstand how body color is generated and refreshed.

**Comment by Dhaeleena** [comment]
This has been happening for a long while. Its not only mobs, But anything that is admin spawned. It happens with most if not all races but its harder to notice since they have different base colors. If you admin spawn the a character for anyone, It will look normal, Except that they will be stuck with a male body no matter gender, But if they are cloned, The clone will be Pitch black or be missing more than half its features. I noticed humans were cloned pitch black but if you do this with a Synth, it would be missing its Hair, custom tail, eye color and any other customization.

**Comment by SpadesNeil** [comment]
Regenerate icons verb does nothing to fix this, I should add.

**Comment by Wickedtemp** [comment]
Yeah, noticed this back in late February. At least 2 members of Staff saw it so I had thought it'd gotten reported. It was actually pretty fuckin' hilarious at the time.

**Comment by ArbyTheDragon** [comment]
I think it might be a remnant of the old genetics code if it still exists. Anyone who has null data gets the respective values set to 0. If a mob dies and his dead corpse doesn't call any information about their skin RGB HEX, it defaults to all zeros and you get a black body.

This bug occurred in genetics because there was _something wrong with not checking enough UI cells?_ VORE has more UI cells than most servers because of our extra features like taur bodies. If you tried to edit the taur bodies back then, you'd always get black taur bodies (but not black skin). Eros had this problem too but actually ended up fixing it, finding that the issue was something in the grounds of the UI data for the character being longer than what the genetics console could check.

I don't know if genetics has any part in our code anymore, but if it is and it still has its tentacles inside this and that, it could be the source of our bug. It's worth checking.

**Comment by Arokha** [comment]
DNA is always there. Even w/o genetics, all the important stuff stored about your character is stored in DNA. Like species and color and size and markings and whatnot are all stored in DNA, and that's not just for genetics, that's like. How you get cloned, and deeply involved during spawning your character when you join and stuff.

**Comment by ArbyTheDragon** [comment]
Huh! So problems in genetics weren't just symptoms of values being unset, but a way of observing the values!
