### ISSUE TITLE
Round End Limbo! The curse of forever voting.

### ISSUE THREAD

**Issue by DemgelZalvine** [VOREStation/VOREStation#1390]
#### Brief description of the issue
Round end votes going off for infinity, potentially getting stuck never knowing when the shift ends.
Making it rather difficult to start anything, knowing the next vote may kill it.
#### What you expected to happen
A single extension, people wrapping up their plays and going with crew transfer.

#### What actually happened
Round was in limbo, three votes to continue before I cryo'd out, reports it went on even further than that too. Quite frustrating, because hindsight shows you could have scened but experience says otherwise.

#### Steps to reproduce
Be lateshift and the few people who are in scene continue it forever.
Watch round end when They're finished.

#### Code Revision
Server revision: release - 2017-04-12
7326a03f6b3cea38a023b1f909b09af2aa18a728 
 
#### Anything else you may wish to add:
So I know this may be a hot button issue, but figured it's about time to actually bring it to light. It does get really tiring getting stuck in the limbo of 'will it/won't it' while people choose not to wrap up their scenes and continue them well after the normal bell. While it is democracy, it's rude as hell for those who're stuck waiting. It really shouldn't need more than the 'wrap up hour' so everyone else has things to do. :V

**Comment by ArbyTheDragon** [comment]
You want the end of the round to be within sight? Me too, but again, it's democracy. _At least it is untill the admins come._

Anyone else have an opinion?

**Comment by Michab02** [comment]
I'd support limiting it to only a single extension vote, so it can only be extended by an hour max.

**Comment by ArbyTheDragon** [comment]
7 hour rounds... Makes me wanna cry. ._.

**Comment by Dhaeleena** [comment]
Yea i think only a single extension vote should be a thing. If the vote is coming up people can choose to wrap up stuff or just wait to see if the vote passes, If the vote passes then they still have an entire hour to wrap things up and the people hoping for a fresh shift dont have to stay in a limbo. I know because i have suffered this

**Comment by Somekindofpony** [comment]
I also support a single extension, it makes more sense and doesn't make people regret hopping on/not hopping on.

**Comment by Wickedtemp** [comment]
Not sure if this has been done already but a few announcements in the discord server regarding this discussion would definitely be warranted. And by "a few", I mean "Announced until everyone knows about it and has had time to talk about it".

**Comment by Screemonster** [comment]
I support putting a cap on it, 'cause if I check the manifest on the web (which is far quicker than firing up byond and connecting to the server) and see the shift time at 5:24 or something I frequently don't bother logging in and wait for a fresh shift. One vote is good for those "just a little... more... time..." moments (like what I had with the solar garden, another hour there would have been perfect) but really, once you're past that it should be understood that it's time to wrap up.

**Comment by ArbyTheDragon** [comment]
That makes me curious. I wonder if the number of players who play on the server and also pay attention to the git is _smaller than we'd hope._ **It would be a good idea to make a channel, even a temporary one, on the discord for this discussion.**

Back on topic.
On servers that had a short round time, there was a problem. For miners especially, mining materials takes a LOT of effort in the game. Often was the round where I'd mine a bunch of materials and the round would be over before science, medical, or engineering got to use them. We're kinda immune from this problem, cause those servers had round lengths of only 120 minutes- one may have even had just 60 minute rounds, extendable to 120 minutes!

**I think some sort of round-persistent stockpiling of materials should be made, even if it doesn't actually carry materials from one map to the next, at least increment a counter. You know, for fun!** We could actually gauge how productive the miners have been over time- That from April whatever to May, miners on VORE collected XX tons of diamonds, uranium, phoron, etc.
If we could be physically stockpiling round-to-round the most valuable things like plasteel and diamond, we could use it to make those 6 Durands central command asked for, or for awesome on-station projects! That'd be kinda neat, right?

**Comment by Arokha** [comment]
Right now each extension starts weighting the vote more towards transfer, so it must have been a pretty significant percentage continue for those! This would be pretty easy to implement, though.

**Comment by ArbyTheDragon** [comment]
IIRC, on a server of roughly 30-40 clients, **first vote always seems to pass. But the second vote seems to have roughly 11 to continue, 8 to leave. Sometimes, I think it passes by a slim margin of 2 votes or so.** The following 3rd extension one turns out to about 7 to continue, 15 to leave and I haven't seen a round go much longer than 5:30. Roughly half of the players vote in each extension vote.

Yeah, more people vote to leave after every successive extension. I think the 3rd extension has only passed once or twice since I started playing again.

**Comment by SpadesNeil** [comment]
I at least want the vote screen to tell how many times we've voted already.

**Comment by Wickedtemp** [comment]
I would personally be okay with this because, in my own experience, an hour is plenty of time to **finish** something you've already started but not always enough time to **start** a new scene. So if I wasn't already in a scene or roleplaying and the vote goes to extended, great, I sit and watch suit sensors for an hour because hey, I don't really feel like starting something I won't be able to finish and I've only got an hour... Then the next vote goes Extended as well and it's a little annoying knowing that I sat there for an hour when in hindsight, I could've actually had a complete scene... But that's more of an annoyance. These are what I feel are the biggest reasons to limit extended votes:

- Round stagnation. People get burnt out and stop roleplaying, the ones who aren't are all in dorms. No one new joins because it's gone on for 8 hours and they've got no clue how long it'll go on for, they decide to wait for next round. Gets boring fast.

- The crew doing stupid shit at the 1-hour mark affects the crew JOINING at the 7-hour mark. My example, because I have a nasty departmental bias, people who take the large beakers from Chemistry. They did so 4-5 hours ago, no one remembers who did it, no one knows where they are and this late in the round, everyone in cargo has been in a dorm for at least an hour and Science screwed off to the Outpost, so there are just no large beakers for Chemistry. This also goes further than minor annoyances. Large events, whether it's done by players or by Staff, also contribute. The longer a round goes on, the less inclined the crew becomes to actually **do** anything. That's annoying sometimes.

- Things break ingame. They don't always get fixed. Sometimes aforementioned things stay broken for the rest of the round but because there are 12 assistants fucking in a dorm, the 8 people roleplaying outside of the dorms have to just suffer through it until someone who can fix it ends up joining. One annoying incident, also Medical because that's the only department I play, someone blew up the lab. Dunno the specifics but it required pressurization. No active engineering staff. No one around to do it. The round continued for another 2 hours at least because people in scenes kept voting continue and those in scenes outnumbered those not. 

So... Yeah, I'd support limiting the number of votes to just a single one. 

**HOWEVER,** this will ALSO mean that players who have big plans, such as saunas, strip-clubs and group scenes will have to wait until the new round starts, or at least hope they join within the 1-3 hour mark, as these types of scenes tend to take longer to organize and prepare. So depending on if this has any opposition, I'd be happy to compromise and limit it to two votes instead of one. 

Speaking of opposition, still think we should make an announcement about this discussion so, y'know, people see it? It's something that'll affect most of the players in some form or fashion so it's prooobably best to let everybody know about it.

**Comment by ArbyTheDragon** [comment]
Just thought I'd make it known, I just got on when the shuttle arrived. It was the first message on my window. The round timer said 5:40.
Yow.

**Comment by Dhaeleena** [comment]
Im all up with what tempest says. Also if anyone has  big project it will always be better at the star of  a round, more people around to enjoy it, Doing a strip club 50 mins from the vote might not have the same results than doing it 50 mins Into the shift. In any case i feel like people should have more than enough time to wrap up anything they are doing in an hour.

**Comment by Yoshax** [comment]
I think it might be reasonable to perhaps just not have a vote at all, and always end the shift at when the vote would be, or at another set time. That way there's no uncertainty at all, and everyone is fully aware of the set, defined time constraints. If you went this route, you could also just make rounds a bit longer, perhaps an hour, so you get the best of both words, or something.

**Comment by Dhaeleena** [comment]
Hmmmm...we could make so the normal round always lasts 7 hours yea, And have like instead of a vote at 6 hours have like an automated announcement that states there is one hour left in the shift. It would work as a reminder to wrap things up

**Comment by Cameron653** [comment]
I'd support making it so there's only one vote to extend. It's nice to know that "Alright, the round ends at 6 or 7 hours, so I can plan to hop on at Y time for a new round.

**Comment by JemliRoivas** [comment]
I would support making it so that there's only the single vote.  I know I've decided to just wait for the next shift... and three hours laster, it's still the same shift with things starting to lag because the shift has gone on too long.

**Comment by Benemuel** [comment]
One vote would be nice just because it means I, won't be in the same situation Tempest was. Waiting a hour because the shift will end, because no point in starting a scene. And then it goes on for another hour. Then another. I have also had scenes that lasted this long, had no way to stop... And just kinda went to "...So. That weather." in the end due to people running out of things to do/say and no good way to end it.

**Comment by DemicusMaximus** [comment]
I'm in favor of a cap. Don't like being 'that guy' but more than once I've had to tell people "This round has gone on for more than seven bloody hours. Let it go." Jobs you want to do are taken, things like doing chemistry or growing in botany were fully finished four hours ago, nobody is mopping or anything so the station just LOOKS terrible... Extension is there so you can wrap things up. If its THAT important to keep going, bug an admin to delay. No reason to not have a cap.

**Comment by Brandysnap** [comment]
I've been in three rounds that have been over 8 hours. I think there was 7 of us. 4 were scening and the other three of us were just.. sat in the bar or pottering around waiting for things to finish. I'd rather have a single extention vote as well. so that's another for one extention.

**Comment by OrbisAnima** [comment]
On the technical side, I do have to remind most people that the game was originally made for short rounds of 2 hours, so its to be expected that the more time we extend a round, the more oddities we can find.

On the gameplay issue, I think it hurts quite a bit being unable to tell if you have to wait 30 minutes or five hours and a half. One extension is a good compromise, but even no extensions might be viable, there are few scenes that cant be continued with discord or just being mature about it and resuming the scene once the game restarted...

**Comment by Vorrarkul** [comment]
I'll throw my vote in with few to no extensions. There's nothing else to really say at this point to further my side of the argument; we just need to wait for someone who is pro-extensions to come along and present some sort of counterargument.

**Comment by Wickedtemp** [comment]
Yeah, so far this has been nothing but people voting for limiting extensions to a single vote.

**Comment by Arokha** [comment]
game_mode = EXTENDED_BUT_NOT_THAT_EXTENDED

**Comment by ArbyTheDragon** [comment]
This discussion is growing stagnent, and in that time, I recalled a critical problem with short rounds.
Before we go ahead and do anything at all in regards to this problem, I think one last thing must be said.

**There is a threshold round-time under which nobody will visit the kitchen beyond just sating a hunger debuff because the debuff can't occur before the round ends. This is due to the rate at which hunger increases being slow.**

This threshold seems to be around 90 minutes (1:30)

We might be okay because our round times will be 3:00, but for the double of this threshold, people may just wait for the shuttle and people will only visit the kitchen _once_.

In general...
Kitchen will get used less as the round becomes shorter because hunger takes time to accumulate.
I experienced this phenomenon on servers with short rounds from 1-2 hours in length. **The kitchen might not get used at all, especially by late joins.** _The obvious exception are people who eat for the sake of eating_. You can't accumulate enough hunger to get a movement debuff before the round ends.


### If we make the average round shorter, I think changing the initial hunger level at the round-start for everyone may be something to look into.

**Comment by SpadesNeil** [comment]
We're not making the round any shorter than it currently is.

**Comment by Dhaeleena** [comment]
I dont think this kitchen thing will be a problem. Everyone spawns with a random amount of nutriment, So people will use the kitchen depending that and also how much they have been running around, So i dont think there will be any change in behaviors when it comes to the kitchen being used

**Comment by ArbyTheDragon** [comment]
Is that so, Dhae? Hmm! Sometimes when I join the round, I'm almost immediately hungry. _It all makes sense now._ I kinda thought of it as buggy/obnoxious. Now I know it's for the better.
 
Yes, if everyone spawns with a random amount, my last post rising the 'kitchen issue' is solved.

**Comment by OrbisAnima** [comment]
Wait, Ace, I though the idea of the server was that players got screwed, otherwise what is the point of allowing erp?

**Comment by SpadesNeil** [comment]
You know damn well which definition of the word I was using based on the context of how it was used. :U Smartass.

**Comment by OrbisAnima** [comment]
:D It physically hurts me not to make a joke. 

Jokes aside though, I have no idea how to limit it to one vote per round, but is what will be implemented, right?

**Comment by SpadesNeil** [comment]
Correct. That seems to be the verdict here.

Admins should have the ability to override the limitation and set it higher if necessary.

**Comment by OrbisAnima** [comment]
they can already cancel the vote, then they can just recall for the vote, right?

**Comment by SpadesNeil** [comment]
I'll explain when I get home from work.

**Comment by Dhaeleena** [comment]
We usually dont like (atleast myself) canceling a vote that passed unless the server is exploding

**Comment by Cameron653** [comment]
bye
