### ISSUE TITLE
[GENERAL] Mining and other robots cant go to V2 Surface

### ISSUE THREAD

**Issue by User-U-U** [VOREStation/VOREStation#13958]
#### Brief description of the bug
Robots cant use the Aerostat computer to V2 Surface 

#### What you expected to happen
Be able to go to the main mining area on the SD

#### What actually happened
Access denied

#### Steps to reproduce 
- Be A robot
- Try to go to surface
- Access denied

#### Code Revision
-  61b9eebb8926747f7d3f160e99e10172100d15b4 
 

#### Anything else you may wish to add:
Please revert the shuttle console component #12425 I looked through it and it seems just locking out the helm console will do everything needed without causing annoyances like this.

**Comment by Very-Soft** [comment]
first, the main mining area for the SD is accessable via the mining shuttle, V2 is not the main mining area, it is an extra area you can access if science builds a pad or the ship moves there.

Second, I'm deffo not reverting that. I'd be much more open to just letting borgs use V2's shuttle for SD, instead of opening up a rules trap by allowing borgs to fly all shuttles again, but making it against the rules to do so.

If you want to fly shuttles, play a pilot.

**Comment by User-U-U** [comment]
> first, the main mining area for the SD is accessable via the mining shuttle, V2 is not the main mining area, it is an extra area you can access if science builds a pad or the ship moves there.
> 
> Second, I'm deffo not reverting that. I'd be much more open to just letting borgs use V2's shuttle for SD, instead of opening up a rules trap by allowing borgs to fly all shuttles again, but making it against the rules to do so.
> 
> If you want to fly shuttles, play a pilot.

Locking out the helm console only does this without further issues though.

**Comment by Very-Soft** [comment]
> > first, the main mining area for the SD is accessable via the mining shuttle, V2 is not the main mining area, it is an extra area you can access if science builds a pad or the ship moves there.
> > Second, I'm deffo not reverting that. I'd be much more open to just letting borgs use V2's shuttle for SD, instead of opening up a rules trap by allowing borgs to fly all shuttles again, but making it against the rules to do so.
> > If you want to fly shuttles, play a pilot.
> 
> Locking out the helm console only does this without further issues though.

If they can't access the helm, they shouldn't be able to access the ability to launch the shuttle either.

**Comment by User-U-U** [comment]
> > > first, the main mining area for the SD is accessable via the mining shuttle, V2 is not the main mining area, it is an extra area you can access if science builds a pad or the ship moves there.
> > > Second, I'm deffo not reverting that. I'd be much more open to just letting borgs use V2's shuttle for SD, instead of opening up a rules trap by allowing borgs to fly all shuttles again, but making it against the rules to do so.
> > > If you want to fly shuttles, play a pilot.
> > 
> > 
> > Locking out the helm console only does this without further issues though.
> 
> If they can't access the helm, they shouldn't be able to access the ability to launch the shuttle either.

This does not consider non shuttle items used by it, and if the core issues are robots flying off on adventures they can't do this without helm. This seems like a pointless nuisance. 

Other such issues.

- Being sent down with someone, that person dying, unable to hail back up.
- Shuttle elevators such as this,

This does not fix any issue though.

**Comment by Very-Soft** [comment]
Shuttles can individually allow or disallow borgs to use their consoles. Otherwise borgs wouldn't be able to use the any of the mining shuttles, which I know they can.

It is trivial to individually allow borgs to use consoles that are appropriate for them to use.

The PR you are requesting be reverted prevents borgs from being able to use BOTH the helm and the short jump consoles.

This was changed because there were too many cases of borgs volunteering for pilot work, and getting picked over pilots because they are walking all access cards.

This was not a small issue that only affected a few people, it was an increasingly normalized thing. It was changed like it is because there really aren't any realistic situations where a borg ought to be flying any ship over a pilot, and it's a little silly to allow something like that mechanically, and then punish players for using that ability.

Allowing borgs to take off in the shuttles, but not fly them is further silly, because again, they couldn't actually go anywhere with them. I could see this being used by borgs to turn shuttles into private dorms. Have them take off with the Starstuff to have their spicy scene, and then oops, the ship moved and now they can't get back. Or further, the shuttle is needed but a borg is using it. Now I gotta get on their case about it.

The problem you are complaining about in this PR is localized to a single shuttle on a specific map.

That is an easy problem to fix.

The rest of your complaint can be solved by faxing for a pilot.

**Comment by User-U-U** [comment]
> Shuttles can individually allow or disallow borgs to use their consoles. Otherwise borgs wouldn't be able to use the any of the mining shuttles, which I know they can.
> 
> It is trivial to individually allow borgs to use consoles that are appropriate for them to use.
> 
> The PR you are requesting be reverted prevents borgs from being able to use BOTH the helm and the short jump consoles.
> 
> This was changed because there were too many cases of borgs volunteering for pilot work, and getting picked over pilots because they are walking all access cards.
> 
> This was not a small issue that only affected a few people, it was an increasingly normalized thing. It was changed like it is because there really aren't any realistic situations where a borg ought to be flying any ship over a pilot, and it's a little silly to allow something like that mechanically, and then punish players for using that ability.
> 
> Allowing borgs to take off in the shuttles, but not fly them is further silly, because again, they couldn't actually go anywhere with them. I could see this being used by borgs to turn shuttles into private dorms. Have them take off with the Starstuff to have their spicy scene, and then oops, the ship moved and now they can't get back. Or further, the shuttle is needed but a borg is using it. Now I gotta get on their case about it.
> 
> The problem you are complaining about in this PR is localized to a single shuttle on a specific map.
> 
> That is an easy problem to fix.
> 
> The rest of your complaint can be solved by faxing for a pilot.

- Then why is the V2 shuttle restricted it is the better place to mine and it doesn't make sense to restrict it.
- Yes but I still find in as a blanket requirement not needed and only a nuisance as it doesn't effect the core issue.
- My original PR was edited as you made your first post and clarifies
- Same as above
- I provided a realistic reason and the consoles are not used only for shuttles they are used for elevators too and other gimmicks,
- Your example of turning a shuttle into a private dorm could be done by anyone, hasn't happened to my knowledge, and is against the servers self-antag rules.
- I am sure there are other maps that use shuttle based elevators that this issue hasn't been located in yet and for future maps is general requirement is unessacary for the reasons I sated above because restricting the helm console applies the same effect without requiring another thing for mappers to do that can be easily missed.
- Yes and it is with the helm console
- Borgs cant fax, and I doubt you want them faxing everytime they want to mine in the area on the SD with higher mine rates that other miners go to. I also doubt a pilot will be happy about showing up to hit one button and leaving.

**Comment by Very-Soft** [comment]
Borgs don't have access to the V2 shuttle because on the tether the V2 shuttle is part of an exploration level. There's no real reason for them to have access to any of the controls on that level.

When the SD was made, V2's upper level was repurposed to fit dangerous science stuff that couldn't fit on the ship itself.

Borgs can't access the shuttle on that version of the map purely because it was overlooked to add access onto the console.

V2 is also the only level we have that uses a shuttle like that, apart from the tiny shuttle and the mining shuttle on the tether, which does allow borgs to fly up and down. 

Any future shuttle elevators that might be added to some map, can similarly have that single variable adjusted as needed.

**Comment by User-U-U** [comment]
> Borgs don't have access to the V2 shuttle because on the tether the V2 shuttle is part of an exploration level. There's no real reason for them to have access to any of the controls on that level.
> 
> When the SD was made, V2's upper level was repurposed to fit dangerous science stuff that couldn't fit on the ship itself.
> 
> Borgs can't access the shuttle on that version of the map purely because it was overlooked to add access onto the console.
> 
> V2 is also the only level we have that uses a shuttle like that, apart from the tiny shuttle and the mining shuttle on the tether, which does allow borgs to fly up and down.
> 
> Any future shuttle elevators that might be added to some map, can similarly have that single variable adjusted as needed.

It is the only place on the SD worth mining for crystals. This is incredibly arbitrary to restrict it, and why would a pilot wan't to go down there every time a borg wants to mine just to hit a button its not even piloting related, your just unreasonably making a nuisance for both of them

**Comment by EtheoBoxxman** [comment]
> Second, I'm deffo not reverting that. I'd be much more open to just letting borgs use V2's shuttle for SD, instead of opening up a rules trap by allowing borgs to fly all shuttles again, but making it against the rules to do so.
> 
> If you want to fly shuttles, play a pilot.

The aerostat shuttle isnt even a shuttle, its a ferry. Its even called the aerostat ferry. Its only purpose and possible use is to get from the aerostat to the surface. 
I went and read through the discourse, and it feels liek theres some misunderstanding about what the ferry is, so I'm putting a picture here.
![image](https://user-images.githubusercontent.com/10347412/197308702-6381e7d9-9b07-4faf-a052-be47aeb9db17.png)

The only thing that prevents the general crew from accessing it is requiring either the ship be moved to V2, or the quantum pad be built. Once either of those has been accomplished, the shuttle actually has no access restrictions.
![image](https://user-images.githubusercontent.com/10347412/197308768-04aa2356-836f-46af-8ee3-32c56e7b1ff6.png)

This shuttle only disallows cyborgs from using it, and it has proven a problem many times already, the most recent was a scientist going into medical stasis and needing rescue- The captain had sent the cyborgs C-R and RW down to save them, and they were unable to do so because of the shuttle, which has no access restrictions, does not allow them to interface with it.
Only reason the person didnt die was because I'd been told after the roadblock b ythe captain that my scientist was in danger, so I got ready to go save them as well.

> This was not a small issue that only affected a few people, it was an increasingly normalized thing. It was changed like it is because there really aren't any realistic situations where a borg ought to be flying any ship over a pilot, and it's a little silly to allow something like that mechanically, and then punish players for using that ability.

This is where I think wires are being crossed.
The ferry is basically an elevator. Its used like an elevator. Its purpose is parallel to an elevator. And asking for a pilot just to press one button to move a shuttle down is honestly... Rediculous. I know I'd be salty if I were responding to a pilot request, fax or otherwise, only to learn all I'm needing to do is press a single button then wait around five minutes for the cyborgs to leave the shuttle _alone_, and that's not accounting for the fact that if I left them down there, they'd be stuck with absolutely no way to get back or ask for help- Unless the off chance there's already a cyborg on station to use binary to relay they are stuck.

Its either mining cyborgs are worthless for an entire week at a time, or cyborgs are placed in a situation where they can effectively be round-removed due to people forgetting they're on the planet. Its not fair in either way, as they are the only ones that this can happen to in this case. Even visitors are able to come and go on a whim.

This might not be a bug, but its definitely an oversight.
I dont think it should be left as is, and should be corrected to allow borgs to move the aero ferry, it shouldnt be against the rules to move a fancier elevator.
