### ISSUE TITLE
The Cool Snake Tail Sprite Has Eenie Meenie Miney TOES Poking Out The Front And That's Terrible

### ISSUE THREAD

**Issue by ResidentCody** [VOREStation/VOREStation#14109]
#### Brief description of the bug
The "Naga alt style dual-color (Taur)" tail sprite has a few pixels where a character's feet are uncovered when facing left/right.

#### What you expected to happen
When using a taur-like sprite (especially one that's meant to imply a distinct LACK OF LEGS) to not have any indication of having legs.

#### What actually happened
See below gif, I CAN SEE MY TOES AT THE BASE-FRONT OF THE TAIL. >:c

#### Steps to reproduce
- Make a character with the above-named tail
- Select distinct, easily identifiable sock and tail colors
- Witness your toes peeking out of your tail
 

#### Anything else you may wish to add:
- https://i.imgur.com/DefasrO.gif

**Comment by KillianKirilenko** [comment]
Right, hold still, I know how to fix this one. ✂️

More seriously this is probably because the server it was taken from actually hides the legs/feet in their entirety/doesn't render them, whereas I'd wager virgocode just kinda hides/masks them under the taurhalf. Adding a couple pixels to the side stances makes this an easy fix, but #14106 has the dmis busy for the moment.

**Comment by Heroman3003** [comment]
This appears to have been fixed at some point but not closed.
![image](https://user-images.githubusercontent.com/31296024/211980594-e74aa9f9-8979-4ee2-8aca-20b43a4f7f3f.png)
(character in question is wearing shoes).
