### ISSUE TITLE
Make Sec huds show a larger clickable sprite on micros

### ISSUE THREAD

**Issue by Somekindofpony** [VOREStation/VOREStation#1412]
With micros being so hard to fight back against, and how sprites work, is it possible to have a large square above the micro or something to be clicked on, maybe as a toggle in the sechud?

**Comment by Arokha** [comment]
Depending on what you're willing to sacrifice, may be hard, or not hard. For midsize micros, basically undoable. For the tiny ones, maybe.

**Comment by Somekindofpony** [comment]
I have several goats, what sort of sacrifice are we talking about?

**Comment by SpadesNeil** [comment]
I like the idea of a targeting feature on the hud. Not very useful for normal sized people, but if the person is less than normal size, it has this overlay on them

**Comment by Wickedtemp** [comment]
It'd be useful for the medical HUD's as well. It's difficult to see some micros, if ones sitting in a chair in the lobby, I OOCly might not even see them. This also goes for treatment, tiny sprite, harder to click, harder to save. 

Not to mention it's almost impossible to tell when a micro is injured because their health bar is literally 2 pixels long.

**Comment by Yoshax** [comment]
You could possibly create a transparent overlay or something along those lines, that just passes any clicks on it to its attached mob. Kinda like how some items have additional pixels added for clickability but are transparent.

**Comment by Novacat** [comment]
Targeting refactor has it so that clicking on a tile targets mobs within that tile. Closing.
