### ISSUE TITLE
Cargo Request events are not realistic or feasible most of the time

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#1414]
#### Brief description of the issue:
They've got a few issues. One example, every single one I've seen with the sole exception of a SINGLE time, it's asked for things that the crew can't even get. Primarily Myelamine and Osteodaxon. Every time. Chemists can't make those without carpotoxin and spider toxin, and even with admin spawned Space Carp, we still didn't have enough for one order. 

That's only the issues with the chemistry requests. I've heard a few players talk about the sheer difficulty of getting that super precise "31% Sleeping Agent, 33% Phoron, 36% Nitrogen at 2174kPa" canister. 

Also, well... Nobody bothers with these events. I've yet to see one actually completed. Apparently you get more cargo points, but the thing is, a few hours into the round, you have more than you can use anyways.

I'd suggest more reasonable requests and better rewards. I don't know, have a mech on the return shuttle and some higher level science equipment, like IMS', bluespace beakers, whatever the other departments get when Science is on the ball. Iunno, could be anything, just something to make these requests worth doing, because I personally want to do them but it ends up with the Chemical requests done, and literally nothing else.

EDIT: Here's a screenshot.
http://imgur.com/a/qKLZ5
These are the two requests that have come so far in the shift. BOTH require reagents that Chemistry can't even reliably get, and not only that, but as mentioned in the comment below, the gas percentages for BOTH of these orders don't even add up to 100%. One's 99 and the other's 98.

**Comment by ArbyTheDragon** [comment]
Sometimes, rounding is in the numbers so the percentages for the canisters doesn't actually add to 100%, so as engineering, I had to figure out what sort of rounding the game is doing. Push this pressure up to 4/10ths, pull this one down to 6/10ths, trying to dick around with the rounding.

There's genuine math involved, but not in a way that seems intentional, but in a way that seems caused by a bug.

**Comment by Wickedtemp** [comment]
Also in the vein of events like these, what about one where a few "SSD patients" come in from CC, requiring treatment? The shuttle departs in 30 minutes, allowing for plenty of time to get them surgery and aid and then buckle them back in! Just something that Medical can do, since sometimes full 6 hour rounds can go by and literally nothing happened, not even resleeving. 

Plus, this could allow a chance for newer medical players to get some practice in.

**Comment by ArbyTheDragon** [comment]
That's what I'd call an 'Ambulance' event!
Where events like the pirate raid brought plenty of CREW to the medbay for immediate trauma care, this event would leave our crew intact. I like it. 
Sounds like a nifty event but who says they have to be SSD? They could be former observers!
-I would be careful though. This could get stale of we automate it too much and take the reality of treating a real player away and render it into some inanimate 'brainless' body, of which SSD is a euphemism for.


I would also find it interesting if CC could _request bodies_ of a certain race and a particular appearance, since we recently acquired our shiny new body creator station. I always thought of Virgo as on the cutting edge of genetics, cloning, neuroscience, and general death-cheating technology. Such an event would be appropriate- and kinda fun considering _it lets us play with bodies._ 
c:

The code could specify colors of this and that aught to be on the body, but I'd just leave it up to an observer or admin to judge if the people who made the body f$@!ed up or not.

**Comment by Wickedtemp** [comment]
Closing this, because it's been open for so long that either it's fixed by now, or it never will be, or it doesn't need fixing. And I'd like to make a small dent in the absurd number of git issues
