### ISSUE TITLE
Help Intent Should Disallow Splashing With Containers

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#1415]
#### Brief description of the issue
Accidental splashing all over the face and body when that wasn't all my intent.

#### What you expected to happen
Cleanliness. Substances within their containers.

#### What actually happened
They were absolutely soaked.

#### Steps to reproduce
- Hold a beaker. Gotta scan this later to find out what's in it.
- Accidentally click on someone nearby.
- Find out it's acid. 

#### Code Revision
- Server revision: release - 2017-04-19
89b93ffc4e0a33a6e2f8b8b8fb34b346a2e92fa0 
 
#### Anything else you may wish to add:
- In all seriousness, help intent really should prevent this from happening. Several times while playing in Medical on my laptop, with a touchpad, I've gone up to a patient to give them this life saving elixir that they so desperately need... And I just end up pouring it aaaaall over them. And now I'm out of medicine. 

In one instance, the patient actually began screaming that I dumped 'harmful chemicals' on them and that they blamed it for their broken bones and internal bleeding. In reality it was just tricordrazine, but it was a super super minor thing that could've been prevented with this sort of thing.

Also hey. 

Hey.

Don't you hate it when you splash phoron on the floor?

**Comment by Somekindofpony** [comment]
Yes, absolutely yes. I don't want to splash water on the floor in that one pixel space between the chemmaster.

**Comment by SeigaSeiga** [comment]
Wasn't that one pixel fixed at some point? #892 But regardless would still be a nice QOL feature and prevents nearly all accidental phoron spills that defined chemistry on pretty much all codebases for a long time.

**Comment by ArbyTheDragon** [comment]
That's why you put lids on the beakers and bottles, silly! Sorry to hear you're stuck, having to use a trackpad.
Personally, I have hotkeys enabled, and use X to switch hands.

Panicking medical staff who aren't paying attention to what they're doing might splash a solution all over someone instead of injecting it into them with a syringe properly. I did this at least several times in the past.

IMO, what followed and the things the patient accused you of are hilarious.
I think the fact this accident can occur is quite fun. In reality, if this couldn't occur EVER (at least not by accident), would there ever be phoron spills? In the name of fun and interesting roleplay, there should be a price for not 'handling with care'.

**Comment by Wickedtemp** [comment]
The moments you're most likely to spill are:
- Moving the beaker from the dispenser to the chem master.
- When you're treating a patient, if you have the bottle inhand.
- Literally anytime when you're using a touchpad.

And sure, it CAN lead to roleplay... Roleplaying being irritated and having to watch engineering siphon out and replace the air in your lab. Which for me personally, not really fun or engaging roleplaying. 

As far as handling with care goes, not using help intent would count. 

This also fixes the fact that right now, you can be on help intent but still pour acid on people. Pretty sure you can still hit people with other objects while on help intent, I'd personally like to see that fixed as well to be honest.

**Comment by ArbyTheDragon** [comment]
I do my best to ensure the beaker is NOT what I have selected when I click anything.
I'm not saying your reasoning is garbage- these are perfectly fair reasons to want to change this, but I'm just saying I'd like it better if we could continue to be clumsy in this way.

**Comment by KiwiDaNinja** [comment]
I'd definitely say that this would be a good addition...I cant even begin to count how many units of medicine - expensive or otherwise - I've wasted because I was trying to shuffle bottles around after dispensing them from the fridge, and look down to notice I've emptied an entire one out or something. Not to mention, phoron spills are certainly not fun.

**Comment by SilencedMP5A5** [comment]
yes please. that's all i can say on the matter. i've wasted fuckloads of meds because >accidentally click the floor inbetween the legs of the chem master

this is a needed change.

**Comment by PhoenixGamma7** [comment]
Yeah, this would be pretty nice. Mainly you only spill beakers when you miss a click by a few pixels, and even if a scene comes out of the mess it's not a fun one! Enjoy having your chemlab locked down. As someone who spends a lot of time in medbay, this would be a godsend.

**Comment by SpadesNeil** [comment]
Is this still a problem?
