### ISSUE TITLE
Give Synthetics a way to deal with very low damage on their own.

### ISSUE THREAD

**Issue by Somekindofpony** [VOREStation/VOREStation#1420]
#### Brief description of the issue
Organics have regen, but synthetic limbs don't. So if you're hit by a flying piece of paper and take .01 damage, you show up as harmed, despite it meaning nothing.

#### What you expected to happen
Either to be able to fix this annoying thing on your own, or prevent it all together.

On the spacelobby discord, we've discussed several possibilities. First was minor damage reduction which prevents any damage lower than a certain number from being taken, but if it's higher than said number, you take the full amount. This would stop rogue paper from cutting you as a synth.

We've also discussed space glue, something that can repair up to a certain amount of damage, but if it's serious, you can't fix it with that. This could go in a loadout tab for anyone with a prosthetic to use.

**Comment by Dhaeleena** [comment]
I really like both ideas. One the Damage Reduction D&D/Pathfinder style of only taking the full amount of damage if the number is greater sounds cool and Makes a lot of sense for a synth.
Glue can be cool too, But i like the first idea more if it is even possible...The thing is Defining what amount of DR is balanced

**Comment by Somekindofpony** [comment]
I'd say three damage seems fair, no one's going to be attacking someone with something that weak aside from a dinnerware in the kitchen when it goes rogue. Though, one damage is enough to stop papercuts and other accidents.

**Comment by Arokha** [comment]
Thas' not how D&D/Pathfinder DR works. `The numerical part of a creature’s damage reduction (or DR) is the amount of damage the creature ignores from normal attacks.`

I will say that the first is much more problematic to code. Because obviously it would depend on damage source. EMP does brute damage too, but we wouldn't want to have the DR affect damage that is nonphysical like that. What about space? Space does tiny amounts of damage very quickly. This would also basically make them immune to that.

The amount of snowflaking surpasses what I'm willing to code. Just add a more common way to repair small amounts of damage.

**Comment by Somekindofpony** [comment]
Like the spaceglue?

**Comment by Arokha** [comment]
Yup. Though I'd suggest less than 3 per thing, if it's going to be a reagent, since you can carry obscenely large amounts of reagents (1800 units in a medical belt, give or take).

**Comment by ArbyTheDragon** [comment]
I would somewhat like to dispute that being hit by an object like paper deals damage to you, but I wasn't a synth. Before I go on, I wanna ask if this is really such an issue? Could a changing of the damage text be in order for this? Changing "It looks damaged" when the damage is anything above 0 but less than X, to "It looks slightly scratched / the paint looks worn slightly." when damage is anything above 0 but less than X, where X is a VERY small number.

But paper seems the least of the problems. A rework of how damage is calculated from flying objects could be called for. Lemme tell you a story of why.

Once upon a time, don't even remember the server (It might have been old vorestation? on bay code?) I was space walking with a backpack loaded to the brim with fire extinguishers. I was Shirishi As'tahk, an Unathi bartender who found out how fun it was to float about using a fire extinguisher for propulsion.
I was orbiting around the exodus station and having lots of fun. _I was just coming around to the cargo area where the trash launcher was when I saw it fire._
My heart STOPPED.
I fully expected to be an unrecognizable splatter of flesh after being hit by that launcher turned carronade, filled to its maximum with various articles of trash, even though my voidsuit 'absorbed some of the impact'.
My entire chat window was flooded with red text of the scores of items I was hit with. I didn't bother scrolling up all the way.
I dared look back at the main screen, and saw I was still alive. A massive pile of trash was in the middle of space to prove that I had indeed been hit. I voice my 'pain' on the radio, at least trying to act as though I was actually shot by this railgun. I also told everyone on OOC how perfectly timed the shot was. Miraculously, I was unhurt. I think my health indicator still said 100%.
Wtf, I thought. 
If I was hurt, it didn't necessitate that I get treatment. It defiantly didn't rise above _"My chest hurts"_, that I remember explicitly.

So that's my story.

**Comment by Very-Soft** [comment]
Tbh? Welders and wires are really super common. They're ALL OVER. There's two different tool storages that you can almost always find some at, and if that fails, there's usually more in maintenance. I've been playing a synth a lot lately, and they are so common that I can almost always find a pair of welding goggles, wire, and a welder within a few minutes of getting on.

I think their lack of regen and the slight annoyance that can come with that is sort of the price you pay for being immune to lots of different negative things, and having pretty much unlimited food supply un that you can just walk over to recharge. 

I think that a space glue, or something like it that was more common and didn't damage the eyes might be nice. But then at the same time I might suggest, make it so synths don't take eye damage from welding themselves? Welders are abundant. Welding goggles are admittedly less so.

**Comment by Very-Soft** [comment]
I got a different idea. What if it wasn't space glue but, 'Prosthetic Polish'

use on damaged part, only works if part is damaged like, 5% or less and has a 5-10 second interruptable cast time?
That way the welder's still useful for self repair of bigger damage, and it doesn't allow you to be cheap and heal all the things.

**Comment by ArbyTheDragon** [comment]
Yes. I wanted my argument to simply be that. You're a synth. You do not regen. This is the price you pay for being a synth. Deal with it.

I just couldn't think of a way of putting it nicely.

In comment to eye damage to synths from welders- I think this shouldn't change actually. Not only would it probably be a hassle to code, but physically, **you can even damage digital capture devices from exposure to too much light.**
I've seen some people who like to play with powerful lasers have dead pixels in their cameras even though they never shined a laser directly into the camera optic. The glare off a wall can be that powerful. Recently in my engineering class, we were trying to take some pictures of us working, sometimes while welding. Near the arc-flash, nothing is discernible in the picture. Forcing the camera to look at this light that's as bright as a neutron star would surely damage the pixels. Synths would be no different.

**Comment by Very-Soft** [comment]
Yeah I tend to agree. What do you think of that prosthetic polish idea? That seems more similar to stuff that's already in the game, and would work as a solution for this problem, that doesn't change much about how everything do.

My main reason for considering this more deeply, is that there are a bunch of jobs that don't have maints access. Which is where most of the welding helmets and goggles are. So, a generally widely accessible maintenance polish does kinda make sense.

**Comment by ArbyTheDragon** [comment]
Hey, why should it be prosthetic? Why can't it just be polish? Putting wax on a car- how is that different from putting wax on that shiny steel arm of yours?

**Comment by Dhaeleena** [comment]
I really dont think "deal with it" or "Just ignore it" Are valid arguments in any way.
A simple addition such as a small bottle of Space glue similar to the crap that is used to Fix cracks in windows would be pretty cool so i dont have to WELD A MOUSE BITE IN MY ROBOTIC ARM.
Anyways i think the space glue as a loadout item that can heal very small amounts of *brute* damage to Synthetic limbs is a good idea

**Comment by Arokha** [comment]
> Why glue, because Tape would be very dumb, Wax could work? But sounds weird, Glue is actually used IRL to close some kinds of cuts in the skin

Tape is too. They are called bandages.

**Comment by Dhaeleena** [comment]
But tape on fur sounds like an awfully bad idea o3o

**Comment by Dhaeleena** [comment]
And im going to just note again. This would be just, Another way of healing, One, much less useful, Much more limited than any of the other ways of healing for a Synth. This is just so there is another option to healing a *3 points of damage caused by a mouse or an apple* That isnt a welder, It would be a limited Loadout item with limited amount uses that Heals Up to a certain point, Otherwise it would not work at all because you would not be allowed to heal 60 points of brute damage my spamming 3 points of heal using this, Because the thing would only work if you have 3 or 4 or something. *3-4 points get healed. But if you have 5 you have to get a welder or something else*

**Comment by Wickedtemp** [comment]
If it's a reagent, give it a recipe and Chemistry can provide it. I'd probably recommend...

Silicate + Iron/Aluminum = "Epoxy". Apply with a dropper.

**Comment by Treasa729** [comment]
Just a thought I randomly came up with on this matter: Since coding DR would be difficult because of interactions like with space, digestion and such something I thought of would be kind of like a damage buffer. Almost like temporary hit points in DND. I'm not sure how feasible it would be code wise, but perhaps an item like polish could add essentially 'negative damage' which acts as a buffer to damage taken. Any damage you'd take would go to that before it goes to inflicting actual damage. It would still be something that takes a really long time to apply, and which would only protect against a few points of damage before needing to be re-applied.

**Comment by Dhaeleena** [comment]
@Treasa729 I like your idea, But that sounds incredibly complicated to code.
Also this whole issue is just to make repairing Super light damage more...fluff friendly?
What i mean, is just that, Fixing a tiny Cut on synthetic flesh in an arm with fur using a *Burning Hot welding tool* Doesn't make sense, But using some glue to fill up the gap and stick the synthetic flesh back together sounds more user friendly and its better fluff wise

**Comment by ArbyTheDragon** [comment]
Trauma kits change what messages they give based on how bad the damage is and what the, and if it's bleeding or not. I recall that a huge bleeding chest-wound from a surgical drill _(I promise it was for science)_ has you just stuffing gauze into the big hole that was once their chest instead of bruise patches or other means. It might even take into account the nature of the damage such as laceration/blunt bruising/puncture/burns, but I haven't tested this and can't recall any notable incidents where this clearly appeared to be the case.

Maybe synthetics could get some thing up their alley that behaves in a similar way? 

I don't really understand the mechanism behind trauma kits, but couldn't the glue be similar?- you just need a lot 'glue' to heal a lot of damage, which is already true for trauma kits. (at least it seems this way)
_Maybe this glue becomes exponentially ineffective (expo decay) as damage increases?_
It'll be the difference between _joining two panels who's original binding agent has broken_; healing 5 of the 5 total damage
and _frivolously attempting to mend the shredded steel with simple adhesives_; healing 1 of the 30 total damage.

**Comment by Dhaeleena** [comment]
Ok so here are some things. First, the trauma kits use Regenerative membrane, Thats why you can fix up "Holes" A whole lot of glue is just going to fill the hole whit glue, Not fixing the problem at all, Now, NANOPASTE is the synthetic Trauma kit, Nanites that regenerate robotic synthetic tissue.
Then again, The idea of this glue existing is not to add another super effective and viable way to repair heavy damage on synths, Its just to fix a maximum of lets say 5 damage, But only if you got 5 damage or less since people seem to have been worried this would somehow throw synths over some balance cliff into a super OP realm of OPness or somethan, which i find silly. Anyways, we could add additional mechanics to it i guess, Im just happy with it being being normal glue for very minimal damage

**Comment by Arokha** [comment]
Nanopaste. Just ask R&D for it (they start with some, and can make more), or medical (they start with some, and have additional random spawns of it, and rarely use it). Or now, #1626 medichines for synths.

Keep in mind nanopaste is in 10-stacks. You could just ask someone for 2 rather than taking their whole thing.
