### ISSUE TITLE
Washing machines no longer accept bedsheets

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#1456]
#### Brief description of the issue
Washing machines no longer accept bedsheets.

#### What you expected to happen
To be able to gather up the linens in medical, wash them, and change them.

#### What actually happened
Beating the washing machine with bedsheets like a cave person.

#### Steps to reproduce
- 1.Get a bedsheet.
- 2.Try to wash it in a washing machine, as you do.
- 3.Grunt like a primitive while you whip the machine into submission with the sheet.

#### Code Revision
- Server revision: release - 2017-04-30
92420a6da5a611d0f561aa7a4e8785d2e439c50b 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ArbyTheDragon** [comment]
Defiantly a new bug. Unfortunately, I don't remember the last time I washed bedsheets.
Should be as simple as adding them to the list of acceptable items.

I don't know when it changed, but I do know why this is happening.

`washing_machine.dm` works by first checking if an item is on the `disallowed_types` list, which are any items that fall under `/obj/item/clothing/suit/space` and `/obj/item/clothing/head/helmet/space`, and displays a message that it "Doesn't fit" if you try.
Then if it's not on the disallowed list, an elseif will allow you to insert an item- **but only the items-** that satisfy later logical statements, notably `else if(istype(W, /obj/item/clothing))`

**Hilariously, bedsheets are actually classified as weapons** according to `bedsheet_bin.dm`.
It shows the type of the bedsheet is `/obj/item/weapon/bedsheet` which is clearly not in the list for the washing machine. 

Since it's not on any list, it is my guess that it doesn't know any other reality than to be violently bludgeoned by said item.

Someone else will have to fix it. I'd add everything under the bedsheet type myself, but I'm not sure if `istype` accepts more than one type.  We may just need to make a new elseif statement to include anything under the /weapon/bedsheet/ types. 

Here's some example code I made out of whimsy. This may actually work. I never tested it, I just kinda made it. If a coder can look it over and thinks it works, fine. No need to give credit.
```
else if(istype(W, /obj/item/weapon/bedsheet))
		if(washing.len < 5)
			if(state in list(1, 3))
				user.drop_item()
				W.loc = src
				washing += W
				state = 3
			else
				user << "<span class='notice'>You can't put the bedsheet in right now.</span>"
		else
			user << "<span class='notice'>The washing machine is full.</span>"
else
```

**Comment by DeepIndigo** [comment]
It's actually pretty old, been around for months now.

**Comment by ArbyTheDragon** [comment]
Sorry to say this is still a bug.

**Comment by DeepIndigo** [comment]
It's been around since like.... October I wanna say.
