### ISSUE TITLE
The supplies event is always ignored.

### ISSUE THREAD

**Issue by Somekindofpony** [VOREStation/VOREStation#1467]
#### Brief description of the issue
The event is supposed to be engaging and get everyone to work together, but it's always ignored.

#### What you expected to happen
Everyone to work together and enjoy the benefits of extra cargo points.

#### What actually happened
Everyone ignores them and carries on.

#### Steps to reproduce
- (Step 1) Have centcom announce that they need supplies.
- (Step 2) Everyone ignores them.

Lowering the amount of items needed or giving alternative rewards could make the event more accessible and enjoyable to whoever wants to try and take it on. It needs a small rework of some kind.

**Comment by Yoshax** [comment]
I feel it's ignored for a few reasons. 
1. It can be impossible to complete. They can ask for things that are physically unacquirable like drinks requiring Nothing, or things that are just unfeasible during most circumstances, like the chems requiring carpotoxin/spider toxin. One department being able to fulfill makes the whole thing pointless. 

2. Leading on from above if one department doesn't have the staff for whatever reason, maybe they're afk, or otherwise busy, it makes the whole thing pointless for everyone else. 

3. The reward is small and non existent. For most people involved, there's no reward at all. Cargo gets a small cargo point bonus to which they can use to order junk for themselves because nobody ever needs anything from cargo, because there's basically nothing useful or needed to order. Most departments get nothing from participating so there's no motivation to do so. 

4. It's frequent and can occur multiple times per shift. It gets dull when repeated so much, as does most things. People enjoyed it when it was first released but interest dropped over time.

**Comment by SpadesNeil** [comment]
How about a chance to win some SPICY HARDWARE such as a Phazon?

**Comment by Yoshax** [comment]
That would probably only be a reward for cargo really, I imagine, or something. It's just hard to actually give everyone a reward and make it worth their time. More meaningful things to order in cargo for high amounts of points and more cargo points from this event might help.

**Comment by Wickedtemp** [comment]
We have two GitHub issues concerning this now,

**Comment by Wickedtemp** [comment]
https://github.com/VOREStation/VOREStation/issues/1414

Iunno how to reference these or edit comments on mobile, so...

**Comment by SpadesNeil** [comment]
This feels like somewhat of a duplicate, then.
