### ISSUE TITLE
Resleeving out of, then back into body deletes stomachs

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#1474]
#### Brief description of the issue
I made a custom sleeve. Sleeved into it. Had stomachs
Sleeved back into an original body. No stomachs.

#### What you expected to happen
Retaining my stomachs

#### What actually happened
They were deleted. And when I cryo'd and rejoined, they were still gone.

#### Steps to reproduce
- (Step 1) Make a body.
- (Step 2) Sleeve in
- 3 Sleeve back to original body or a new one
- No stomachs

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 2017-04-30
92420a6da5a611d0f561aa7a4e8785d2e439c50b

**Comment by Natje0** [comment]
A good few hours later, as I went on the same character on a different computer, despite having Saved the stomachs after re-making some... They returned. The 8 stomachs that were deleted suddenly came back. That made me happy.

**Comment by Arokha** [comment]
This might be a little unexpected on how this works, but if you use the character setup during the round to design/change stuff about another character, or make a new one (which I'll assume was the case here, maybe bored while dead? I don't know), when you get put in a body, it'll use THAT save slot's bellies.

The reasons are practical ones.
Option 1) Save bellies with bodies so printed bodies have their original bellies.
Problem 1) Then you have those bellies and if you click save your original ones are overwritten if that was someone else's body, or a new body.

Option 2) Give you NO bellies.
Problem 2) Same as 1, really. Just you'd end up wiping out your bellies.

Option 3) Load your bellies from the currently loaded character when sleeved.
Problem 3) Not realistic, since you have bellies from a character in another body if you swapped bodies, but it prevents you from accidentally overwriting your bellies.

So we use Option 3. Unfortunately it means if you do anything in character setup like loading another slot, or making a new one, next time you get resleeved it's like "oh great, I'll use these bellies here" and loads THAT character's. You probably saved those stomachs onto whatever other slot you had loaded.
