### ISSUE TITLE
Prometheans are Too Dark

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#1479]
#### Brief description of the issue
Initially, we had an issue where prometheans were too bright; the darkest they could reach was a neutral grey. Well, now we have the opposite issue: prometheans can be neutral grey at the absolute brightest.

#### What you expected to happen
To have the full range of color on prometheans, like most species

#### What actually happened
![image](https://cloud.githubusercontent.com/assets/17329033/26167289/3e19f972-3aeb-11e7-9b4a-3e687d3b1b5e.png)

#### Steps to reproduce
- Be a promethean.
- Try to be a light color, such as human skin toned, or even white.

#### Code Revision
- 92420a6da5a611d0f561aa7a4e8785d2e439c50b

 
#### Anything else you may wish to add:
- N/A
- EDIT: This particular screenshotted promethean is my attempt on a "half-promethean" character, meant to have patches of opaque skin that constantly solidify and liquefy on her body. I had to hunt for a good dark skin shade to match the promethean's normal significantly darker skin tone. You can see the values in the screenshot as well as the result of them.

**Comment by Arokha** [comment]
This is due to the difference in the base species color sprites. Some species base sprites are black, some are white. The white ones use color multiplication to set the color, the black ones use color addition.

This results in prometheans having different coloring methods depending on what shape they are in, which can have varying results depending on the species. Prometheans themselves are set to use mult, which means they would look good with most vorestation-added species, but not most of the stock species.

**Comment by Arokha** [comment]
This is basically impossible to fix.

**Comment by Screemonster** [comment]
Unless we go through all the species sprites and change them all to COLOR_MULT this isn't fixable.
This will be tedious as fuck unless I can find a way to batch-process the fuckers :v

**Comment by Vorrarkul** [comment]
I'll give my hand at changing the sprites. Just need to be pointed to which to change, and an example of what to change it to.
