### ISSUE TITLE
[GENERAL] Synthetic monitorheads cannot change display as a Custom Species.

### ISSUE THREAD

**Issue by Breeii** [VOREStation/VOREStation#15094]
A full-body positronic/synthetic cannot change their monitor display if they are based on the Custom Species setting, only if they're based on the Human species. The display will remain blank and nothing will change when setting monitor display or altering monitor layering.

**Comment by liache** [comment]
Seconded. It also appears that human bases don't allow for some of the monitor heads to be selected. Just stays human.

**Comment by TankTheBirb** [comment]
After looking into this, the bug is because the head organ for custom species does not properly get the monitor head icons from the setmonitor_state() proc. All other species tested do.
![image](https://github.com/VOREStation/VOREStation/assets/96669534/49d914e8-bceb-46af-a036-9832704a706d)
Custom species use human_face.dmi for eye_icon_location no matter what they are named, what their base sprite is, or what their monitor head is. The proc does not error out at any time, going through its prompt chain but does not update the icon at the end. The proc exhibits the same effect on all monitor heads tested (ones referring to monitor_icon.dmi and monitor_icons_vr.dmi), the species of the mob is what matters.
