### ISSUE TITLE
Railings should stop Teshari movement

### ISSUE THREAD

**Issue by Fevix** [VOREStation/VOREStation#1522]
#### Brief description of the issue
Teshari can walk straight off of railings

#### What you expected to happen
Railings stop Teshari movement unless you actually click and/or drag yourself over them

#### What actually happened
Lagged for a few seconds, got to watch my character simply walk off the railing

#### Steps to reproduce
- Play Teshari
- Walk towards railing

#### Code Revision
release - f2c9a3a54e980f6e578ad278651b12887b610f3c

**Comment by Ketrai** [comment]
I play as a teshari myself, I think this is actually quite funny, I haven't gotten any issue with it yet, except that one time I fell of twice in a row and got into redcrit.

**Comment by Arokha** [comment]
I've so-far seen two regular Teshari players ask to NOT be prevented from falling through.

**Comment by SpadesNeil** [comment]
I might mark this as wontfix.

**Comment by Treasa729** [comment]
One possible solution for this would be adding a verb for Teshari which allows them to toggle their ability to ignore tables (and railings) on and off. That way one group of players isn't left out. It could be in the preferences tab like the intent requirement for firing a gun or something like that. There could be one for railings specifically as well rather than having the whole ability get toggled on or off.

**Comment by Fevix** [comment]
I'm 100% for having an option to turn this off. This table-ignoring movement has been the biggest annoyance for me while playing Teshari. At least with the metabolism you can nick a box of donk packets, but try to run up to the bar and sit on a stool? Whoops, you held the button just slightly too long and suddenly you're trespassing.

It's never made sense to me how a species meant to be shorter has so much of an easier time getting onto tables/over railings that they don't even have to think about it to do it. Are Teshari known for having instinctual jumping abilities when encountering an eye-level obstacle?

**Comment by AeroWing** [comment]
I thought it was actually intentional at first because they could be too short to actually get caught on the railing. Maybe having a verb to prevent ducking under tables, etc. that would also prevent tesh from bypassing railings would be a nice solution? Otherwise I'd leave it be mainly because the railings aren't just for z-level as they are found elsewhere blocking off certain areas in maint that could prove useful for a tesh to zip though if hunting or hunted.

**Comment by kcin2001** [comment]
the whole verb to prevent hopping through things like that would be wonderful because the first time you fall off the third floor is ok, the next 3 times it starts to just be sad
