### ISSUE TITLE
Add prebuilt macros for up/down Z

### ISSUE THREAD

**Issue by Fevix** [VOREStation/VOREStation#1523]
For example, clicking a staircase takes the eye to the Z-level the staircase leads to, or clicking Open Space takes you down to the z-level shown below

**Comment by Screemonster** [comment]
tbh just give them up/down arrow hudbuttons.

**Comment by Arokha** [comment]
There's a verb to move up/down wherever you are already, it's in the IC tab because it applies for humans and silicons and everything, as they can all climb up/down on lattices or use jetpacks to jet around or walk up/down walls with magboots.

Personally I macro'd it to O and P, but maybe + and - would be easier to remember or something. I often forget which way was which. Or I mean for AI anyway you could just bind it to Q and E for easy reaching.

New HUD stuff is not impossible but also way harder than just "Hey use the existing verbs".

I'll leave this open if people have any suggestions for a premade set of keys to do this (I'm unaware of a way to do it for 'just AI' so it'd be for normal guys too).

**Comment by Dhaeleena** [comment]
Lifeweb uses page up and page down, And i guees that makes sense? *shrug*

**Comment by Arokha** [comment]
Super annoying on a lot of laptops. On some it's like Fn+Up and Fn+Down.

**Comment by Fevix** [comment]
I'd still like to see some GUI elements for it or something. Having to hunt down verbs and/or set up macros is a bit much for someone whose never done it before.

**Comment by Dhaeleena** [comment]
Nothing to do with this. But i would love to see the chair that im buckled to in the HUD somewhere, Like in tg, And im sure macros will love that.
Anyways dunno..Uh just use numpad? Shift+directional key Up down?

**Comment by chaoko99** [comment]
Could always use < and >
Y'know. Like Dwarf Fortress, as well as literally every popular MUD.

**Comment by Heroman3003** [comment]
Testing the bot comment
