### ISSUE TITLE
Volatile fuel needs to be fixed or removed.

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1542]
#### Brief description of the issue
Related to Yosh's comment #1396 because it's still an issue.

Basically, Volatile Fuel is a pain in the arse. It doesn't show up on air alarms, gas scanners, or any other means of detection, and scrubbers don't appear to remove it. It's something that players can handle, but only if they specifically know about it, and if they don't know about it they're fucked.

It's practically the _definition_ of a missing stair problem.

It either needs to be fixed so it shows on air alarm readouts and scanners, and can be scrubbed by air scrubbers (portable or otherwise), or it needs to be removed from the random gas leak event.

#### What you expected to happen
Players to have a reasonable chance of knowing of or avoiding something that can kill them in an instant.

#### What actually happened
Someone lit a cigarette in the cafe and three people died.

#### Steps to reproduce
- wait for volatile fuel leak
- look for it on air alarms, analysers, and PDA scanners and find nothing
- attempt to scrub it
- fail, die in a fire three hours later anyway.

**Comment by ArbyTheDragon** [comment]
It DOES show. The alarms detect it, but don't display the percent. The PDA scanners show the fuel as 'unknown'.
It's not a normal gas like the big five, (O2, N2, N2O, Phoron, CO2), and the scrubbers don't work on it. It does seem to be removable if you pump all the air out and let the station atmos system filter it out. Basically you gotta vent the whole room and repressurize it.
Or... You can burn it.

**The ROOT of this problem is that scrubbers don't work on it. If they did, it's perhaps not even as bad as a phoron leak.**
TBH, I had a lot of fun that round, but I love chaos and many are not like me :3

**Comment by Screemonster** [comment]
The round wasn't quite so fun for the people who had to sit in deadchat because someone who didn't know about the leak decided to have a smoke. And like you said, if it wasn't such a pain to clean up, it wouldn't be so bad. Knowing the gas is there isn't much help when there's no reasonable way to get rid of it.
