### ISSUE TITLE
Engineering Mapping issues

### ISSUE THREAD

**Issue by Poojawa** [VOREStation/VOREStation#1603]
Engineering Cameras aren't labeled helpfully. 'The Engine room' 'The Atmospherics' 'Engineering Aft Hallway' for example are just the same labels for different cameras

Engineering in general is laid out horrendously, there are no safe guards and not enough walling/id-locked doors protecting critical areas such as the engine room itself. RCON consoles are secured by a single R-window and a table for anyone to flip switches as they want. If they decide to wander into the control room, they can do it without even worrying about a table. Shocked Grilles are just idiot deterrent/Atmosia trap, not actually a defense.

Engy EVA is cut off from the department, There's no other way but outer space or the hallway to get inside it.
 
No atmosia to really speak of, area scrubbers seem like excessive overkill or just not wanting to place enough piping down/airlocks. Pressure tanks as objects pale in capacity to the specially mapped floors that hold hundreds of thousands of KPA with basically infinite moles.

There's two 'Bar' Substations. Substations in general do not respond to the power net very well, if at all. 

the Workshop is on the literal other end of engineering from EVA, making rapid response not all that rapid at all if one wants to gear up.

**Comment by Poojawa** [comment]
Not like any of this would get fixed.

**Comment by Screemonster** [comment]
Except these are still valid issues worth looking at next time map adjustments are made.

**Comment by Arokha** [comment]
Just to add more information to this:

RCON consoles (most engineering consoles) require engineer access to use.

The area scrubbers are for emergencies, because normal scrubbers are extremely ineffective at cleaning up phoron, and nobody wants to wait 2 hours for them to clean up the entire atrium area. They're only in the atrium area, because it would take so long to clean. There's no real opportunity to put airlocks to reduce the volume of that area since it's a giant vertical hole. Even if one were to cut off hallways leading away from it, even the middle atrium 'hole' area would still take a *very* long time to clean with normal scrubbers, and portables would almost instantly fill up.

The 'basically infinite moles' is why the pressure tank rooms were NOT used on this map, because there's an outdoor supply of air. However the tanks don't start with enough on the current map, which we can improve.

Duplicate bar substation was fixed.

What would you suggest about the engineering EVA?

**Comment by SpadesNeil** [comment]
This is probably resolved by the recent map edit. Closing for now.
