### ISSUE TITLE
Deafness in NIF Soulcatcher causes headset vibration

### ISSUE THREAD

**Issue by KotetsuRedwood** [VOREStation/VOREStation#1757]
#### Brief description of the issue
While in a NIF's Soulcatcher with external audio input disabled, messages that would be sent over common channel transmit a "You feel your headset vibrate but can hear nothing from it!" even though being in a soulcatcher means you have no headset.

#### What you expected to happen
No indication that any messages were sent over common.

#### What actually happened
"You feel your headset vibrate but can hear nothing from it!"
"You feel your headset vibrate but can hear nothing from it!"
"You feel your headset vibrate but can hear nothing from it!"
"You feel your headset vibrate but can hear nothing from it!"

#### Steps to reproduce
1. Get your mind stolen by a cute person with a NIF and a soulcatcher
2. Have them implant your mind into their soulcatcher
3. Have them disable external audio input.
4. Be unable to hear over comms that a teshari fell off a railing. again.
(Optional. - get utterly dominated within soulcatcher)

#### Code Revision
Server revision: release - 256e1db4d6e43368e3e53cf3027e5ae395abdacd 
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/10330701/27257819-7c499742-53dd-11e7-8051-30889ab77676.png)

**Comment by Arokha** [comment]
This is because you're inside a thing inside a thing inside someone with a headset on. For whatever reason, headsets are actually just like handheld radios that broadcast messages out loud when you get them. But only if they're on an ear. And only to the same turf. That's why you can hear your pred's radio when you're in them, or being pinned/resting with them.
