### ISSUE TITLE
Emergency Treatment Center: No Defib/Surgery/sink

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#1762]
#### Brief description of the issue
Emergency Medbay has to Defibrilator.
Also can't do surgery there.
Oh, and no sink. Dirty hand doc.
#### What you expected to happen
Save my patient

Be able to do surgery during emergencies.
#### What actually happened
Screamed for a defibrilator while Singularity consumed the Medbay above. Got Starter Cables delivered.

#### Steps to reproduce
- (Step 1) Go to emergency medbay
- (Step 2)Be unable to fix emergencies.
- (Step 3)Have filthy hands.
- (Step 4) Scream.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 256e1db4d6e43368e3e53cf3027e5ae395abdacd 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Emergency Treatment Center, Base floor 3.

**Comment by Dhaeleena** [comment]
I dont think that place is supposed to have a surgery room, Just like the security post doesn't have cells.

Defib? yes it needs one
Sink? most likely will add one

**Comment by SpadesNeil** [comment]
No surgery room. Defib and sink, yes.

**Comment by SeigaSeiga** [comment]
The suggestion of a surgery room in particular came up because surgery is the actual alternative to chemistry. If you ever bring up that 'chemistry is the only way to treat X malady', a developer is going to cite the surgery that fixes it as something you can do. There has also been a movement to incentivise the use of non-chemical treatments as more of a 'default' to allow for chemists to be chemists and doctors to be doctors, instead of doctors thinking they **have** to be chemists.

That treatment centre might as well not exist if people don't either take the very deliberate effort to stock it with chemicals [which you struggle with due to the lack of storage, transport and crafting options. oh and btw if you're stocking one medbay you better make sure you're stocking the other so this essentially doubles the workload], or enable it to be able to do surgery. All you can really do there currently is scan someone, find out that they need to be at the upper floor medbay to be fixed, and then take them there, so nobody's even bothering even though it's the closest thing.

Security and Medical is apples and oranges. Prisoners aren't dying on the way to the cells all the way up the elevator. Usually.

**Comment by SpadesNeil** [comment]
Seiga makes a good point I think.

**Comment by AeroWing** [comment]
I'd honestly prefer a chem fridge down there that has its stock synced with the main medbay's fridge like we had before with the original version of this map with chem on deck II instead of deck III. The distance could be written off as 'a series of tubes' if you wanted to. Alternatively just have a fridge and some practical way to stock it. Most doctors can stock up their belts with a standard loadout that should be more than enough to tend to most cases down there except for surgery level issues like broken legs, etc.

That said sink is very much needed along with a defib unit or two. Also for whatever reason the oxygen first aid kit is in maintenance next to surface medbay instead of in medbay. Can we get that fixed?
