### ISSUE TITLE
Xenobiology is very difficult with very minimal if no reward [suggestion]

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#1862]
#### Brief description of the issue
xenobio as done by polaris is random and unclear and unfun

#### What you expected to happen
to have fun  breeding slimes and using their extracts for great stuff

#### What actually happened
i was bored and confused and one my favorite things to do was gone
 
#### Anything else you may wish to add:
bay and whatever xenobios are like bay would be great to be added in instead of polaris' xenobio

**Comment by SpadesNeil** [comment]
Can you elaborate?

**Comment by kcin2001** [comment]
what do you wish for me to elaborate on?

**Comment by Epitaxis** [comment]
Probably all of it. Expand on your explanation through your personal experiences, give examples and give more specific ideas on what you wanted out of xenobiology that was contrary to your experience, as well as what actually went on in game.

**Comment by kcin2001** [comment]
i loved bay xenobiology because i could come in and start working and immediately know what i was doing with the slimes and how i would get what i want, with this its unclear what my mutations are doing and if they are effecting the slimes any or if at all, and with bay you could get things like mobs, food, batteries, phoron, etc from the slimes. with Polaris you can get chemicals which arent very fun unless you are making bombs or are otherwise chemically inclined

**Comment by Natje0** [comment]
I have to agree with this. Xenobiology here is broken, (Several machines seem to do nothing, be unoperable, or I just don't know how), there's next to no indication as to what mutations do, you have to manually inject them with a syringe with nutrition unless you want to wait ages for them to go for a monkey, the slimes are often impervious to the xenostun weapons (I've nearly died because of this before.) and there's only like three or so chemicals that it can provide that's actually useful. Such as Carpotoxin, and the things you can make using it.

I'd much rather have something more clear and simple, such as Paradise's xenobio(which might be the same as TG and Polaris', IDK) where mutations are clear, straightforward, and provides fun and useful effects. Such as Silver Slime's food/drink creation, Metal slime's plasteel/metalsheets, Yellow slime's low capacity, but regenerating power cell thing, and the Pink slime's docility potions.
Obviously, some modifications will be needed, (Such as removing/modifying the blueprint slime thing from one of them) but, I think it'd be a good replacement that most if not everyone will prefer over the current we've got.
(I'd also love it if Xenobio got more to do. Example: Give the monsters in the woods organs that you can extract with surgery, give them effects, and make them implantable in people for fun effects~ After all... Xenobiology is quite a broad term, and slime ranching doesn't quite do it justice.)
