### ISSUE TITLE
Emergency cooling loop for atmospherics

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#1918]
#### Brief description of the issue
Fires have a habit of clogging the waste loop in atmo and being impossible to deal with as the coolers are too slow, so Scree has ICly done a little building.

#### What's been changed
Firstly, an extra section of pipe (with valve) has been added. This is because previously, any incoming waste gases from the scrubbers would have to go through the filters before they get routed to the network downstairs, possibly clogging the system with hot CO2. This is a major problem because even if engineers wanted to open the existing valve downstairs and dump the waste line to outside, it'd still have to go through the scrubbers. Hence, a bypass.
![image](https://user-images.githubusercontent.com/14942479/28746904-690160ce-748b-11e7-8572-c4a0b8d6bfed.png)

The more major addition is just for people who want to cool the waste line off a bit without outright dumping to outside. In short, it's two pumps and a long pipe. There's a valve in there to stop it recirculating after being passed through the radiator, but that can possibly be skipped.

The APC is there pretty much so the gas meter has power (and the light so you can see it). If we wanted to be really fancy we could use the tunnel as an external airlock for atmos peeps, but that's an expansion for another day.

![image](https://user-images.githubusercontent.com/14942479/28746922-d5dbe70a-748b-11e7-81bf-1219b8cf0a14.png)

#### Code Revision
Server revision: release - 
861edd2c42e78d3b8327d42c2067fe5346a563b1

**Comment by HawkerTheGreat** [comment]
I agree with re-modeling the system, but I think the current ATMOS setup is still a bit messy, You have a good idea, but the reason cooling doesn't work too well is because the current loop is as simple as it can get and can often cause problems with having air too hot - or - even air too cold in some cases, making it into the mixes... too hot or cold.

I would provide some ideas, but I've not given the atmospherics system on tether an in depth analysis, - there is problems though... like the issue Scree is presenting. I feel like there might be a better system to doing this - heating or cooling the air before it has the chance to enter these tanks and screw up the mixtures.

And Besides ATMOS might do good with a slight bit more room, possibly an airlock and outdoor cooling.

**Comment by Screemonster** [comment]
Cooling the stuff that's made it into the mix in this setup is as simple a matter as dumping the tanks into waste and sending them through the cooling loop.
Now, if the air mix is too _cold_ from taking more in from outside / the algae generators, then that can probably be dealt with by connecting a gas heater to the air mix tanks.

**Comment by Screemonster** [comment]
Atmo has been remapped since this issue was created and these fixes/suggestions are no longer applicable.
