### ISSUE TITLE
Defibrilators don't work beyond 200 damage.

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#1921]
#### Brief description of the issue
If patient has over 200 damage, defibrilators don't do anything at all. (Not counting oxygen damage)

#### What you expected to happen
Save lives.

#### What actually happened
Got frustrated and really annoyed at the unneeded nerf.

#### Steps to reproduce
- (Step 1) Use defib on patient with over 200 damage
- (Step 2) The combat defibrillator buzzes, "Resuscitation failed - Severe tissue damage makes recovery of patient impossible via defibrillator. Further attempts futile."
- (Step 3) Get gruesomely dissapointed.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 861edd2c42e78d3b8327d42c2067fe5346a563b1

**Comment by JemliRoivas** [comment]
This was put in for pretty much that exact reason.  Once the body's too damaged, no amount of defibrillation should be able to save it.  What you can do is try to patch up the body down below the 200 limit, and then attempt defibrillation, doing it with non-chem methods since a body can't metabolize the chems.

**Comment by SpadesNeil** [comment]
Yea that isn't a bug.
