### ISSUE TITLE
Departure shuttle teleports directly to CentCom

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1982]
#### Brief description of the issue
On the tin.

#### What you expected to happen
For the shuttle to go to the transit area when the departure countdown hits zero.

#### What actually happened
Teleports directly to CentCom

#### Steps to reproduce
- Vote to end the shift
- Wait

#### Code Revision
- Server revision: release - 65f327472204df85b8f1da241685c8ac31e01e62

**Comment by Verkister** [comment]
Pasting my recent discord observation here since I have no idea whether it was ever getting looked at.

Anyway basically i think this thing https://github.com/VOREStation/VOREStation/commit/18012fa1d16d61af16c7968c5d0c935e022411ed gutted out a file (shuttle_controller.dm) just a couple days before this thing https://github.com/VOREStation/VOREStation/commit/aa8723b724bf2afaa6af2bb46aff115e4e3b6ef7 moved a reliance from shuttle_controller_vr.dm towards the forementioned gutted file, with the phrase "using standard shuttle_controller.dm again" sort of sounding like a return to an earlier system, which impliedly sounds like it'd be referring to an earlier point of time before the other commit just couple days earlier?

Not sure if this actually would fix the thing or how relevant it is, but it is the closest thing I could find for a cause of the bug.

**Comment by SpadesNeil** [comment]
I just woke up so I'm reading this like

https://www.youtube.com/watch?v=KufiqCh3Qd4

but I what you're saying makes sense and I'm open to trying things if you wanna take a crack at it.

**Comment by Verkister** [comment]
https://github.com/VOREStation/VOREStation/pull/2055
