### ISSUE TITLE
Synthetics Can't use the succumb emote/command.

### ISSUE THREAD

**Issue by Xindii** [VOREStation/VOREStation#2044]
#### Brief description of the issue
Using a full body prosthetic akula character, I attempted to use the *succumb command to die when in hard crit.

#### What you expected to happen
I expected my character to die after entering the command.

#### What actually happened
I got the text saying 'You have given up on life and succumbed to death' text or whatever it is, but nothing else changed. I was still very much alive and stuck in hard crit.

#### Steps to reproduce
- (Step 1) Play as a full body prosthetic/synth.
- (Step 2) Go into hard crit, or the threshold where the succumb command is enabled
- (Step 3) Type 'succumb' in the text bar.
- (Step 4) Sick back and complain when the game says you died, but are still stuck in a perpetual near-death coma.

#### Code Revision
4230069a59f5e135eb1b8a5ece0d8509c01cefd4

**Comment by aztectornado** [comment]
This is due to the fact that Succumb works by adding a crapload of Suffocation damage. Obviously, since machines don't breathe, and for that matter, don't take Suffocation from hard crit, this will not work. 

I think this could be fixed by doing a check to see if the player is synth or not, then instead of suff, doing burn damage as their body short circuits itself to "death"

**Comment by Cameron653** [comment]
I'm assuming this is a polaris bug. Succumb could probably be  improved by making it set the stat to dead.
