### ISSUE TITLE
Tajaran Engineering void suit not visible

### ISSUE THREAD

**Issue by Poojawa** [VOREStation/VOREStation#230]
#### Brief description of the issue
Refitted human -> Tajaran hardsuit doesn't have a sprite, but still makes shoes hidden.
#### What you expected to happen
Swanky hardsuit sprites
#### What actually happened
Helmet on, suit invisible
#### Steps to reproduce
Convert hardsuit to Tajaran, equip onto person
#### Additional info:
https://gyazo.com/840736ce852d53d7c3b56455781fade5

 - **Server Revision**: release - 2016-05-23
3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Poojawa** [comment]
Happens to Atmosia as well. ANother user reported Akula was the same way.

**Comment by SpadesNeil** [comment]
@Cameron653 can you look into this?

**Comment by Cameron653** [comment]
I'll see about fixing this sometime today.

**Comment by Cameron653** [comment]
Found the bug after a bit of testing. item_state should be "rig-engineering" not "eng_voidsuit"
When I changed the variable to "rig-engineering" it worked, as seen below
https://i.gyazo.com/f6c5b7159277b98fd17183e1d0fde144.mp4

Going to code in a fix real quick.

**Comment by Leshana** [comment]
Hi, actually the item_state should be eng_hardsuit.  The item_state is used for when you are holding the suit in your left or right hand.    The true root cause of the missing sprite bug is different tho, its the very fact that the item_state is being used in update_icons is the bug.  I have fixed this with some changes in void_vr.dm,  I'll show in a second.
