### ISSUE TITLE
Whitelist missing for Rapidvalj (Vox)

### ISSUE THREAD

**Issue by Rapidvalj** [VOREStation/VOREStation#2369]
#### Brief description of the issue
My whitelist for the ckey Rapidvalj and the species Vox was accepted about 3 weeks ago, but the whitelist ingame hasn't been showing up.

#### What you expected to happen
I expected to be able to select vox during character creation.

#### What actually happened
I could not select vox during character creation.

#### Code Revision
 https://github.com/VOREStation/VOREStation/commit/dcddd0d64a82f76e991e166c8d9dc3893690fbe9

#### Anything else you may wish to add:
https://forum.vore-station.net/viewtopic.php?f=46&t=1139

**Comment by SpadesNeil** [comment]
https://forum.vore-station.net/viewtopic.php?f=45&t=277#p7053

Due to the high volume of special character apps at any given time, it's not a duty of admins or devs to add whitelists to the server once accepted. However, you should be able to do that easily yourself because unlike most servers, our whitelists are part of the Github, and the files are not ignored, allowing you to edit them at will.

**Comment by Rapidvalj** [comment]
@SpadesNeil Oh uh, when I asked on the server Scree told me to make an issue here.

**Comment by SpadesNeil** [comment]
He was correct!

**Comment by Rapidvalj** [comment]
@SpadesNeil well I'm not really sure how to actually do it myself.

**Comment by SpadesNeil** [comment]
Eventually a dev will get to it here on Github then. Or you can bug Cameron. Just be advised there is no official ETA.

**Comment by Rapidvalj** [comment]
@SpadesNeil Alright, thanks a ton.
