### ISSUE TITLE
No recharger on floor 6

### ISSUE THREAD

**Issue by lbnesquik** [VOREStation/VOREStation#2569]
#### Brief description of the issue
It's a small complain about rechargers, mostly for synths since borgs can go anywhere. Every floor except floor 5 and floor 6 have public rechargers. While floor 4 has at 4 rechargers with 3 publicly available, floor three has 6 with two public. Hell, even floor 1 has 3 of them on public access. It's just a bother for synths. 

#### What you expected to happen
Nothing

#### What actually happened
Lack of rechargers (surprising, i know.) 

#### Steps to reproduce
Just ghost around

#### Code Revision
-Server revision: master - 2017-12-02
8c376610f857d2df29dee93920f7b255ee9724a0 
 
#### Anything else you may wish to add:
- https://imgur.com/a/Z7bld
Here is how i think you could fix problem relatively easy. Purple is where i'd put the recharger. In the corner like all synths deserve to be. Guests pass moved to the right and atmos alarm moved down. Make it easier to see from the desk too.

**Comment by Arokha** [comment]
There just aren't any public areas ON 5 or 6 though that aren't a department. Like medical and security both have rechargers. Medical's is accessible if you're in medical because it's in the patient recovery area, Security's is accessible if you're in security cause it's in the bathroom.

But there's not really anywhere to actually PUT one because all the space is eaten by departments for the most part.

**Comment by SpadesNeil** [comment]
I'll see what I can do about this anyway.
