### ISSUE TITLE
Autolathes don't let you access the material storage

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2603]
#### Brief description of the issue
For some reason, once your put stacks of metal or glass into an autolathe, you can't take them back out as there's no 'material storage' anywhere to remove stacks of materials like in all the other machines such as the exosuit fabricator, protolathe, or circuit imprinter.

#### What you expected to happen
If I accidentally added glass or metal to an autolathe, I'd be able to get it back out.

#### What actually happened
It's in there for good.

#### Steps to reproduce
- Add glass or metal to an autolathe.
- Cry once you really need that glass or metal and it's stuck in there for the rest of the shift.

#### Code Revision
- release - 
d2194a759af92a64e9392232841f351bf15d409f

**Comment by Treasa729** [comment]
It's been a while since I last used one but last I checked you actually can dispense the sheets, they're just treated as normal items in the autolathe. They're just called glass sheets and metal (or maybe steel) sheets in the list of items. This might have changed though, as I said it's been a while.

**Comment by Screemonster** [comment]
![image](https://user-images.githubusercontent.com/14942479/34294329-ec134694-e6ff-11e7-811c-def7261fd857.png)
