### ISSUE TITLE
Feature: Allow pred to give mob control to prey

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#2638]
It's 8am and I've been up in a fantastic RP with someone for far too long, let's go before sleep depreivation catches up with me. 

The suggestion is to allow preds pass control of their mob to a prey within their stomach. I feel that this would add a layer of depth to things such as absorption RP, as well as opening up possibilities for living clothing via Promethean and the like. I feel like the framework for it is there (The body swapper, cortical borer, etc), it would just be an issue of finding an elegant way to do it.

**Comment by Arokha** [comment]
I do like the idea (though I think it should probably be from a soulcatcher rather than 'just anyone in you' as that seems arbitrary). There are a couple problems with this that have to be fixed, that came up while I was talking about this last night with Zalvine. I think 'giving control' will have to be using some novel system rather than just swapping minds like the body swapper does (should be more like borer does).

Swapping minds has some problems (and these need to be fixed with the mind swapping thing too):
Most notably is how NIFs, backup implants, and end-round persistence interact with it. Like if you swap into a body without a NIF while you had one, and they have a backup implant, it's going to take a backup of you and mark you as not having had one and you'll lose yours. Conversely if you didn't have one and they did, you now have a free NIF for no reason. End-round persistence will completely ignore you if you're in the wrong body for saving limbs/markings/etc, and your vore-organs will get all screwed up.

**Comment by Mewchild** [comment]
It sounds to me that a lot of the issues involving persistence are bugs that need to be addressed anyway, especially given how easy it is to find a body swapper on server. Want me to make new issues about them?

**Comment by Arokha** [comment]
They aren't really bugs is the thing. That's just how it has to be. It's completely impractical to do it any other way, or requires like... a strong AI to be written to figure out what your 'intent' was.

Like if you're in another body, what should it do? Save all your stuff from the previous body you were in? Or your original body? What if your original body is gone? Or if someone's removed the NIF manually? Should that be saved to your thing, even though you weren't in that body? etc

As it is, for now, this is impractical. May revisit it in the future.
