### ISSUE TITLE
AI/Cyborgs unintelligible within soulcatcher

### ISSUE THREAD

**Issue by AbbieFland** [VOREStation/VOREStation#2648]
#### Brief description of the issue
When inside a soulcatcher you can hear the host's headset, as intended. Most of what you hear works normally. But AI, cyborgs, and station announcements instead display partially garbled as "A synthetic voice says blah blah blah" as though they are speaking a language you don't understand.

At first I thought it was one joker speaking in an unknown language over the radio, but then there was a solargrub alert that came through equally garbled but still triggered the audio alert.

#### What you expected to happen
Normally-understandable synthetic voices over the radio remain understandable within a soulcatcher

#### What actually happened
All synthetic voices over the radio sound like an unknown language

#### Steps to reproduce
- Get placed in a soulcatcher
- Listen to radio until the AI or a cyborg speaks or a station announcement occurs
- Fail to understand

#### Code Revision
- Unknown, observed 22 December 2017
 
#### Anything else you may wish to add:
- It's easy to miss if you're not specifically looking for it

**Comment by Arokha** [comment]
I've noticed this but I have zeeeero idea what causes it. Potentially something about languages?

**Comment by PrismaticGynoid** [comment]
This sounds very similar to the issue with communicator mobs a while back. Silicon mobs don't have a default language set, so unless they specifically set one during the round, they're not actually speaking GalCom as a language (GalCom didn't used to be a language in the same way as the rest, and it was never set to be default on silicons when that was changed). Mobs without the proper say_understands set up to handle that, then, can't understand them. 

Since it looks like your soulcatchers use a living/carbon/brain mob inside of them, and those are set up to only be able to understand language-less speech while inside an MMI, it makes sense that they wouldn't be able to understand silicons. (https://github.com/VOREStation/VOREStation/blob/master/code/modules/mob/living/carbon/brain/brain.dm see lines 25-50 for details)

**Comment by Arokha** [comment]
Fixed, and fixed even harder shortly.
