### ISSUE TITLE
Something fucky with vent pipes and open space catwalks.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#2738]
#### Brief description of the issue
Vent and scrubber pipes located on open space catwalks are messed up. Not sure if they function or not.

#### What you expected to happen
The pipes to behave like they used to.

#### What actually happened
![kuva](https://user-images.githubusercontent.com/13697337/34905437-1d7d3f92-f861-11e7-8aa9-b59b97595326.png)
(same above trash pit)

#### Steps to reproduce
- (Step 1) Walk over to a location of open space catwalks with pipes.
- (Step 2) Hurt your OCD.

#### Code Revision
- 47001e607a3531cbe1018e11ee2ae974f4f00879
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by SpadesNeil** [comment]
@Arokha I have no idea what I am looking at.

**Comment by Very-Soft** [comment]
Oh I'm glad I peeked at this, I was just writing up a pull about it myself as well.

**Comment by Cyantime** [comment]
It should be mentioned that this currently disconnects the upper and lower sections of the tether's atmospherics networks at roundstart.

**Comment by Arokha** [comment]
It's because there's no floor there. Catwalks are not a floor, they are an object, and the spot there is actually openspace turf. So the pipes disconnect themselves because they are like "AAAA I'M NOT ON A FLOOR" and try to fall in openspace... then land on the catwalk which they were already in the same turf as.

@Cyantime couuuuld fix this easily with putting plating under that spot (or just running the pipes somewhere else if that's ugly and blocks the view).

**Comment by Cyantime** [comment]
Pre-mapped pipes should be considered already attached when initialized, you can have pipes that have already been constructed and remove the floor under them just fine. Anchored objects are perfectly fine with hanging in open space, look at the lighting fixtures in the stairwells.

**Comment by Verkister** [comment]
They seem to be doing it on lattices as well at the little spot behind upper first level elevator shaft disconnecting the whole upper tether.

**Comment by SpadesNeil** [comment]
Hotfixed by https://github.com/VOREStation/VOREStation/pull/3051
