### ISSUE TITLE
Husk mutation/status is a pain to remove

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#2740]
#### Brief description of the issue
There are situations where people get husked, and even if everything else is fixed, they end up walking around perfectly fine looking like the inside of a packet of streaky bacon frazzles, with no in-character means of fixing their appearance.

#### What you expected to happen
Plastic surgery or something iunno, or some means of restoring a (living) body to no-longer-husk status.

#### What actually happened
[8:47 PM] Isaac (ktccd): does anyone here know how to fix a synthetics face if they've been burned badly?
[8:48 PM] Isaac (ktccd): like, they look like a charred corpse, but are otherwise completely healthy after repairs
[8:48 PM] Isaac (ktccd): so there's no damage left :S
[8:53 PM] Bluehaus: That's the husk effect, it can't be fixed ingame
[8:53 PM] Bluehaus: It isn't a problem for non-synths, because it keeps you from being revived by defibs

#### Code Revision
- don't have it, this was reported over discord.
 
#### Anything else you may wish to add:
- This was recently fixed in the xenochimera revive. Adminhealing doesn't remove it, but admins can easily just remove it from the mutations list when reviving.
- Mainly a problem for synths, as organics that take enough damage to get husked are gonna need resleeving (husk used to stop old clonescans working too, hence the need to debrain changeling victims and implant their brains into an unmonkey before clonescanning, not sure if this applies to resleeving)

**Comment by Screemonster** [comment]
Fixing it is just a case of calling "mutations.Remove(HUSK)" on the person.

Searching through the repo, the only things I can find in the current code on a quick skim that are affected by it are defibs (it makes defibbing fail), appearance (it returns "unknown" as your name and makes you look gross) and a few changeling abilities.

The effect is caused, barring ling/borer shenanigans, under the following conditions:
( ((getMaxHealth() - total_burn) < config.health_threshold_dead) && stat == DEAD)

**Comment by Arokha** [comment]
```
/datum/reagent/ryetalyn/affect_blood(var/mob/living/carbon/M, var/alien, var/removed)
	var/needs_update = M.mutations.len > 0

	M.mutations = list()
	M.disabilities = 0
	M.sdisabilities = 0

	// Might need to update appearance for hulk etc.
	if(needs_update && ishuman(M))
		var/mob/living/carbon/human/H = M
		H.update_mutations()
```

Ryetalin removes all mutations (it simply sets the list to an empty list) and forces them to update. In this case, it would not have worked due to them being a synth, but synths don't even need resleeving to get a new body, it's like a 2-step surgery and I'm unsure how else you'd fix "burned beyond recognition" on a robot body rather than just popping their brain into a new one.

If, on organics, there was no way to fix it then I'd say it's an issue because then the only choice is resleeving and some characters are afraid of resleeving. But, like I said, it's fixable on organics and synths don't need resleeving to get a new body, so I'd consider this fine in both cases.
