### ISSUE TITLE
Flying drains hunger too quickly

### ISSUE THREAD

**Issue by aztectornado** [VOREStation/VOREStation#2761]
#### Brief description of the issue
The flying trait seems to drain hunger at an absurd rate, so fast even chugging protein shake can't regen your hunger, and moreover so fast that you'll be grounded in around a minute air time, far, far too short to have even a short scene in the air, let alone a full one.

#### What you expected to happen
I'd fly around the atrium, chilling out as much as a caged bird can, maybe swooping down and snatching up a micro to toy with after a bit. 

#### What actually happened
I lasted around 50 seconds before falling and nearly breaking my hollow bones. 

#### Steps to reproduce
- Fly
- Crash land after less than a minute or so
- Look like an idiot ICly

#### Code Revision
- 1c41215a8241619a11dfc5d9c36ebc75a3936042
 
#### Anything else you may wish to add:
- Rest in peace being a harpy

**Comment by Arokha** [comment]
Flying isn't intended to allow you to have a whole scene in the air, I don't think.

**Comment by aztectornado** [comment]
Well, what purpose would it serve then? 

There's nothing I can think that it'd be used for since wings don't work in space (So it's not a free jetpack) and there's nothing worth seeing outside tether in upper levels. It's expensive trait-wise and offers no tangible benefits in actual gameplay, less now that you can't even stay airborne in the one or two places it can be used. 

for a trait on an RP server, you'd think that it'd be for RP like that.

**Comment by HzDonut** [comment]
It _is_ pretty upsetting how bad the flying trait is. I mean that in that it has way too many problems and very few fun things. For example:

1. It drains your hunger like CRAZY to the point where you need to keep chugging shakes or you're taking a tumble.
2. There's no places to really use the flight ability, to be honest, except for the atrium where you're completely trapped anyways.
3. Related to the atrium, if you fly into a railing you flip over it and get hurt if i remember correctly. Of all things you should be able to fly over a _railing_.
4. You have to keep the _perfect_ weight or else you'll be unable to fly, which makes problem 1 even bigger of a problem.
5. That 'perfect weight' is pretty darn low so good luck not accidentally shooting past it.

Most winged characters I see nowadays don't even fly ever outside of a few seconds for laughs, it's really sad to see because the flight ability could be _so fun_ if it wasn't so flawed.

**Comment by Arokha** [comment]
> Well, what purpose would it serve then?

Don't ask me. If I was asked when it was being added, I'd have said not to.

**Comment by Arokha** [comment]
https://github.com/VOREStation/VOREStation/issues/2597 Duplicate
