### ISSUE TITLE
Respirocytes overpressurize surrounding atmos

### ISSUE THREAD

**Issue by Squi-RL** [VOREStation/VOREStation#2810]
#### Brief description of the issue
the Respirocytes NIFsoft causes you to emit large amounts of CO2 and Oxygen.

#### What you expected to happen
to no longer need to breathe as long as it's on.

#### What actually happened
no longer needed to breathe, BUT caused a massive spike in CO2 and oxygen, enough to double the pressure in the warehouse within seconds.

#### Steps to reproduce
- Install Respirocytes
- Turn on Respirocytes
- Watch the air pressure spike like a cat spotting a cucumber

#### Code Revision
- e1a9a611a8259561240bb0fb973331f9a9eb413b
 
#### Anything else you may wish to add:
- grabbed the nifsoft from a miner pack, but I don't see how that'd be an issue... just putting this in just in case...

**Comment by aztectornado** [comment]
This is still an issue, even months later? 

Anyway, it looks like the reason for this is that the NIF program simply _floods_ a creature's breath with oxygen when activated, probably a lot more than they'd ever need, in fact. I think this could be fixed by simply changing the molarity of the breath flood thing to whatever constant it is that a mob's single breath size is. (Can't remember it)

...Though that'd probably just slow the effect down, rather than removing it, but right now iirc the thing adds like 50 moles per breath, when a creature only uses less than one or so, but I can't remember the specifics.

 Ideally we'd have it that whatever they breathe in is changed to an ideal gas mix and pressure before it's processed, so they always only exhale as much as they inhale. (Or more, if there's low pressure) But that sounds like a lot of life() changes that'd be a mess to tangle with.
