### ISSUE TITLE
Quality of Life for miners is terrible

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#2884]
#### Brief description of the issue
Mining is slow and tedious and uninteresting. It's not hard, but it's also too slow to be easy. But giving them fully loaded rigs is imbalanced. There needs to be a proper solution to this, probably changing multiple features in mining to make mining actually fun.

So I want people to discuss ideas.

I have some hotfixes for now but I want a good long term solution for this.

Ideas accepted so far:
- [x] Ripley needs a speed boost.
- [x] Ripley needs a battery drain nerf.
- [x] Ripley needs an ore scanner.
- [x] Mining needs a recharge pad for ripley. (I think this was resolved.)
- [x] Mobs in the mining area. Maybe tameable. Maybe just a threat to safety. Spices things up either way.
- [x] ~~Return of asteroid mining?~~ Underdark!
- [ ] Return of secret rooms.
- [ ] Ripley bumping into airlocks that cycle should make the airlock cycle to open that door. This is a feature on /tg/, I don't know why it doesn't work for us.
- [x] Make the big drills report on the supply channel when they fail, possibly with ID number.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/7f48af2b4bb7ed4bd7a6dc5c363830bfd1e8c280

**Comment by Screemonster** [comment]
I'm going to give ripleys a buff to movement. Step_in delay of 6 is ludicrous and a step_energy_drain of 10 is _fucking_ ludicrous. Probably give them a built-in ore scanner too.

**Comment by KotetsuRedwood** [comment]
Something that was mentioned in the discord was treasure rooms making a comeback. Gives them random loot, and let's be honest, who doesn't like loot.

**Comment by Tasald** [comment]
some kinda loot machine like on other servers? where they turn in ore to get better gear/ toys?

**Comment by Dankman** [comment]
ore satchels that hold more than 50 ores at a time

**Comment by SpadesNeil** [comment]
I'm adding the industrial hardsuits back as a **temporary** fix. Expect it to be removed again in the near future when we have some QoL fixes.

Another issue is the lack of recharge pads for ripleys in the field.

>ore satchels that hold more than 50 ores at a time

We have those. Bring an ore box with you, click on it with a full satchel. Holds infinite ores.

**Comment by Natje0** [comment]
My basic suggestions; Leave the RIG as it was, until the mining area as a whole is made mode fun, and boost Ripley speed by 2x, since at last station it was essentially just that due to no atmosphere making it faster.

**Comment by SpadesNeil** [comment]
>My basic suggestions; Leave the RIG as it was, until the mining area as a whole is made mode fun

Already on it. That is a temporary fix though. You posted just as I posted.

**Comment by KotetsuRedwood** [comment]
>the lack of recharge pads for ripleys in the field.

To be fair, this might not be a huge issue if the ripley has a big enough battery installed in it. 

... I don't play mining much, much less use a ripley, so I might be wrong with how long the charge would last, but...

**Comment by DemgelZalvine** [comment]
Far as the Ripley Mech, I've already detailed this but was blown off.
1. Speed, needs it. Needs it bad.
2. Drill variations. Standard does 3widex1out, uranium could do 1widex3out, diamond could do 3widex2out, you know. Make with the interesting.
3. Grapple (if we ever do astroid-like shit again) it can fire, and drag itself to things (can also be used in say, a drill of 1wide 5out to haul itself up to the wall quickly)
4. +More ideas would be nice, this is just to get the ball rolling for the Ripley longterm

Far as mining itself:
1. They need something like the astroid field returning. An RNG area where there's beasts, loot rooms, adventure that could be handled by 1-3 of them. (maybe a console to set how many miners, alters the rng?)
2. Bouncing off the astroid field, maybe just change the mining map period. Something to explore, loot rooms for better mining gear as they go along. I know we're not other servers, but that's usually the balance to when sci isn't there and whatever you don't get, you can fill in from sci after your haul
3. Maybe an actual reason to go BACK OUT to the mine after the first haul. As it stands, there's no allure to actually step back out and KEEP mining. 
4. Suggestion there: Something like TG's vendor and mining point system. Give them things they can earn for drowning the station in so many materials they don't know what to do with. Things they may not be able to get elsewhere, or maybe super rare loot items up for like 10k points and each diamond is worth like 50 or something.
5. While throwing things at the wall: Tame-able creatures they can go hunt for while mining. A special pet Otie, fennec, or various things. Hell, maybe some stupid pokeball bullshit. Maybe make them imprintable like pAI's, put players into them under master's order. So they could sell say, deathclaws on the side guarenteed to follow someone's command (or fuck and get eaten themselves)
6. So much more. If I keep going I won't end. If you want more, I'll post more.

**Comment by SilencedMP5A5** [comment]
monsters to take out your everlasting anger on. the lack of classic mining mobs to beat the snot out of is my only gripe with mining to be completely honest. the ripley and other stuff was always fine by me.

**Comment by Kersakof** [comment]
I'm mostly accustomed to TG, and their lavaland made a step in the right direction. Just not the powergaming one.

Their plasmacutters shooting down multiple tiles at once is very nice, and gives a reason to advance plasma past 3.

Drill times are fucking abyssmal. The reason people scream over the industrial rig being removed is because the difference in time is massive. I can clear out a vein of ore in a couple seconds with the rig, while as with a normal drill it will take me a minute. The variance in speed should not be this big when science is done is 10 minutes.

And the biggest QoL thing from TG? Auto ore pickup for mining satchels and ore boxes. If you have an ore box, any ore you step over goes to it as if you picked it up, and the satchel does too.

Now I'm not saying Virgo mining should be as fast as TG. Hell, TG's advanced plasmacutter shoots 10 tiles and I'm not sure if that's a direction Virgo really wants to go in. One of the reasons why RIPLEYs are still useful in TG code is because in low pressure environments, they move faster, and the batteries are bigger. Not the same case with Virgo, and that could be an improvement for itself, like Scree suggested. 

And tbh, giving research more things that need mining resources would be a QoL improvement too. Too many times I mine for a good hour and come back to no one being able to use it, or don't care to. I'd ask if you could get things like femtos and bluespace matter bins, etc. but iunno how that'd affect the code since they aren't in anyways.

**Comment by DemgelZalvine** [comment]
^ YES THIS. I forgot about the auto ore pick up. THAT ALONE WOULD BE A MAASSIIIVE YES.

**Comment by ArgobargSoup** [comment]
> To be fair, this might not be a huge issue if the ripley has a big enough battery installed in it.

My first experience properly using a Ripley?  It had a good battery installed.
It took half the charge gettin' it from Robotics out to the minin' area.

I would suggest the return of random ruins myself.  HOWEVER.  If they are added, I would also suggest a second z-level ta mining ta make up for it.  With the current generation, there's been times where there's only been like, 3 tiles with a diamond deposit in them.  And if they got overwritten because random ruin, that'd end up bein', well, nearly no diamonds for Research at all, if my experience with stationary drills and their low returns means anything.

Auto-pickup would be highly useful, and would help counteract one of the other problems with mining, the fact that whatever proc lets the satchel pick up ore/whatever proc that moves ore from the satchel to the ore box _really sucks._

**Comment by SingoDingo** [comment]
A long while ago there was a rogue-lite mining suggestion that I really liked the sound of, and would be something I can see being an improvement on top of many of the suggestions made here. It went something along the lines of:

- Mining would be a multi z-level area, perhaps beginning with an initial area one is sent down to on a mining elevator.
- Somewhere on the initial area is a ladder/makeshift stairs that leads down to a lower z-level, this being the case for the next few z-levels below it as well.
- Each level has an increased ore density and secret spawn chance, but contains gradually more angry mobs.
- Level 1 would be something like the mining area we have now, going all the way down to, say, mining level 5 which would contain things like phoron dragons but in return have more diamonds and perhaps an Indiana Jones temple of some sort with rare loot.

**Comment by WTFIsmyname** [comment]
Okay so I created an account just to commend on this shit, so here's how I see it.
The biggest problem is that mining is fucking boring as shit, and Singo kind of touches on the idea, but instead of a dungeon it should just be alien ruins. It suits the theme of the map and what we have established are features of the moon. It's unlikely that a species inhabited this thing, left behind relics, but didn't live inside anything that was a permanent structure.
I don't think ore should be inside these ruins, I think they should be almost an exclusively garunteed phyiscal reward for the miners. Ores aren't rewards for miners, it's more work, why would they actively work harder to get ore. It has to have like, large anomalies, abandoned crates, alien drills, something that they can use to make them feel like they are being rewarded for their effort. The biggest thing for me is the risk/reward for miners needs to be equal. If you're asking them to go up against Phoron Dragons, you best be rewarding them with alien rifles or some sort of cool advanced alien drill that's even faster than a diamond drill, or a translocator or something. It needs to be something they can get that no-one else can get without that same amount of effort.

**Comment by Very-Soft** [comment]
It'd be nice if we had the mining features from paradise (which come from /tg/ I think?)

Basically, rather than using the ATROCIOUSLY SLOW BELTS, have an Ore Redemption Machine, which you drop all the ore behind, it scoops it all up, automatically turns it into desirable things, and allows you to claim mining points to your ID. You can then use those points on a special mining vendor, which has a bunch of goodies, from better mining tools, to toys, and medkits.

Being able to get at least SOME upgrades to mining without relying on other departments is fun. 

Also, some monsters to fight would be nice. I'd again suggest looking at the monsters present on Paradise. There's 3 kinds, and each give something desirable.

**Comment by ktccd** [comment]
Honestly, when I mine, some days I just like doing regular hard work and hauling in tons and tons of phoron.
The only problem with it, assuming I've got good gear, is that it takes forever even with top-gear to do. And at the end of it.... we have 4k points in cargo and noooooothing to show for it.
Nobody needs that much. Nobody can use it. We're supposed to do it, shipping it off is the lore-reason we work on it, but it feels *Really* pointless.

**Comment by ktccd** [comment]
Also, yes, Very-Soft has a point. Make redeeming ores easier. Setting the smelter to specific things is....
Well... there's like, one thing that needs setting: Do you want plasteel for science or platinum to sell?
All the rest? Look at wiki and memorise. It never changes.
Oh, you were a newbie and didn't know? LOL, half your stuff is now slag. Enjoy learning curve.

**Comment by SingoDingo** [comment]
If there are to be monsters in the mining area, it was one reason I liked the leveled mining concept, because it gave those involved a sort of opt-in. You don't have to deal with monsters if you don't want, the first floor would always be monster free with a decent amount of materials on it, one simply had the option to dig deeper if they enjoyed danger with their reward.

**Comment by Very-Soft** [comment]
One thing that would be cool is if the meteor event for the surface had a significant chance of dropping some rock somewhere, with valuable resources, and maybe some strange, neat loot in the center.

**Comment by Very-Soft** [comment]
Also, while the Ripley has been buffed, it would be cool if with science's help, and some advanced materials, the ripley could be upgraded. It's a big strong mech. I'd honestly PREFER if it was the best tool for clearing the mining area once you put some upgrades on it.


What if it could get a phoron power generator, so it can passively gain power as long as it's outside, maybe not as much as it uses by moving and drilling.

Maybe some advanced actuators, uses more power, moves mech faster

Maybe more kinds of mining tools/better mining tools, which are expensive?

Heavy plating, slows ripley down, but makes it more durable, for mining in especially dangerous environments.

etc etc

**Comment by Screemonster** [comment]
I'm sure the phoron power generator is already a thing. I know there's a nuclear one that takes uranium.

**Comment by Cyantime** [comment]
There's a plasma generator that runs off solid plasma sheets, I think they wanted something like a solar panel that runs off ambient plasma gas.

**Comment by Screemonster** [comment]
... a miniature combustion engine that uses the ripley's onboard air-tank and atmospheric phoron to generate power? Could be interesting.

**Comment by SpadesNeil** [comment]
Considering the atmosphere outside of the station, that would be both plausible and practical.

So long as it doesn't explode.

In exchange for a higher drain on oxygen, it produces power if in a phoron atmosphere.

**Comment by Kersakof** [comment]
Condensing my requests to what people want:
Auto ore pickup for mining bag and if you have an ore box, put it directly into that.

Mining satchel of holding so you can have more if you don't want to do the first one.

**Comment by Screemonster** [comment]
Mining drills reporting over supply is a thing now. Ticking that box.

**Comment by InterroLouis** [comment]
I'd like to see a couple of things put in that I'll list now. First off, the ore scanner. It takes...five seconds to scan a spot as is, and you've got to scan a lot generally to find good spots. Cutting that down by maybe half would be great incentive for miners to actually use those big stationary drills. 
Adding to that, not as necessary but I'd like to see an increase in the chance of finding abandoned crates. Not necessarily by a lot even, or maybe just an alteration in how they're found. Right now it calls a number from 1 to 500 and if you get 1 you get a crate. I'm not sure which would run better but I was thinking either the 500 could be reduced, or another few numbers could be added to the ones that would get you a crate if they pop up.

**Comment by Mewchild** [comment]
Pssst give updates

**Comment by KasparoVy** [comment]
Asteroid mining did actually return and there are quite a few POIs. Space-parallax was merged and makes mining in space utterly beautiful too

This is p much 100% resolved aside from RIPLEYs interacting iwth doors AFAIK
