### ISSUE TITLE
Prometheans are weak to water

### ISSUE THREAD

**Issue by aztectornado** [VOREStation/VOREStation#3136]
#### Brief description of the issue
Recently a change was made to Prometheans such that they'd take toxins damage from water, for no discernible reason other than "Lol slimes are weak to it for some reason"

#### What you expected to happen
I could still propose sexy shower times or pool fun to slime gals. 

#### What actually happened
They take a stupidly minor amount of toxins damage from drinking or touching water; so minor it's barely actually a weakness so much as it is an annoyance, and a deterrent to RPing in those situations despite the fact I know a lot of people are probably into it. In addition, this made protein shakes poisonous to them. This all makes little sense in the lore overall (don't get me started on slimes), but this is especially true coupled with the fact that not all our promethean players are actually xeno-bio prometheans; we have slime girls, tentacled monsters, mimics, and so many other things on station at the regular this does not feel like a sane thing to add to _all_ of them.

#### Steps to reproduce
- Play with or as prommie
- drink water or go to a shower
- sigh as your scene is constantly interrupted by "Your body stings slightly" messages

#### Code Revision
- 22568ffdf997493f46ae28b3f572e793e53a3899 
 
#### Anything else you may wish to add:
- Remember that watery amoeba boss from Legend of Zelda? Yeah just-... Any of the games, really. Always a water boss. Slimes are water aligned from a cultural sense. I still don't get why we've kept this as their weakness for so long.

**Comment by Screemonster** [comment]
It's a less-shitposty version, but pretty much echoes my sentiment. Restricting eating on the eating server, and the only other times people are likely to run into water on this RP server is things like showers, the pool, the beach, places where people want to actually... roleplay scenes. Where else? Honestly, I... can't think of any that come up on anything _close_ to a regular basis. And I'm opposed on general principle to putting in mechanical changes to impede scenes for no reasons other than "just 'cause".

**Comment by Screemonster** [comment]
And taking comments from development:

[11:11 AM] Saffron: i mean
[11:11 AM] Saffron: so proms are poisoned by water now right
[11:12 AM] Saffron: i must've missed that memo
[11:12 AM] Saffron: because i'm not sure what that adds
[11:12 AM] Saffron: is that making the game more fun for anyone?

And re: #3135 being a non-serious way of raising this issue:
[11:17 AM] Chargae has too many characters: It's about as serious as the nerf should be taken

**Comment by Benemuel** [comment]
I will add that this also makes their OTHER weakness, being set on fire, impossible to deal with EXCEPT stop dropping and rolling. The standard fire extinguisher will just kill them now, meaning that this is just another thing that Prometheans are WEAK too. And at one point, when they regenerated super fast, I could see the reason for this, but since THAT got nerfed a while back this basically just adds more damage sources to people who already have to be extra careful to a degree.

**Comment by aztectornado** [comment]
Fire extinguishers and chemistry spills are the only other sources of water in the current code... 

But wait, I interject into myself for effect, aren't fire extinguishers used to put out people on fire? And isn't people on fire currently broken in such a silly way because of the very people who made this nerf, such that if you aren't put out within 10 seconds or so of ignition, you DIE? And aren't they already weak to burns, presumably because they're watery and evaporate easy? 

And then while typing Benemuel managed to say basically what I was saying here

**Comment by Very-Soft** [comment]
I think there being a species that is weak to water is a really neat idea.

I don't know what the thinking behind it being Prometheans is though. Like, I think it's a neat idea kind of, but I can't think of any good reason for it being like that really. :I

**Comment by Draycu** [comment]
I would agree that this recent change was not implemented.  I also need to say it should not do toxin damage to Prometheans, but burn damage instead, as it burns slimes in Xenobiology when you use a fire extinguisher.  

Overall, I am a bit torn.  I can see how and why a person who became a promethean by using the slime extract would also gain the weakness to water.  

That said, I feel it should be an optional weakness, particularly if someone is related to the blue slime, or the one which is notoriously immune to the water weakness.

**Comment by Cameron653** [comment]
Made a PR to keep the weakness to water (They don't heal when drenched in water. Their goop can't push thew water away to reform. Or somethiung. I dunno.) but removes the damage from water.

**Comment by HzDonut** [comment]
Slime aren't weak to it for 'lol no reason', that's one of their 'canon' weaknesses on other servers. We just didn't have it here for some reason. Honestly with how tanky prometheans are, combined with the fact they can't actually get toxins damage normally, this change is perfectly fine and I don't get the hubbub. If you want to have a scene in some water as a promethean, that's your poor logistical choice to make, just roleplay out how your character is getting around their weakness, it's what the bloody server is all about: RP.

Anyways it's not just 'some stupid nerf out of nowhere', it's giving them a way to recieve toxins damage. Just suck it up and deal with the fact you can't have your water-based scenes anymore without pain messages, and if you REALLY want to get in some water to shag someone else:
1. Take dylovene
2. Take tramadol

Boom, no pain messages and that dylo should counteract the minor toxins you're taking. Easy fix.

**Comment by Dankman** [comment]
hzdonut that is literally the dumbest fucking thing i've ever read.

"If you want to have a scene in some water as a promethean that's your poor logistical choice to make, just roleplay out how your character is getting around their weakness, **it's what the bloody server is all about: RP.**"

"Just suck it up and **deal with the fact you can't have your water-based scenes anymore** without pain messages, and if you REALLY want to get in some water to shag someone else:"



THE SERVER IS ABOUT ROLEPLAY, SO FUCK YOUR ROLEPLAY LMAO DEAL WITH IT.

**Comment by HzDonut** [comment]
Wow, amazing responses as always folks. Yet people still are confused as to why I'm taking a break from the server.

1. I don't care about immersion. If the feature is removed who cares, I was clarifying the fact that it wasn't just 'randomly added' like people said. Way to focus on one thing and not the full picture per usual.

2. The problem is so minor that it won't affect water scenes at all if you want to do them, like I said. If you don't want the oh so annoying pain messages: dylovene and tramadol. Otherwise you can do the scene just fine.

3. The main point of the post wasn't even 'ree my immersions', the point was that it was a way for prometheans to take toxins damage since they normally can't. The pointing out of the fact that the toxins damage is minor and ignorable for scenes was just showing that it's not even that big of a deal.

4. I only mentioned other servers to show it's not some crazy new concept, I know they don't matter here. 

So once again, actually read the full message instead of focusing in on one thing and throwing a tantrum. So sorry for not agreeing with everybody else and pointing out the fact that the problem is near insignificant and barely even worth so much discussion and drama.

**Comment by SpadesNeil** [comment]
The amount of hostility in this discussion is asinine.

**Comment by Dankman** [comment]
if they're gonna need a way to take toxic damage at least have it be something that makes sense

radiation comes to mind, ingesting toxic reagents as well. that said, at a point in the past, due to the old equity of toxins and plasma, toxins used to at some point in the past, actually heal prometheans during early implementations of the species, and it was never really changed after that was changed.

that said, the only real sources of toxins damage that come to mind, to other crew, are poisonous attacks, radiation dissipation, and sepsis

prometheans don't get sepsis, so that's out

do they not gain toxins from being irradiated? if not that should be patched unless there's a lore reason for it

and can they be poisoned?

**Comment by SpadesNeil** [comment]
Did you guys can't discuss this like grown-ups without resorting to insults I'm just going to start blocking all of you off of GitHub.

**Comment by HzDonut** [comment]
Prometheans don't take radiation damage at all, they just glow. I _think_ the 'lore reason' is that prometheans completely lack DNA and so "radiation wouldn't affect them because they wouldn't be able to take genetic damage," or something like that.

**Comment by KonBear** [comment]
I'm still stuck on the idea of why there is not a white list on prometheans (not all slimes mind you) for our server. They seem to check all the same boxes that Dionas, Vox, and Xenochimera have. The polaris lore has been what a lot of players have been following for prometheans as that seems to be the only uniformed public lore out there, (as far as I know) so my question is are we gonna end up adopting that lore or not?
