### ISSUE TITLE
Broken disposal pipe

### ISSUE THREAD

**Issue by Tasald** [VOREStation/VOREStation#3374]
#### Brief description of the issue

Pipe near mining is getting clogged with trash that's been sent down. Might be others as well, unsure.
#### What you expected to happen

To have blockage free pipes
#### What actually happened
https://gyazo.com/d49cb48f9a24b7733a490454a4744123

#### Steps to reproduce
N/A?
#### Code Revision
0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8 
 
#### Anything else you may wish to add:
![broken pipe](https://user-images.githubusercontent.com/15081050/38162760-194658e2-349c-11e8-8538-ca78a8040a97.png)

**Comment by Mewchild** [comment]
Will fix when I’m home today

**Comment by Mewchild** [comment]
The pipe itself is fine, it seems.
The issue was, I believe, caused by an untagged destination in the sorting/mailing system. When an item enters a disposals network, it's packaged into what I understand to be a virtual container called Disposals Holder. This container will move [2048 tiles](https://github.com/VOREStation/VOREStation/blob/031874bc6b5681d2c3c055d858381dcd2b52ed3d/code/modules/recycling/disposal.dm#L498) before becoming inactive/stuck, to mitigate the lag from infinite disposals loops. The issue being that when [two holders meet, they combine](https://github.com/VOREStation/VOREStation/blob/031874bc6b5681d2c3c055d858381dcd2b52ed3d/code/modules/recycling/disposal.dm#L600). If an item has become stuck in the pipe due to travelling too long, it then becomes a blockage, stopping any further items in the pipe in their tracks, the moment they hit the pipe containing the inactive object. A coding fix would be to, I feel, make it so an active object dislodges an inactive object when they meet (Throw a brick down the pipe to smash loose the blockage), but I'm not sure how heavy that would be in regards to controller usage... and it may also render the infinite loop safety useless. In either case, I'm testing now, to see properly tagging [the junction](https://i.imgur.com/3ctDCXf.png) has fixed the issue.

**Comment by Mewchild** [comment]
Testing checked out. Items tagged to "trash" now no longer go on the smelliest coaster ride, forever.

**Comment by ArgobargSoup** [comment]
@Mewchild 
> A coding fix would be to, I feel, make it so an active object dislodges an inactive object when they meet (Throw a brick down the pipe to smash loose the blockage), but I'm not sure how heavy that would be in regards to controller usage... and it may also render the infinite loop safety useless.
I think I've had cases where that's actually worked.  I've had one or two occurrences where I sent items to Chemistry via the disposal mail system... the package was the only thing I put into the system, but Chemistry got bombarded with trash as well.

A similar case was when I jumped into the disposal system as a maintenance drone... there was nothing in the disposal I jumped into, but I suffered damage upon exiting due to being bombarded by trash that exited with me.

**Comment by Mewchild** [comment]
A more innocuous example of this is exactly that. Because everything entering the network is packaged into the same disposals holder, it all goes the same location. It's why sometimes trash pops out along with your package, if you have cargo mail you something. I'm curious if the game would throw an error, truthfully, if you sent two or three small items through disposals in the same holder, all tagged with different locations.
