### ISSUE TITLE
Map scanner on security/medical consoles mapping issue.

### ISSUE THREAD

**Issue by swat43** [VOREStation/VOREStation#347]
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Arokha** [comment]
Whenever map changes happen, to update these you gotta run the "Generate NanoUI Map" verb ingame. Do it on a test server since it makes the server freeze for 60 seconds. It drops a new map png into your byond cache. You then plonk this into the html or nano folder somewhere to overwrite the old one and make a PR for that changed png.

**Comment by Arokha** [comment]
It's pretty current now. Though for any map change it'd have to be updated.
