### ISSUE TITLE
Department Funds impossible to access

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3541]
#### Brief description of the issue
When attempting use a account ID and Pin to enter a department account, it instead puts you into your personal account. In addition, it's possible to access your account without needing an ID card

#### What you expected to happen
Enter department account number and pin correctly, be able to access funds from account.

#### What actually happened
Be pushed into my character's personal funds, and need to have an ID imprinted with the account number to have proper access. If your personal account's security level is elevated, the process fails entirely.

#### Steps to reproduce
- Join as command role
- Use Notes verb to view account ID and PIN
- Enter into ATM

#### Code Revision
7be6c1a479cb498e22d6a00104ae8b8fa43add79

**Comment by Heroman3003** [comment]
Turns out its not a bug, but a weird interaction. In order to access any sort of account, you need to have ANY ID in. If account is set to not require ID, then any ID will do, otherwise it has to  be owner's one, but if you do not insert ID and just input numbers, then you will be auto-logged into yours (because if it has no ID, it ignores the input info and just tries to log via ID-only login of your worn ID).
