### ISSUE TITLE
Perhaps Warden/HoS should get access to the Red Armory again.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#3675]
#### Brief description of the issue
No access to the red armory unless its a code red.

#### What you expected to happen
To be able to freely use the red armory, even if it ain't an emergency. (Sometimes, I wanna shoot guns in the firing range on slow shifts, alright?)

#### What actually happened
Access Denied!

#### Steps to reproduce
- Join as HoS or Warden
-Go to red armory
-Become depressed as you cannot get to those delicious lethal weapons.

#### Code Revision
849c1374a1b064b9c9a1fb8c1c43ed19a4259100 
 
#### Anything else you may wish to add:
Armory could also do with an expansion! Attempting to put back flashers or barriers if you used them results in you having to smash a window to get them perfectly aligned! (Or crowbar, screwdriver, crowbar the window.)
![blockade](https://user-images.githubusercontent.com/33539568/39954936-58eb7546-560b-11e8-8b44-3cabed1f2166.JPG)

**Comment by Leshana** [comment]
Functioning as designed.

**Comment by Arokha** [comment]
I mean we discussed this as admins and decided we'd compromise on this setup. :v Are you going rogue

**Comment by SpadesNeil** [comment]
If it were up to me, Security would have lethals all the time.

Well, it technically is up to me, I just don't want a coup.

**Comment by MrSign** [comment]
My opinion has shifted to allowing for at least ONE person in security to access it, preferably Head of Security. Just to allow for some spice in low pop rounds where all you wanna do is mess around with guns and stuff. And considering action events have been rather low/non-existance might as well have SOME fun by shooting at cardboard cutouts.

**Comment by SpadesNeil** [comment]
HoS should be given access.

**Comment by Arokha** [comment]
Leshana suggested maybe we just make it a key card auth thing so you have to convince at least one other person but don't need code red

**Comment by SpadesNeil** [comment]
I disagree with that because we never had a problem with the HoS distributing lethals willy nilly in the first place. It was the Warden who was being a pain in the ass about it. The only person who would logically need to access those lethals would be the Warden, and so instead of it being a matter of getting the Warden and HoS's approval, the Warden and HoS may decide at the start of the shift "hey let's move all the guns to regular armory just in case shit goes down", which will have the counter-productive effect of actually _encouraging_ them to take guns out of the red armory. The HoS commands the Warden, so the Warden could simply be ordered to help, which makes the point of them helping to control another auth pad completely pointless and redundant.

We used to have a system, long before you arrived or we changed maps, where the heavy tactical gear was just kept in a second armory with HoS-only access, and the HoS could open shutters during an emergency. The shutters part is not needed because we now have the alert levels that unlock the armory, but the HoS should still have access to the red armory all the time.

**Comment by Arokha** [comment]
Resh: "I think we have better HoSes now"
Ace: "I think the HoSes+wardens might just powergame it"
👀 

>[entire first paragraph quote]

Strawman, since that's not why the whole armory was redone or this was done in the first place. It was all redone because they had crazy equipment they never should have had in the armory in the first place, and would grab superheavy armor/gear to respond to any threat, regardless of severity (because why not use the best stuff). The second part of the paragraph about them moving things out of the armory even though it's obviously intended to be locked until code red is powergaming and should be treated as such. If you let people who think that's okay stick around or continue thinking that's okay, they do other shitty things too. Uncorrected rulebreaking because you think it's inspired by how the map or code is set up is still uncorrected rulebreaking.

>[entire second paragraph quote]

I don't necessarily think you're wrong here, and I'm not super-opposed to giving the HoS the ability to go in there, but I fail to see how this fixes your first statement at all, if the warden and HoS decide at the start of the shift to loot it and put it elsewhere, *how is this solution supposed to change that*? It seems like it would make it worse, if anything, by making it even easier for the HoS to just hand all the stuff over to the warden.

**Comment by SpadesNeil** [comment]
I think my statement was misunderstood. I meant to say that in either scenario there is the potential for powergaming, but my point was that in one version we have to bag _two_ people for powergaming when one of them might have just been following orders, while in the other scenario, the one that I want where the HoS alone is needed to enter the red armory, only the HoS is to blame.

We'll just punish the HoS who abuses the privilege. I think it's better for the rest of the HoS players who _don't_ abuse it to have the potential to access the armory, and I do not want it to require a two-step authorization just to get in.

**Comment by Screemonster** [comment]
The excessive gear is definitely a thing that lead to events getting powercrept just to keep up, which effectively locked non-sec players out of doing anything apart from holing up in a closet.

**Comment by MrSign** [comment]
The least we can do is provide access back to the Head of Security. The amount of equipment in there allows for a full department to combat any threat in the immediate vicinity. (And considering 'action' events have been non-existent for the past few weeks/months at least give them a chance to play with the guns in the firing range if they so wish!)

**Comment by SpadesNeil** [comment]
We'll do a quick admin vote on it, because the admins are ultimately the ones who would have to deal with potential powergaming. I'll abstain from the vote because I haven't been around enough due to work for me to justify having a fair say in the matter.

**Comment by Tasald** [comment]
I Like the idea of needing the key card to get in, the vault could do with one as well, however, what cards would work to get in? warden/HoS/Other head?

**Comment by Tasald** [comment]
I don't think it should need code red to get into the armory, especially for people that like to inventory >.>. I also don't think HoS/CD should be able to just 'walk into' that area when ever they want. It should be at least a little inconvenient to get in besides just opening a door. So, If it's just a vote for 'bog standard I can open this door' then I think I'm gona have to go with no. Mostly because I don't think lethal armories should be that easy for 'anyone' to get in. I do Like the Keycard idea, maybe need the warden/another head to let them into the doors, one it forces cooperation, two it lets other heads / other sec know what's going on, instead of being a silent HoS and wordlessly putting in or removing gear for 'any reason' out side of code red.

**Comment by SpadesNeil** [comment]
This is becoming a very complicated discussion so it may be a while before I have any final say on this. In the mean time we won't change anything until we're confident in something to implement.

For now, if you want to access the red armory, pester the shit out of CentCom. They can open the door remotely (admin powers).
