### ISSUE TITLE
Most random events are boring and uninteresting

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3677]
#### Brief description of the issue
Random events to mean something. There is only a few you can't ignore and not affect anything important. Only grubs would cuase any kind of station threat.

#### What you expected to happen
People to have to care if an random event happens. Rare ones should be, oh shit kind. While common ones should just be on a passive look out, but should spial out of control if people decided to lwed for 4 hours instead of working. Have a rouge space carp to worry about. Or damaged parts of the station to fix. 

#### What actually happened
Falling space rock less dangerous than Kenzie sitting down. Doesn't even smash a window. Same problem with space debries, but that give no rocks to go looking for to get bragging rights. Unkown life forms of mice and lizards get ignored, so do electircal issues. It's common for rouge venders to get ignored too. If engineering decided to get as much power out the engine as possible, grubs can be a non-issue too. fungus goes unfound because it's never a problem and boreing to look for. Viro being bolt open only gets fixed if engineering is bored because no one plays viro, and there's never any viruses. Oh and SPAM SPAM SPAM LOVELY pda SPAM. 

#### Steps to reproduce
- (Step 1)notice random event
- (Step 2) or don't. Rarely adds to game play or RP in anyway

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 849c1374a1b064b9c9a1fb8c1c43ed19a4259100 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
I want random events to encourgae people to do their jobs. Breaking the station gives engineering give them work, small school of carp give medical rescourse, and also give sec something to shoot at. Kept at a low level poses minimal threats to people. (Other than turnips) The old metor system that hit the station is less dangerous due to the tehsi barrier and bar stair case. It should be rare for a random event to kill everyone (maybe only after a string of player mistakes) but common enougth, and engageing enouth to keep people on their toes. Not just distract from emotes. Since we don't have antags random and admin events are the only thing pushing non-ERP RP

**Comment by Ketrai** [comment]
The thing is. this server is mostly about well, roleplaying? People would rather not have their scenes constantly interrupted. If you wanted to, you could even ignore grubs. they're not a big deal. invasive events like spiders, which can even end up near the dorms, maybe even inside of them, are a pain. no one wants to deal with them. We do have spess carp.

**Comment by SpadesNeil** [comment]
There's a fine line to walk between events being disruptive and not actually fun to participate in. I for one want to have some rare events like asteroids actually cause more substantial damage.

Keep in mind, Ketrai, all events are coded to avoid dorms. That includes Spiders. Or, it's supposed to.

**Comment by Very-Soft** [comment]
To put in my 2 cents:

Engineering has a disproportionately large amount of focus in the random events, because it's the easiest department to think of things for. 

I think it'd be neat for one of the electronics shorting out events to make a random door somewhere shocked indefinitely. But I also recognize that most of the random events are already engineering focused, so I'll avoid suggesting any for them.

The problem is, that most of the other departments events don't have as much room to randomly happen. It makes sense for lights to short out, kind of. Or for some space dust to break a window.

Security is arguably the easiest to think of ideas for, in that for the most part, security wants to go fight the bad.

-Monster infestation - similar to existing mob infestations? But only targets maint rooms, and spawns 1-4 sort of lesser monsters. Scatter a few mimics, dinos, frogs, oties, giant rats, or other things around in some random section of maint. This way they are out of the way, and there is an air of danger to wandering the maint tunnels. This should ideally though, be rather rare, and not take place every shift.

Medical is a little harder, but I think with the above, that will give medical a bit more work at a similar frequency to security, which is a good thing. I think though that we could take an idea from an existing event though.

-Foreign contagion - Have a random [something] around the station spawn, which has one of those spiffy viruses, or some other effect, such as steadily increasing toxins. It might also be neat to have a parasite effect, which slowly deals oxy damage to those infected, and requires surgery to remove. You could put the parasite inside of any part of the body, or all of them if it's left untreated for long enough. Again, should be rare, not every round.

The harder ones are for cargo, service, and most specifically science, because those jobs in large part only really have a job when someone asks them to do a thing as far as mechanics are concerned. That said, Cargo and Service's events are simple enough, and we already have them.

-Central Command supply orders - The main problem with these orders in the past was that they seem to just randomly ask for random things, and often as not, those things would be simply unobtainable with a reasonable amount of effort, and they gave you nothing for completing them. I think that tweaking what is asked for, to be things that Cargo could realistically obtain, perhaps with a little help from another department, would be ideal. 4 Phoron canisters, as an example. Two deathclaw corpses. Ten meat pizzas and twenty long island ice teas, etc etc etc. And if these things are loaded on, give them a load of points to make it worth their time. This kind of thing could easily happen every shift, just make sure the list isn't ridiculous, so they don't just get the same thing every shift. 

Science is the hardest here, because for the most part, random events don't really mesh well with the activities they can partake in. More damaged crew will give robotics more work. And the supply orders could offer science some activities in obtaining things for cargo. But I've been relatively stumped for random science events. I can think of a few ideas for them, but it would sort of mean adding in whole new concepts to the department, which are likely difficult to code.

-I like the idea of a portal randomly appearing, which may or may not have harmful things to wander through it. Science could study this portal, and build the tools needed to close, or stabilize it as needed. But I mean, that's mostly just gateway missions with an alternate entrance tbh. 

I would really like there to be more event things for science to do mechanics wise, but that's kind of a whole discussion on its own, because like. Space vines results in a plant that science can study. Xenomorphs can be roleplay studied after they are dead (Or during if you're brave enough). But these things don't have science participating in the actual RESOLVING of the issues. They're always the ones to come in after, never the solution, or often the CAUSE of problems everyone else is having. And that's lame. There should be a kind of random event that science alone has the tools to resolve.

**Comment by Ketrai** [comment]
To be honest, with what soft says. Might as well add an event where random animals end up in cargo? Not hostiles ones, but ones science or some other department is gently nudged to take care of. Can't have all that wildlife just running around can we? Clearly the shipment wasn't meant to end up here, but alas.

**Comment by Ketrai** [comment]
ALSO, I was thinking about adding more exotic dishes. Top-of-the-line foods. Make it something for the kitchen to goof around with, something exciting when rare ingredients pop up? Maybe even have special effects. And randomized recipes? Not the kind of effects that are. "Omfg, i can oos this to powahgam, am gohn to shove mah face at kitchen ebery tihme i get defclaw meat!" But something decent. Can even be something minor as a 1 time 5 maxhp buff or something. That can only apply once per person if it hasn't already. 

We could even make it part of an event, make rare ingredients grow outside? Blocked in by some indestructible pallisade, with a door that asks for a certain food. Maybe even have it ask for an exotic food, and have it spawn ingredients in randomized locations over the station, and the outside. (Within reason, don't just spawn it in a corner of the mining area.) And if that is too annoying, have it give riddles. or a little puzzle to solve, so you get a good hint where a certain ingredient is. These can easily vary in difficulty too.

**Comment by Ketrai** [comment]
For the bartenders we could have something similar? Exotic drink reagents. can just combine the two events if you wanted to. Or heck, even something as weird as having a certain blue rock spawn in the mining area randomly at the start of the shift. If this elusive blue rock is found. (It wouldn't appear on scanners, only mesons.) Then a bartender can use their cocktail mixer to collect a randomized amount of a randomized exotic reagant. Heck, even make different coloured rocks if you so want to, just make sure the reagent is randomized so people won't go. "OH, it's the red  rock, beh, I don't like that drink." but. "Ohmagerd, I hope it's the exotic potato juice, it's my favourite." People like having special things. And you could set up really exotic diplomatic dinners with these for events.

**Comment by Ketrai** [comment]
For security? Instead of just fighting things, maybe capture something that is designed to run away first? and fight back when cornered? Something you have to try and capture/net. Of course this means you need a little help from science, but it's more interesting than just fighting. And since it fights back, we can put it in the announcement that it's better for security rather than science to go out and capture, or vice versa. It really depends which department you think deserves an event dedicated to them the most...

**Comment by Ketrai** [comment]
I'm willing to try and code at least one of these, but honestly I'm probably better making second grade sprites, and second grade code. xD

**Comment by LiquidFirefly** [comment]
Alright, but why would I want to clean up after a random event flooding the bar, or worse, get my subtle footjob under the bar table get interrupted by a phoron flood thats *entirely random and out of my control.*

**Comment by LiquidFirefly** [comment]
"I want my RP characters mechanically fixing a problem and dropping what they're doing to deal with things that pop up, not roleplaying or scening."

**Comment by Very-Soft** [comment]
Random events can be fun to deal with, especially if you're bored and no one's biting for rp. And we ARE playing a videogame. If you want to make sure your scenes don't get interrupted by something, then play off duty or visitor, and go to the dorms. 

Having more kinds of random events would mean there's less of just engineering getting all the random events. I personally do LIKE the engineering events, but with how many there are, and how few there are for others, it means that if you go engineer, pretty much every random event that happens centers around your department fixxing it. And this happens multiple times per shift.

It'd be nice if there were more events that focused around other departments, so there's more to actually do in each, for those that actually like to deal with ss13ish problems.

**Comment by Entosine** [comment]
Okay, but if I wanted to deal with ss13ish problems why would I be here and not literally any other server.

**Comment by LiquidFirefly** [comment]
Alright but why would I be here if I wanted to deal with SS13 problems.  There are a million better servers for that that aren't RP centric, and won't find something like *solargrubs* to be some kind of out of the way nuisance.   This is an RP server, what do any of these events add to RP except pointless busywork on a random clock?

**Comment by Very-Soft** [comment]
The events provide work for people to do, which can translate to RP before, during, or after whatever the threat is if people are willing.

Like, sec briefing and gearing up to go get a threat, teaming up, communicating and searching around, or bragging after the fact is RP.

Medical empathizing with and caring for the sick, or being total assholes and booting people out of the door as soon as they are finished, is RP.

Cargo techs going around putting in orders with different departments for supplies that they need, and the subsequent interactions that result, apart from the mechanical handing over of the goods, is all RP.

All of this can be roleplayed if people want to. Is it likely to? More often than not, people will probably just run and deal with it, or ignore it as they already do with most of the existing events. 

And, we ARE still playing SS13. I can understand that you might not like the game, but others do. What you seem to be suggesting is more, removing all the random events unless they're entirely optional. So, running that to its natural conclusion:

Why don't we have the engine pre-set? It is a mandatory thing that needs to be done every shift, No one ever RPs setting it, and it can go wrong, which could ruin someone's round! :C

Why don't we also make it so that RnD is always maxxed out, since that's another thing that's entirely mechanical, and never RPed. 

Cargo should also probably automatically accept orders, and mail them to the appropriate places.

Further, Medical should probably start with cryo set, the chemfridge stocked, and automatic implanting and resleeving machines. 

Wouldn't want all these people to have their BJ RP to be interrupted by that job they signed up for.

**Comment by LiquidFirefly** [comment]
"I have to do the job that I signed up for" and "I have to go suddenly deal with additional work that was tacked onto my job, probably in the middle of something"  are two entirely different things, you don't seem to understand that, or just seem to be ignoring that point for some reason.   I enjoy SS13, but I don't enjoy dealing with it's problems when I'm in the middle of a long form RP, which believe it or not, is what a very large portion of people are here for.

**Comment by AbbieFland** [comment]
# CentCom message:

A toilet has stopped up at East Bar Maintenance. Janitorial staff is requested.

**Comment by Very-Soft** [comment]
I think having some work to do that isn't directly the result of someone else fucking up is ideal.

Security has grubs to deal with sometimes if people don't just outright kill them on their own.

That means that OTHER THAN ADMIN EVENTS, sec ONLY has people being annoying to deal with.

Medical's work is ENTIRELY, implanting, resleeving, and fixxing other people's mistakes.

Having work OTHER than that extremely limited scope, would be desirable to me.

**Comment by LiquidFirefly** [comment]
I don't see the issue here.   I even think that grubs are much because of how often they can gum up the works by sitting in the AI chamber.  Like, this is a perma-extended round server.  If you want carp bashing windows out during your RP, or foreign contagions, or whatever else, there's a million other fun RP servers to go to, most of them you'll have to give up your snowflake cards, but who cares really.  Aurora is a decent example.  I like SS13, and I like the problems it presents when I'm playing the game for those problems and for RPing around those problems, and other people.   The issue is that I'm here because I can also ERP, which is long, hates interruptions, and doesn't mesh with random, mechanical elements.
