### ISSUE TITLE
Cryo consoles can be accessed by anyone

### ISSUE THREAD

**Issue by Screemonster** [VOREStation/VOREStation#381]
#### Brief description of the issue

I've had multiple reports from players of being able to retrieve restricted items after someone decides to cryo with all their gear instead of putting it back.
#### What you expected to happen

For the cryo item storage/retrieval console to only be accessible by heads of staff.
#### What actually happened

Assistants running around with eguns and sec gear as all they have to do is wait for someone to cryo and just go nab it.
#### Steps to reproduce

Cryo with a bunch of gear on your person.
Have someone else access the cryo console.
#### Additional info:

Server Revision: Server revision: release - 2016-06-15

**Comment by SpadesNeil** [comment]
https://github.com/SpadesNeil/VOREstation/issues/30 Old problem, should be resurrected.

**Comment by Arokha** [comment]
I've not seen anyone abusing this, so either it's fixed or people've decided to stop doing this (maybe because we yelled at them because it's shitty to do and basically powergaming).

Kinda important that sec officers can scrape their own department's gear out anyway. Seems to be working fine as-is.
