### ISSUE TITLE
Energy Gun Crate not available to order via cargo

### ISSUE THREAD

**Issue by Mewchild** [VOREStation/VOREStation#3862]
#### Brief description of the issue
Title. The [energy Gun crate](https://github.com/VOREStation/VOREStation/blob/44380c7c30caf1ab8dea66d5a8a989c9af3671e4/code/datums/supplypacks/munitions.dm#L119) doesn't show up in the cargo list

#### What you expected to happen
To be able to order additional standard weapons for security

#### What actually happened
ADVANCED EGUNS FOR ALL. Ahelp and ask the pack spawned in

#### Steps to reproduce
- Walk to Cargo, check list

#### Code Revision
- release - 
ad18753b9d6bfd50b51846b726f025f1e781a75c 
 
#### Anything else you may wish to add:
- https://i.imgur.com/vYyQk15.png

**Comment by Arokha** [comment]
You linked an old version of that file, it appears to have been changed and removed since then. The egun and officer crates were removed since they are trivial points for doubling the armory's weapons.

If you want you can make a PR to alter that, but I would expect that HoSes will just order it at the start of the shifts again and we'll have to remove it again. If you readd it, make it much more expensive.

**Comment by Mewchild** [comment]
There is currently no way to order more standard energy guns, and no way to produce them via science or other means.

**Comment by SpadesNeil** [comment]
It should probably be readded. A little more expensive, but having no way
to resupply the armory with basic gear at all isn't good.
