### ISSUE TITLE
Absorbed prey can be ejected willy nilly with single ejection

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#4017]
#### Brief description of the issue
While the "release all" button respects the status of absorbed prey, the ejection button in the popup of a single absorbed prey gives no crap about it, spewing the absorbees out as if they weren't 'sorbed at all.

#### What you expected to happen
For the popup ejection button to respect the absorbees like the release all button does.

#### What actually happened
Absorbee gets insta-spewn.

#### Steps to reproduce
- (Step 1) Absorb a prey.
- (Step 2) Click their name in gut to summon the popup.
- (Step 3) Press eject.
- (Step 4) Cheat the system.

#### Code Revision
- ad18753b9d6bfd50b51846b726f025f1e781a75c Actually current master but this works too.
 
#### Anything else you may wish to add:
- I was trying to use the absorption as a part of my experimental fusion mode thing and being able to release the original mobs from there without unabsorbing was catastrophic lmao.

**Comment by Arokha** [comment]
This is intentional. It's assumed that if you want to unabsorb someone directly into the world, this is how you can do it. There's no hard requirement to "unabsorb" prey before releasing them.

The [All] respects it because it'd be too annoying to ask "And absorbed prey?" every time. Basically: It's assumed that if you want to release an absorbed prey, that's fine, and you must know what you're doing if you click an absorbed person and want to release them.
