### ISSUE TITLE
Suggestion: Small shift map.

### ISSUE THREAD

**Issue by Ketrai** [VOREStation/VOREStation#4026]
Would it be neat to have a smaller, more compact map for smaller shifts? First of all it seems silly to me to have an industrially sized station like this filled up with skeleton crew. A security team would make sense when there's no people to book. But just sending a small group of a few people to maintain a full blown station, fire up the engine, and thus cause wear to a plethora of unused facilities. Seems wasteful, even for nanotrasen.

Logic and such aside. I think the huge map is actually actively killing the spiirit of the server. There is little to encourage people to interact with one another in the vast expanse. Everyone is extremely spread out. On top of that, some of the more essential departments are almost isolated due to how far out they are, even illogically so. On top of this we have trash piles everywhere, which have people busy for easily 15 to 45 minutes depending on how thorough people have to be. The elevator splitting two parts of the map makes it tedious to move up and down to seek interaction, so it's easier to stay put and AFK somewhere, hoping for activity to bustle up, or a random passerby to interact with you. It's e asy to say people should be more engagive, and take initiative, but I don't think this is an issue that's just on the players. Map design encourages this kind of behavoir. 

Take medical for example. On many maps medical is a central department. It's easier to treat people if you don't have to take the elevator up and down constantly, but the outpost never gets used due to well... who is going to haul a bag of chems down there? cryo bags, other nonsense?

On other maps people frequently pass by medical. I remember it often being a place where you could stop when you see people tending the desk or the chem lab, and hit up a chat. The only department that regularily passes by medical nowadays is security, if they don't take the stairs to take the elevator. There's the inherent pressure to spend half an hour making chems, and then sit behind the desk to man medical. Other than cargo, no departments really have this pressure to stick in the department, and man the desk, or do other things unless you choose to. It's very much the reason I've seen medical become more of a closed circle than it has ever been. 

All the walking distance also means people have less chance to run into one another. And as i've said, encourages passive play. "Hrm, I could go to cargo to order a box of pizzas, but then I need to go up that elevator again..." Even the public garden, which tends to get used on other maps, is so isolated and far away I don't see it used on skeleton shifts at all. It's sad. On top of this, we have expiditions now. So people can go fuck about off station instead of staying and form a community. You get explorer cliques this way.

I think it's a good time to sit down, and think about what kind of design would actually serve the purpose of the server well. A roleplay server, focused around vore. The experience should be immersive, but not scare away social interaction.

It's currently way too easy to go a whole shift without seeing a soul on skeleton shift. Even fudging maintenance is so huge, that despite 3+ people running off all the piles at the same time, you don't run into one another most of the time.

If we do end up adding an extra map, I guess either by vote, or based on how many players were on the last shift. or even time of day. There's plenty of ss13 maps around. take boxstation for example. Just something small, compact, interactive.

**Comment by Benemuel** [comment]
I.... Honestly agree with this. I liked the idea of the tether, especially at first, but anymore the magic of having such a large station is gone, replaced with well.... The fact that it is huge and takes forever to get anywhere, or around. I often times hit the elevator button and then start watching youtube, because it generally takes a while to get to me. And I generally continue when I am going around on the elevator, since it feels like no one wants to talk while riding it. Combined with the Dorms being so out of the way you never run into someone going their, and alot of the things being on their own levels, so outside of the elevator you never run into anyone, and yeah, finding people IS hard to do now.

And this is to say nothing of how it makes people know their coworkers and thats it, kinda leading to every department kinda not caring about the others, since there is generally no reason to seek out interaction, and you won't run into them alot of the time. Security really shows with this, since the only time most people interact with them, is when they are arresting them, since if they are relaxing in security, there won't be be just walking by since its so out of the way.

**Comment by Very-Soft** [comment]
I'm in general agreement that I'd love for there to be some sort of map rotation. I will say though, that I tend to like how spread out and out of the way some things are. 

For example, I like that the public garden is a cool place, that's way out of the way. It makes it so that you can have a public-ish scene, without a whole lot of worry about people running up and butting I think the tether is actually a pretty good map for having some fun places for vorethings to happen. 

Maints being big and winding is a good thing for preddy types to do their thing. And going trash diving is by no means a requirement. If folk are spending all their time hunting maint for goodies, and that results in them getting less scenes... well to be frank, that's not a map design problem. That's all up to personal priorities. 

I still don't think that the tether is an especially BIG station, but it's complicated enough to FEEL huge.

So on that hand, I tend to agree that the tether is also not the most fun to have to deal with the layout of constantly, especially on slow shifts. 

The main department areas being SO separated from one another does make running around to check and see if people are free and able to be stolen, or otherwise engaged with from any given department rather tedious.

Having a few stations to work with, and shifting between them based on population at the end of the previous round, or on a set schedule, I think would be really neat. 

I've worked up a little bit of a map that I went overboard on trying to make a gateway map, myself, and having played with that, I do think it's entirely possible to make a reasonably functional, if cramped station on just one of the Z levels at the current size we have them. It'd be ideal to have 2 I think, with one of them being for all the main stuff, and then the secondary one being for the extra stuff, and maints to help connect it all together. 

I like the Tether, and I don't want us to just get a new station or whatever, but I think that I'd be really keen on having some variety. 

You could even suggest that additional maps are smaller bases on, or above Virgo 3b, with the crew being able to ship out as needed to here or there, implying that the Tether is still functional, and possibly even manned and in use while the players are on a different base, fulfilling other positions. Call it crew rotation or whatever. 

The long and short of it is, the Tether is nice, I like it, but I do think that some smaller, simpler maps would be nice to have at times.

**Comment by Ketrai** [comment]
Mhm, soft also makes me think of another problem. The fact that there are a lot of quiet places, normally a function of the dorms... well, it encourages OOC prep a little too much. or PDA'ing to set up a scene. I still enjoy being able to run into people for spontaneous action a lil more.

**Comment by SpadesNeil** [comment]
It's not making the map that's complicated.

**Comment by Screemonster** [comment]
Well, having a bar as well as the cafe near the tram _does_ help on highpop shifts, 'cause it's like... sometimes there's someone being loud and annoying in the bar or else it's _too_ crowded to actually set up any kind of scene with someone with the sheer number of people around.

**Comment by Wickedtemp** [comment]
We used to switch maps around every 1.5 years or so before Tether.

And while I think Tether is kinda neat as a concept, and that its *our own map*, I would support a map change entirely, personally. It's large, or at least feels that way, medical and sec are out of the way, the elevator's a bit annoying to deal with, especially during rounds where power loss is frequent because then you're just stuck on one half of the station. 

I'd recommend Polaris' Southern Cross if it wasn't going to be cramped with our population, and if it didn't completely isolate xenobio and others on the planet outpost. 

So either its... making a new map, keeping this one, or going back to Box or Northern Star - which I believe could be tweaked enough for our population to be enjoyable. 

But, yes, I share all of those concerns and more.

**Comment by SpadesNeil** [comment]
>We used to switch maps around every 1.5 years or so before Tether.

You say that like it was a deliberate thing we did.

**Comment by Wickedtemp** [comment]
Deliberate or not, thats what was done and its what a lot of players kinda grew used to.

**Comment by TheDavestDave** [comment]
I'm for a map change. The phoron limits what engineering can do project wise too much

**Comment by TheDavestDave** [comment]
maybe I have been playing too much metro, but if we compress the station to three z levels we could turn another three into maint getting more dangerous as you go down. We could fudge the trash piles to give better things. For example level -1 would be bags and other load out items. Maybe have crime symbols or something.  Level -2 would have insulated gloves and knifes. But spawn things like rats and maybe mimics, hostile mobs you could fend off easily with a crowbar. Level -3 would knifes, guns, and subspace jammers and things but spawn blobs. Also would spawn other redspace creaters when admins wanted to do an event
