### ISSUE TITLE
Belly contamination too recursive.

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#4246]
#### Brief description of the issue
Bellies contaminate _**everything**_, regardless of where it is or how it's stored or how deep it is.

Accessories attached to clothes.
Everything in a box.  (That lightbulb box they were carrying?  Enjoy cleaning over 20 bulbs.)
Alternate modes of power tools, like the drill.  Gotta wash it in both modes.
Encryption keys in headsets.

#### What you expected to happen
Not having to spend 10+ minutes cleaning things up when someone hands me a gurgle-contaminated bag.

#### What actually happened
oh god everything is gross

#### Steps to reproduce
- Gurgle someone with itemweak on.
- Expel items.
- Have to dig down through *everything* to get it all clean.

#### Code Revision
- release - 6831216aa58b34b2d6610f7de92c556b69272fbc 
 
#### Anything else you may wish to add:
- The discussion that brought this up also brought up how, well, the whole "IDs get ruined" thing inconveniences everyone *but* the pred.  If the pred actually wanted to steal an ID, they'd strip it beforehand.
Relevant because this issue is probably caused by an indiscriminate check to make sure an ID was gurgled no matter how deep it was in the player's belongings.
- washing a soggy cardboard box with water to make it usable again

**Comment by Screemonster** [comment]
Making sure IDs get ruined was an executive decision to stop easymode ID-theft via noms.

Making people individually wash every single item in an item including contents of lightbulb boxes, contents of their toolbelt, and god knows what else, is _silly_.

Not to mention that contamination also has other stupid side-effects like people being able to meta when someone's eaten because the PDA server tells them their PDA is "slimy".

**Comment by Very-Soft** [comment]
I generally agree with what's said here, and I'll add, that the outright ruining of IDs regardless of circumstance, is sort of anti-fun. 

I'll just say that, while I understand that the ID ruining was well intended, to prevent preds from just getting access from those they ate, in practice the only people it really regularly inconveniences are the prey. In practice, if a pred wants to steal someone's ID for the access, they'll just pull the ID off of the prey first. Further, if someone's going and abusing someone else's access, that's sort of more of an ahelp issue, rather than something that should outright be prevented. 

Now, I'm not saying that ruined IDs should be removed. Just that, there's certain situations where it makes more or less sense than others. If a pred has itemweak and stripping on, and aren't presently using a harmful digestion mode, then I'd imagine the ID would be fine. And of course, if the ID ends up in a belly that's causing damage, then sure, ruin it! That makes sense, and is much more of a conscious choice.

I'm just saying, with how rarely we have a HoP sitting around waiting to replace IDs, this could do with a bit of a reconsider.

**Comment by Arokha** [comment]
@SpadesNeil requested that it be this way and has stood by this for years, so you'd need to convince him.

**Comment by Screemonster** [comment]
I remember there was talk of making a biometric ID-restoring machine that would allow a ruined ID to be returned to roundstart access if it was used _by_ the owner. That'd be fine, as it'd allow prey to get their card back without a HoP present, while preventing predators from using the card unless they used some other means such as impersonating via resleeving, and frankly if they're going far enough to resleeve themselves into a copy of their victim's body and impersonate them then they've probably earned that access.

Absolutely agree on non-damaging bellymodes not damaging IDs though. If I'm endoing someone and they accidentally drop their PDA inside me I'd rather it not ruin their access.

**Comment by Wickedtemp** [comment]
I can see Ace requesting the broken ID's, and while it'd be better to have a means of restoring them by the owner - potentially an ID slot on the wall in the resleeving lab, since most of the time if your ID's screwed, you got digested and need to be resleeved. 

Otherwise, medbay lobby would kinda make sense, or in front of the HoP's desk. 

But for the 'every single item is now poison' thing, yeah, that undeniably needs to be fixed. It's annoying as hell to have to clean a resleeving patients **everything**. At times, I was honestly tempted to just throw their bag and equipment belt out and tell them nothing was turned in except for their PDA and ID and tell them to get new shit.

**Comment by Shophaune** [comment]
There's also the point that you need an ID to fax.

**Comment by SpadesNeil** [comment]
>There's also the point that you need an ID to fax.

Try using a digested ID in a fax machine. It works perfectly fine.

**Comment by Verkister** [comment]
Got some plans on an idea that would make certain items stop the recursiveness while still leaving the leakier containers vulnerable.
