### ISSUE TITLE
Icon badly sprited

### ISSUE THREAD

**Issue by VoidnessPT** [VOREStation/VOREStation#429]
![1bfdcc09dcf4838be02987615a61ca78](https://cloud.githubusercontent.com/assets/20602986/17068435/dc171148-5048-11e6-85ff-2b4f9f1b6cbf.png) ![59fc64bbd4b1f0d84e1bc7791a90fd3a](https://cloud.githubusercontent.com/assets/20602986/17068493/2c01c702-5049-11e6-966a-17d0e629c713.png)
#### Brief description of the issue

Basically, my character's icon is kind of badly sprited, mostly it being the hands, since they somehow make my character look fat when it isn't supposed to be. The evening gloves that I wear even make it look like some sort of optical illusion.
#### What you expected to happen

For the icon to not look fat, whilst it's just the hand somehow making it look like it. I don't really know how to explain since the admin that helped me just really told me to put up an issue report here and I have no idea how to even explain the thing properly.
#### What actually happened

The hand on my character's icon making my character look fat or have a big belly.
#### Steps to reproduce

Not really any steps. It just shows up when my character is either naked or just with underwear. With clothing, the belly disappears. At least with most clothing, I guess.
#### Additional info:

N/A

**Comment by Arokha** [comment]
I'm going to close thissss. Not because I don't agree, but because eeevery hand/glove sprite in the game has a row of pixels for the "far hand" when the character is facing east or west, and it makes you look fat or have a pixel dick, and though that's dumb, would require respriting every species and hand thing to remove that. Some gloves make it look worse than others, yeah, just because of the coloring and stuff.
