### ISSUE TITLE
Objects in bellies vanish

### ISSUE THREAD

**Issue by Eearslya** [VOREStation/VOREStation#443]
#### Brief description of the issue
Dropping items while resting (also includes logging out) or having items taken from you while inside a belly causes them to vanish forever.

#### What you expected to happen
The item(s) should be able to be ejected along with prey, or not allowed to drop.

#### What actually happened
The item(s) vanish entirely.

#### Steps to reproduce
1. Swallow a prey.
2. Prey `rest`s with items in hand.
3. Item(s) are gone.

**OR**

1. Click-and-drag from prey to pred to open the "take/give items from/to" menu for the prey.
2. Swallow the prey, leaving the previous window open.
3. Attempt to take something from the prey.
4. The pred doesn't get the item, but the item disappears.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-07-26
2ef573b78aa56cbe97ae8a7047fcf5408ab3d6ec 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Screemonster** [comment]
Need to test this. In the old code prior to the polaris port, dropped objects landing in the belly and could be picked up by prey. Happened with the belly-teleporting too.

**Comment by SpadesNeil** [comment]
Is this still an issue?

**Comment by Eearslya** [comment]
The issue as I described it seems to be..fixed? Objects no longer vanish, but they instead appear on the ground beneath the predator instead. Still not *quite* what should be happening...

**Comment by Arokha** [comment]
This is basically how everything else in the game works. Preds and prey have a mystical connection and can swap items from inside to outside with 'give' and stuff so this kinda makes sense. It's a liiiittle harder to make ANY item that a prey drops appear in the belly, since you need the item, as it's falling, to figure out what belly the person who dropped it is in, which may or may not be possible. Depends on if the item knows who dropped it. Alternatively you could try to edit the proc on mobs when they drop items, and the proc when you strip them, and blah blah blah. It'd be a little 'open-ended' that way.

Anyway, if you're satisfied with the current 'to the ground' thing, then...
