### ISSUE TITLE
Abduction events should be triggered by specific conditions, not RNG

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#4535]
#### Brief description of the issue
The things filled with bugs and only a few people find grinding itself fun. Worse still they can't get it when they want it, and it's forced on everyone else wether they like it or not. It was fun the first time, annoying the second time. And honestly I just depsie it to the point I'd rather be blown up and resleved than play it.

There's also the problem of people who do want it piloting and going everywhere but where the rest of the crew wants to go.

Also if no one knows OOCly how to hack a door you're fucked becuase you can't shoot it open. Even pusleing random wires won't work because the bolts start down.

It also pushes that explorers are a combat focused job. Becuase game play wise the whole thing is trying to kill you, and maybe I just wanted to pet fennics or explorer caves.

Turrets aren't fun to fight naked. And it slows down moveing a lot. It's possible to spend the whole shift there fighting turrets if you don't know you need to wait for them to pop out to fight them. But it's much easier to learn if they pop out they're going to shoot you.

Did I mention this is FORCED on people if they want it or not. 

it's "balanced" with high tech gear, turning the place into a loot and shoot campfest game.

#### What you expected to happen
Not have RNGues ruin a trip with. Have it as a selectable location, or replace that with haveing some pilot mini-game and have the event happen if the pilot fucks up at a later time. It being an admin triggering event if the whole team decides to go in 20 mechs or something. 

#### What actually happened
the team is taken out of a round into a grind-fest few people want. And on the odd chance you DID want it fuck you. You don't get to decide to do it

#### Steps to reproduce
- (Step 1) hope RNGues let's you do what you wanted to do. Maybe scene at the beach when you are done or something
- (Step 2) Die 
#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 1fe04192c11e2ad7357512d5a873c44a4ea687d3 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Just because you did it once by yourself in 30mins Scree doesn't mean the rest of us are that robust. It kills most teams that go. And cripples the rest.

Also I know this was added to stop over gearing. But this punishes everyone who over gears or not. I would say it encourges overgearing becuase the less trips you make the less likely you are to go to this hellhole. It also stops a lot of non-experdition staff wanting to go because they say or heard about an abductor event. This results on less people going on a shuttle trip, and us haveing to do non-explorer jobs. Like setting a relay the RD demanded, even thought we didn't want it. 

I really hate that you ether out robust the turrets or die. If you pick too big a fight anywhere else you can run away. It isn't rewarding going through a death maze for the 50th time that you never wanted to do the 2ed time. 

if you want a oh no the pilot can't do his job, the pinic area would be much better for this. Becuase there isn't turrets everywhere. It would be Exploration focussed instead of combat focused. Imagine that. Explorers. Exploring. Instead of shooting phasers non stop singing this: https://www.youtube.com/watch?v=O1CQ7Vwz8Eo

It's FORCED on people if they want it or not. Most people don't want it. Again the few nutjobs who do want it can't get it. Both sides suffer becuase of RNGues decidieing if you do it or not.

You connected them to the space elves empire people. So at somepoint when you want to do some kind of peace talk agian, or have a large number of them on the station for an event.  Or another event like that. You've got a big portion of the station who's been adbducters by them, put in a death maze. Or had to deal with that. Heard that happen to their friends. And it's not going to be fun event haveing tensons that high during that talk.

**Comment by TheDavestDave** [comment]
oh I should git hub devices not chargeing other devices before I forget. But yeah keep the adminbus option. Haveing it a selectable distation lets people not have to have an admin online to trigger it.

**Comment by Very-Soft** [comment]
Making an abduction be a selectable option is a little bit silly from a sanity and lore perspective.

I do like the idea though of abductions only really happening if you do certain things. 

Like, I think that having a comms relay on the shuttle should totally attract attention. And like scree suggested, having alien tech with you on the shuttle also. 

But I think that making it a selectable location is a bit silly.

**Comment by TheDavestDave** [comment]
that's going to be fun
RD: I want a relay on that ship
Pathfidner: Sorry but no, I want to live
RD: we have a possiton open for pathfinder

**Comment by SpadesNeil** [comment]
I want to see the abduction event changed from RNG to specific circumstances as well.

**Comment by Screemonster** [comment]
instead of building comms relay on shuttle where it takes up your precious space, build comms relay at destination where you have an abundance of space. You don't even need to build a SMES, just slap an APC on the wall and jam a cell in it, it'll last you a good long while.

**Comment by Novacat** [comment]
Once one of my existing PRs get merged, I will put up a PR to set abduction change to zero.

Relays are largely built on the shuttle for two reasons. The main reason is that it is rare for people who know how to build relays to go on expeditions, usually an engineer or scientist will set one up and then do something else (Usually they have no interest in going along). The other reason is that the shuttle has unlimited power, and thus, there is no need to set up power or wiring or anything like that.

Ever since I enlarged the shuttle, it is practically very difficult to run out of space. The only time things got cramped was during an event where a couple dozen people + mechs were assaulting an abductor ship.

**Comment by Very-Soft** [comment]
I  know WHY people build the comms relay on the shuttle. It's the simplest way to deal with that situation. There's no downsides to doing it, and as things presently are, most people don't like going out with the shuttle, specifically because there's a chance they'll be tied down for however long the abduction takes.

But I mean, if you tied abduction chance increasing to factors like the presence of a comms relay, I'd be willing to bet people are a lot more willing to bring the parts for a couple solar panels and an apc to set up a relay at the destination as intended.

I am personally of the opinion that putting an autolathe and a comms relay and whatever other machines you might want on the shuttle is a bit powergamey, specifically because those things are meant to be used with and have to deal with power. 

The shuttles only really have unlimited power as I understand it, because that's the easiest way to make sure that all their parts work properly. 

I don't think it's unreasonable to consider, that if you have something on the shuttle that's sending and receiving advanced signals like that, then you might attract the attention of the abduction craft.

**Comment by KasparoVy** [comment]
Niiice.

**Comment by Novacat** [comment]
The long term plan was to make it so that the shuttle had limited power like everything else. Originally Aronai asked me to redo the shuttle into something like the Baystation shuttles, which have their own SMES, APCs, and Atmos, and basically just functions as a portable part of the station that can run out of power like everything else. This would have likely also fixed the ongoing issue with the airlock.

That went out of the window however, as one of Polaris's developers is going to be completely overhauling shuttles. No sense putting a few solid weeks of work into something that is only going to be around for a limited time.

"But I mean, if you tied abduction chance increasing to factors like the presence of a comms relay, I'd be willing to bet people are a lot more willing to bring the parts for a couple solar panels and an apc to set up a relay at the destination as intended."

The main problem with this is how do you _communicate_ to the player that it is the relay that causes abductions? Even if abduction chance was set to zero tomorrow, all of the bad habits that abductions caused are not going to go away overnight because character just will not know what changed ICly. It would have to be paired with some kind of announcement.

The other problem is that it is not going to make people bring parts for solar panels and an APC. Outside of the fact that explorers generally are not trained in engineering, and, people who are trained in engineering usually have no interest in going on expeditions from my experience. What is more likely to happen is that people will just not set up a relay at all, which is usually what happens most shifts there are expeditions.

It is kind of like the Quantum Telepads. They were supposed to be a huge boon to explorers, allowing easy transit to and from expedition areas without concerns of abduction, but they ended up never getting used after the novelty wore off. They needed power and they could not be set up on voidcraft tiles, and the characters who had the engineering knowlege rarely go on expeditions, and the overall verdict is that unless it was a major operation, quantum telepads are more trouble than they are worth.

**Comment by SpadesNeil** [comment]
>It would have to be paired with some kind of announcement.

I could do that easily.

The rest of what you explained, I'm afraid I don't understand what the point is you are trying to make. Seems more like a rant about how explorers don't use these tools even though they would make their jobs easier.

But that's the point of having multiple departments. You can get the job done independently, but can do it better with outside help.

**Comment by Novacat** [comment]
It is a murky grey area. SMES/APC/Solar work is very clearly engineering department duties, but explorers are science department, and having another department's work as a core part of the explorer's job is a bit icky. While it is nice if an explorer knows engineering as well, it should not be a requirement.

Though, the Subspace Radio PR will probably make the whole relay thing moot since, at that point, explorers would have a method of communicating with the Tether by means other than a relay.

**Comment by TheDavestDave** [comment]
I've stopped asking for engineering help becuase when I tried to ask nicely for shuttle improvement I got told rather rudely no. Then once thoose players left I got told very politely no, we wish to live to engineer another day. This is always going to be a problem while exploration is gameplay combat focused. This is a problem on V2 solars because of the hive bots. Sometimes we can get people to go to the beach on virgo 4 however. It make me think that combat is a big turn off for most people.

tbh if I think I can safely take people I'll ask over the radio and let anyone who comes.

**Comment by Wickedtemp** [comment]
Abduction has already ruined more than one 'beach party' and turned it into a depressing round with a bunch of fatalities. It's the sole reason Tempest has never gone off-station via shuttle. Sure, it could be fun going to a beach, but there's literally a small chance shi could be abducted and more or less forced to watch crew members die in front of hir with no reliable means to save anybody or hirself. 

Glad to see it corrected.

**Comment by SpadesNeil** [comment]
Temporary fix with abduction chance made 0 by default.

We can now consider new ideas to make abductions happen. I like the idea of a communications hub on the shuttle triggering the event.

**Comment by Novacat** [comment]
I do feel that the proper solution to the infinite power issue is to just not have the shuttle have infinite power to begin with. One of my planned projects was to overhaul the shuttle to work something similar to Baystation's shuttles, which have an SMES, APCs, and they primarily get their power from a power line to the Tether, with a backup generator and some phoron.

However, it was announced not that long ago that Polaris is doing a complete overhaul on shuttles, so I am waiting to see what Polaris does before touching the shuttle.
