### ISSUE TITLE
HealBelly is kinda bad and doesn't get used as a result

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#4611]
#### Brief description of the issue
One of the main reasons healbelly is never used is because it's just... bad, compared to just about every resource Medical has. It's rather slow, only heals brute/burn, doesn't disinfect or salve, doesn't help at all with toxin, oxy, cloneloss or pain -- though there's a numbing effect that'd circumlemt that easily enough, and after discussing it a bit on discord, I figured it could probably be made to be at least usable.

#### What you expected to happen
A vore mechanic to see use on a vore server.

#### What actually happened
It really just isn't used, due to a combmlemation of:
- **Prefs**
People like different things. When it comes to Medical stuff, a lot of incidents are time-sensitive and it's difficult sometimes to ask everyone if they're okay with it and get a response before their condition worsens to the point the healbelly isn't even useful anymore. This isn't as much of an issue as it used to be, due to the freedom we have in the vore panel, if we have a 'belly' already made and it's all good prefs-wise, then we can just change it to Heal.

- **"It's a bit weird"**
...And, well... That isn't entirely untrue. If someone's in critical condition and you just swallow them -after confirming prefs, it's a bit odd, even if it is to heal them. I think this is just an IC thing, though, and can easily be cleared up. Though, if they're in critical condition, ideally you'd give them something first. At least they'd be healing while they're in transit.

- **Limited Healing Ability**
So, it only heals brute/burn, doesn't proc salve/bandage/disinfect, or heal toxins or oxy, or cloneloss, etc. This means that even if you do have someone with a relatively minor injury that it could totally be used to fix, let's say, 34 burn damage, they could still potentially end up with an infection, you're honestly better off just using a first-aid kit. This also means that you can't, for example, use a heal belly on resleeved patients with genetic damage or on someone who ran into a radiation artifact, or was tackled by a slime. Overall, medical vastly outclasses this in just about every possible way. Even having a basic first-aid kit means you're able to do more than a heal belly is capable of. It's also difficult to monitor the patient's health. I don't think you can use a health analyzer on them, so you'd need to rely on suit sensors to see if their condition is improving enough. 

- **Time**
Usually, if this happens, it's because they're going to do a scene, or the patient is at the least going to spend a fair bit of time in the predator, and sometimes one of the two people, or both, aren't interested in the RP, they just want to heal and finish, if it's due to just not being interested in the characters, because they have something else planned, etc. Not really a problem, not something needing to be fixed, just mentioning because it's a reason. 

#### Suggestion:
So, my suggestion is to essentially to keep brute/burn the same, give the belly-heal a tricord-like speed on toxin/oxy/cloneloss and be able to clear mutations - which is important for resleeved patients, as without an upgraded printer, someone could end up blind, deaf, paralyzed, etc, and the only way to fix this is with ryetalyn. This would make it still...be rather slow. Slower than any reagent Medical would use, but ideally there'd be a bit of an RP scene to go along with this so it doesn't need to be quick anyway. I personally think a 'bandage/salve' effect would be good to add, since it's something you'd find in gauze/ointment in basic aid kits anyway, but it could definitely be a little powergamey and I know for an absolute fact that people would start relying on it in a new meta for Expeditions. 

**Pros**
- Vore mechanic hopefully being used more. 
- A slow but broad healing allows for damage coverage without making any aspect of Medical useless or inferior. All of Medical's reagents would be much faster.
- The ability to heal genetic damage outside of, but at a slower rate than cryo. Want to use a belly instead of a cryocell to heal that 1.2 genetic damage you got from radiation or a slime-handshake? Now you can! Want to fully heal someone after being resleeved? Iunno why you're putting them in an unhealed body but you could totally do that, too, but it's not really a great idea.
- Can act as a sort of minor stabilizer/passive heal should there be numerous patients and only one doctor, allowing them to do more instead of having to simply inject/bandage and leave you on a bed or Sleeper.
- Might lead to Medbay not being called as much over small things. This is neat, depending on your personal taste.
- On the flipside, it might lead to more requests for Medical, because people might be wanting you to use the healbelly to fix them now that it's better. This could also be neat, depending on your personal taste.

**Cons**
- Adding Salve/Bandage effects may also cause the passive healing to start on wounds, which would actually make the healing substantially faster if it's widespread, potentially making it 'too much'. While the intention is only to stop bleeding and make sure an infection doesn't pop up later on, as these can get out of control quickly and ruin your scene when you thought they'd be healed, unless there's a delay, I'm pretty sure an expedition team is going to powergame this hardcore. I'm leaning toward not even including this.
- Doesn't have a painkilling effect. This is because 'numbing' is already an option so it should be fine without one. I'll make sure before making the PR.
- Allows everyone to essentially heal someone at a tricord-level rate. While ideally this would be used for minor issues and for Mlemical/Patients to do scenes a little more, some people could attempt to use it for more serious injuries where they really should just go to medical. Granted, I really don't think this is a big issue as it already heals brute/burn _currently_ and we've had an ability like this for a _long_ time, since before I even started playing here, and I really don't recall having this problem with anyone.
- Outside of suit sensors, can't view vitals of belly occupants, as far as I'm aware. So like... if they aren't stable, they could totally worsen and die, and you wouldn't know until they tell you or do a deathgasp.
- Actual tricord speed may be considered too quick. While any other reagent is around +5x better, it would likely be faster to simply use a healbelly to fix a shocked hand on floor 1 than it'd be to run to the rarely-manned surface medbay or use the elevator to head to floor 7 and go to medbay. But, currently, the brute/burn heal is set to 5, and I haven't run into that probmlem yet, either, so I doubt this is an actual problem.
- Might lead to Medbay not being called so much over small things. This could suck, depending on your personal taste.
- On the flipside, it might lead to more requests for Medical, because people might be wanting you to use the healbelly to fix them now that it's better. This could also really suck, depending on your personal taste.

So... yeah! I think it could be a neat addition, but it should be discussed first before I try to code it, because that takes effort and work for a mlem like me, and it'd kinda suck if I put in that work only to have it be "lol bad, closed"

**Comment by Screemonster** [comment]
Honestly the healing level isn't tooooo bad, but making it able to stabilise patients for transport (ie. hold off oxyloss from crit and so on) would be pretty dank

**Comment by ArgobargSoup** [comment]
For that first con... I was looking up the salve and bandage effects, to see if there could be a "bellysalve/bandage" effect that wouldn't set off the autoheal timer, but that would require messing with more code than I thought.

However... then it occurred to me.  Could possibly half-get those effects... For a "bandage" effect, maybe something that sets bleeding to zero, and for a "salve" effect, maybe something that sets infection chance to zero while they're inside a belly/belly set to heal.  Stops the big things without counting the wound as "treated" and triggering the passive autoheal...

...also I like Scree's idea.  If the healbelly could keep them stable...

**Comment by Wickedtemp** [comment]
I still think adding a slower toxin/oxy heal would be useful. You'd be able to take care of small cases of poisoning relatively easily without having to like... Healbelly, great, burns are fixed, but you have to spit them out to get toxin treated.

**Comment by ArgobargSoup** [comment]
I do like the idea of addin' toxin/oxy heal.  Maybe if it was slower than tricord?  But I've had a case where I got toxloss in a belly due to bugs (was in the belly of someone outside, took off my goggles while inside them, and somewhere between my face and my hand it got phoron contaminated), and I was not only stuck in that belly until they went back inside, but had to deal with "Your body stings." messages from the toxin.

**Comment by Wickedtemp** [comment]
It could totally be made to be slower than tricord, but I wouldn't want it lower than 0.1 damage per tick, because at that speed it'd take a fair bit of time to heal even minor cases.

**Comment by Heroman3003** [comment]
While it is a vore-option, I can see why it is the way it is now. Since its also an 'extremely lazy' option, as you have to do absolutely nothing other than eating a person to get the result. I think just abilities to dysinfect and prevent/immensely slowdown DOT effects on toxins and oxyloss would be enough to make healbelly viable without making it "just use it when too lazy to do good option", since that propositions seems to allow fixing anything except broken bones, maybe.

**Comment by Wickedtemp** [comment]
Broken bones, organ trauma, rising oxy/toxin, radiation, internal bleeding, shrapnel, internal infections, etc, all wouldn't be fixable.

**Comment by Heroman3003** [comment]
I mostly don't like idea of it fixing genetic damage/mutations, since it removes the only things cryo AND upgrading the sleeving machine are actually uniquely needed for.

**Comment by SpadesNeil** [comment]
I remember back when unbirth was the only thing with healing qualities.

We just had a major hull breach and people were dying. Wanker, who was a new user at the time, and still to this day isn't into vore, was in voice chat with us while we were all laughing hysterically at the panic.

But realizing Wanker was dying of oxyloss and decompression, I had to act fast. I dragged him to an airlock. I had a suit on, he didn't.

The door was locked.

Wanker was going into crit.

Wanker is still not into vore.

But I said, "SORRY WANKER, YOU'RE GONNA GET VORED."

"Wait, what?"

"IT'S FOR YOUR OWN GOOD." _**Schlop**_

And vore saved a life that day.

**Comment by Wickedtemp** [comment]
Yeah, like... Even if it was made into an actually viable, solid method of healing, if I remember correctly it *used* to be identical to tricord, and it wasn't broken. I'd have patients sometimes brought into medbay by other people via healbelly and tbh I think thats kinda neat. I'd like to make it closer to that level again, with maybe adding a slow (slower than cryoxadone) cloneloss heal, since that'd give a more fun alternative for xenobio or radiation accidents. 

The last time the SM blew up, Tempest was the only medical and couldnt restock because the upper floor was inacessible. Healbelly being an option then honestly would have made a rather irritating end into a fun one.

**Comment by Very-Soft** [comment]
TO BE ONE HUNDRED PERCENT HONEST

I don't really see any good reason why a heal belly couldn't be used to heal basically everything that doesn't require surgery or more specialized medicine to treat. 

Broken bones? Organ damage? Nah, you need to go to medical for that. 
But making it heal some oxy damage could let you carry people with popped lungs back to medical without them dying at least for a little while. 

Buffing heal bellies makes there be a lot more context for vore scenarios within the medical department. It seems like it could totally result in a lot more opportunities for scenes in general, since you could use it as a means of actually keeping your patient alive and fixxing them while that's working.

I think heal bellies being buffed would make medical requests over minor things less common... but. Medical is already practically avoided by a lot of the player base, because it's one of the most complicated, demanding departments on the server. This would take some of that pressure off of them. 

I also think it would not be terrible if the healbellies cleaned up wounds and stopped bleeding on the external parts at least, and prevented infections from starting. (I kind of don't think that healbellies should just cure infections, just prevent new ones from occurring)

And yes, if healbellies are more competent, then people will abuse them more, but I think as long as they can't fix internal bleeding, broken bones, or regrow limbs, then medical will still have a job to do. They'll just have less to worry about as far as minor stuff goes.

And passed all that, while I'm not 100% sure it works this way, but I'm pretty sure healbellies use up your nutrition while someone's in there with heal on. And if that's not presently the case, that could easily be the limiting factor to make sure you can't just stuff everyone down your fat gob to heal them all endlessly. If you need a constant food supply to keep up healing, then eventually  you're going to need to restock. And I think that's a pretty ideal situation if I'm honest.

I'm totally fine with the idea of medical catering a bit to squishy endo nerds personally. And it's one of those things that no one -has- to do. You're still gonna have plenty of people who don't want to play that way from either end. 

I just honestly think that medical needs something, and that this could be that something. There's lots and lots and LOTS of times where there's no one in the department, we'll put out an alert for medical and no one will come. Meanwhile, put out an alert for anything else at pretty much any time, and watch that roster fill up. I think that this occurs because in large part, medical struggles to be fun, but interferes with ones opportunity to do fun things regularly. 

Offering people who are up for it an option to deal with their minor issues themselves, or medical the ability to deal with it in a fun way, could breathe new life into the department. (I know I'd be more inclined to play in medical if more of the tedious things could be dealt with by eating them.)

**Comment by Very-Soft** [comment]
To also clarify briefly: I think heal bellies healing all the basic damage types would be good. Though I would like healbellies to work at a slower rate than what medical can do. I'd like it if it was an alternative to basic healing, but not necessarily the best option. Just a viable one. I feel like for it to be viable, it would need to clean wounds and prevent new infections from starting.

**Comment by Screemonster** [comment]
Okay now I'm pondering nonselectable bellymodes that _do_ heal all the crazy shit like bones, and only making them available to certain mobs like bluekin.

**Comment by Wickedtemp** [comment]
Pending custom app for Tempest to obtain the uber healbelly.
