### ISSUE TITLE
Suggestion: separation of tracking and health sensors on jumpsuit

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4626]
#### Brief description of the suggestion

At the moment, suit sensors have four modes: Off, tracking alive/dead status, tracking main damage types and tracking main damage types + location.
I think only being able to track location when vitals are also tracked is rather stupid, as it has high chance of giving medical false alarm for scenes. Of course, it rarely happens, but if the health sensor and tracking had separate activation, you could really customize your sensors' status.

#### How you would expect it to work?

Option A: Complete separation)
Now isntead of 'Toggle Suit Sensors', it would be 'Toggle Vitals Sensors' and 'Toggle Tracking Beacon', with vitals having option of Off, Binary and Full, while beacon would just be Off and On.

Option B: New modes to current one)
Add two new sensors modes to existing sensor selection: Binary with Beacon and just Beacon (in case somebody wants to be JUST tracked for some reason?)

I do believe most prey players that don't play dangerous job would find good use for suit mode that only tracks their alive/dead state (as digestion almost immedeately removes corpse once death has occured) with trackers, so if they actually DO die from something else, they can be found.

**Comment by Wickedtemp** [comment]
As someone who exclusively plays as Medical, I think it's pretty much fine as it is. The 'false alarms' aren't really an issue and the most they result in is a PDA message from Tempest asking if they're alright, and most of the time there's no response, but the sensors switch off a few seconds later and it's left at that. I do kinda wish they'd just be like "yuh all good" for IC closure, but meh. It doesn't usually result in anything.

This is part of the reason we have SOP regarding what information can be shared, and why the suit sensors monitor is covered in that SOP. Nobody in Medical should be commenting about what they see on the sensors over general comms unless it's clearly an emergency. And for scenes, all you have to do is remember to turn your sensors off, or just take the jumpsuit/nudepermit/etc off, and that handles it. Or do nothing, because nobody's going to do anything about easily-identified digestion damage unless you call for help.
