### ISSUE TITLE
[SUGGESTION] Custom vendors to stock items into for (at least) service jobs

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#4787]
So after some discussions around the discord, it was discovered that it's incredibly frustrating to leave your post and then either come back to everything being gone, or suddenly being called back to it despite never being needed all shift. While reading through what people were saying, I did a bit of brainstorming and figured "Well, what if we added vendors that service staff can stock to sell excess product?" That way, you can just toss everything into it, and now if people want to just blow through your whole stock, at least now you're profiting off it. Besides, more jobs need ways to profit like how mining can. Charging with the scanners doesn't really count, since typically this gets people absolutely assblasted IC and OOC at you, unfortunately. 

Figured i'd just put this out there before I forgot, even though we're still a bit frozen at the mo'.

**Comment by Wickedtemp** [comment]
Can confirm. Tempest doesn't buy drinks or food from the bar or kitchen. This is mostly just because shi uses synth-meat and a food ration, but still.

This would be neat. We have characters here that try to make overeating their defining character trait. And while its against the rules to just eat everything the chef takes the time and effort to make, if you leave for a while and come back and its gone... You don't know if was one person or five. And in a way it doesn't matter because the end result for you is the same - all of the food is gone. 

I think the only issues that'd come out of this are: 
1) The chef throws everything into the vendor to make people pay which would lead to the above 'angry people' thing. 

2) The vendor needs a whitelist, else people are gonna be shoving random things into it to force people to pay money to get it back, like stolen belongings.

3) Someone's gonna hack the vendor at some point and steal whatever is in it.
