### ISSUE TITLE
there's no instructions anywhere near the emergency tether shuttle explaining the maintenance mechanic

### ISSUE THREAD

**Issue by nerdass** [VOREStation/VOREStation#4809]
#### Brief description of the issue
nothing tells anyone about the maintenance mechanic

#### What you expected to happen
there to be something in game that explains that you need to fix the engines after every flight

#### What actually happened
not that, also how do we fix them when it's docked space-side

#### Code Revision
1fe04192c11e2ad7357512d5a873c44a4ea687d3
 
#### Anything else you may wish to add:
- maintenance mechanic should be removed, genuinely adds nothing and if it was gone, people would stop bitching about us adding stairs to orbit and not be able to say "BuT tHe ShUtTlE cAn FaIl" when we point out the shuttle

**Comment by Iroquois-Pliskin** [comment]
Gonna piggyback on this here. I'm pretty sure the airlock controllers for the station-side shuttle dock is still fucked.

**Comment by Wickedtemp** [comment]
I'd kinda prefer an equivalent to stairs ranging from floor three to four. Fluff it however you want. A transit 'tube', a small lift, gravity manipulator, 'bluespace', etc. I agree that the shuttle shouldn't need a repair after every single use else you risk dying. But it isn't a good substitute. Moving between floors shouldn't be a hassle. Moving from the chapel to the bar, even when there are power issues, shouldn't be annoying as hell.

It's gotten to the point where people are opting to use wrapped lockers and destination taggers to get around when there are power issues. Because it works, and it works better than anything else we have other than the elevator.

**Comment by Little-119** [comment]
Just make it a ladder that takes several minutes to climb while 'Snake Eater' plays

**Comment by Novacat** [comment]
Ace was told about this mechanic and he asked to straight up remove it, so that is what I am going to be doing.
