### ISSUE TITLE
[SUGGESTION] Option to disable contamination fully when using stripping bellies

### ISSUE THREAD

**Issue by Shophaune** [VOREStation/VOREStation#4856]
#### Brief description of the issue
There's plenty of choice as to how you want gear fouled up by your guts to be described - but no option at all to, y'know, NOT gunk up someone's stuff. So anyone who wants to do stuff with stripping but is turned off by the disgusting green sludge that their gut somehow generated JUST for these items is a bit stuffed. Let alone the people with bellies for say, carrying someone in a tail - those foul items up too. Plus, healing bellies apparently soak everything EXCEPT prey in poison? Having an option to disable contamination would solve most of these problems.

#### What you expected to happen
- People not to be mechanically prefbroken if they use item stripping mode
- Dousing people's clothing in poison to be optional.

#### What actually happened
- ...see above.

#### Steps to reproduce
- Be eaten into a non-digestive vore organ with stripping and itemweak enabled. Even one where it makes no sense for items to get dirty, like coiled up in a tail.
- GREEN SLUDGE OF EW

#### Code Revision
Current

**Comment by Vorrarkul** [comment]
For the record: current code revision is 6c758051139daed75163f1941b40600bd97dceaa

**Comment by Wickedtemp** [comment]
I'm not into grossness and filth. It's why all of Tempest's insides have plenty of natural 'goop', but at no point is it "rancid" or "gross", or any of the prefix options we have available. I actually dislike it in general, it's one reason I get so annoyed when people don't clean off their vore partners things, because great, now I get to deal with all of the gross bits.

And out of all the ways to customize the filth kink... There's no "disable" toggle. Instead, every time I'd use itemstrip, instant filth. And not only that, it comes with a disgusting prefix and a vomit-green overlay just to show how gross it is. Even if its in a vore panel slot that wouldn't make sense for it.

Have a "cleavage" or breast vore or "toes" slot for smothering kinks? Tada now those are filthy and green, too. Are you a macro and thus may have a panel slot for advanced handholding? Filthy and green. Tail coiling for Naga's and Lamia's and serpents in general? Filthy green! CV? Filthy green. 

And just to drive it home just how gross and filthy and slobby your character is, not only is the sludge visible.. but it also actively poisons you if I'm not mistaken. 

So... yeah. This is just kinda something I've dealt with, but I'm reaching a 'boiling point' of sorts. I can't even use item-strip on vore panel slots that were meant to have it.

**Comment by Heroman3003** [comment]
Contamination as a mechanic in general seems like overdone needless punishment of prey for participating in vore, so being able to toggle it, reducing its severity and effects, should all be only a net positive for everyone involved.

**Comment by Sebbe9123** [comment]
I'm in favor of this as long as it doesn't do away with disabling ID's. Contamination isn't for everyone.
