### ISSUE TITLE
[Suggestion] Let the AI use vore bellies

### ISSUE THREAD

**Issue by prismaticIris** [VOREStation/VOREStation#4863]
#### Brief description of the issue
As AI, the only thing I have access to when scening is the Hardlight Nom verb, which basically just turns the hologram's sprite purple and holds my victim inside my hologram harmlessly. If possible, I would like to be able to use the same vore system as literally every other character on the station uses, which would allow me to create descriptive guts/maws/skyrim ports/the station's inner workings/virtual reality/pretty much anything else instead of just 'ECH0's hologram starts surrounding Victim!' I'd also like to be able to digest/absorb/etc instead of just holding them harmlessly.

#### What you expected to happen
Writing out nice vore bellies for my partners to enjoy.

#### What actually happened
Hardlight Nom

#### Code Revision
6c758051139daed75163f1941b40600bd97dceaa 
 
#### Anything else you may wish to add:
Hands would be nice, too, but probably also a bigger ask worthy of its own issue/feature request for discussion.

**Comment by AldenBluetenberger** [comment]
somehow i think that violates every law 1

**Comment by prismaticIris** [comment]
Heaven forbid the AI participate in what the entire server is based around!

**Comment by AldenBluetenberger** [comment]
Heaven forbid the AI violate the universal law of NO HUMAN HARM.

**Comment by SpadesNeil** [comment]
![no fun](https://user-images.githubusercontent.com/6484985/57895000-5bb9e080-7817-11e9-8d06-08219a79aa43.jpg)

**Comment by SpadesNeil** [comment]
Jokes aside, if we give AI the ability to use vore bellies, I want them to be hardlight noms (which I think we already have) and I do not want them to have the ability to digest people.

Unleeeesssssssssss they have an ion law active or have had their laws changed. This would be enforced by OOC rules.

Even still, I'd prefer the AI not have vore at all because the AI is something I consider too omnipresent to be given vore. It's something that will not only attract _a certain kind_ of roleplayer that I don't want to deal with, but it also is something that just pushes the limits of an already questionable lore.

**Comment by AldenBluetenberger** [comment]
mfw no fun allowed for realsies

**Comment by Screemonster** [comment]
only allow the AI to nom people if it's done right in the core like that bit in superman 3

**Comment by TheFurryFeline** [comment]
Partially allowed with shells, but not so with holopad noms.
