### ISSUE TITLE
[SUGGESTION] Enabling AI shell functionality

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#5022]
#### Brief description of the suggestion
Recently, thanks to upstream, we've got a new functionality for AI, ability to get cyborg shells. It relies on config files however, and default for it is being disabled. Suggestion is to basically enable that functionality. It being disabled was more understandable when AI could just spam shells and only shells accessible were drones from drone fabricator. However, with system being closer to tg's and shells being borg bodies for AI, it is much better. It also gives AI some much-needed ability to properly interact with crew in lewd/vorish ways that does not rely on hardlight noms, which are extremely lackluster, and some gameplay for times when crew is uninterested in interaction with them.

As for the 'roundstart shell spawn' one, this one is trickier. Lack of this makes AI rely on pretty unreliable department (research) for providing of shell, but presense of one may be too overpowered.

Either way, whether they get roundstart one or not, I think getting the shells as a whole enabled is a good improvement for AI gameplay.

**Comment by prismaticIris** [comment]
Having -any- form of hands would be simply amazing, as would being able to actually, y'know, -do vore on VOREstation-

**Comment by Shophaune** [comment]
I'm in agreement with this, because if nobody wants to interact with you as an AI you're pretty much relegated to a door opener a lot of the time - and often not even that, because people so rarely want access to places they don't already have it for. With a shell available an AI could be of actual benefit to Medical/Research/Supply, or make up for a missing bartender - plus the extra options for how you look if you do interact with crew.
