### ISSUE TITLE
[Suggest]Healbelly Usage Can Be Tricky! Solution!

### ISSUE THREAD

**Issue by Wickedtemp** [VOREStation/VOREStation#5241]
#### Brief description of the issue
So, as Medical, it can be tricky to know if someone's okay with using the heal-belly. Some players don't see it as a prefs-thing as long as it's used to save them mechanically, others care a whole lot, understandably so, but it isn't really mentioned directly in notes/prefs.

Even if it was, it'd be difficult to scan the ooc notes of someone who's dying in crit and read through them while things are going on and you need to know if you have an opportunity to use it or not right that instant. Usually this means always asking in LOOC, which is fine when you get a quick response and awkward when it turns out this person has LOOC disabled and you don't realize you're talking to nobody. True story. 

I feel like there's a better way.

#### What I suggest:
In character setup, in the Vore panel, have a 'healbelly' setting. 3 options, 'Always Yes', 'Always No', and a custom field that allows for a small, perhaps 150 character field that'd show up as a pop-up. Exactly how flavor text shows up upon examine. Click read-more and it has a pop-up window. Do that. The reason for this is because some people may want to specify if they're only okay with it with certain people, species, ''destinations'', only for major injuries, etc. Given that every character has the potential to use the healbelly, I think having this info readily visible upon examine would be a good idea.

Edit: It's also worth noting the existence of the canine borgs. Their primary means of transport and healing would involve vore, and given that mechanically they aren't able to do a whole lot else OUTSIDE of that, having this would actually really help their job be a bit easier, too.

**Comment by Screemonster** [comment]
The answer is they should fill out their damn notes properly. At most have a _very_ short thing they can put into the mechanical vore prefs popup so medics under a time pressure can quickly check it. Literally like yes/no/borgs only/no dudes etc.

**Comment by Wickedtemp** [comment]
The vast, vast majority of people don't have anything about heal-belly in their notes. I don't think not including it counts as "not doing it properly" given the sheer number of people who don't have it included, it's basically the 'normal/expected'.

If it's included in Mechanical Vore preferences, that'd be neat, but you'd still need a custom-field with a small character limit to have stuff like "Only for macros", "Only for OV", etc.

**Comment by Heroman3003** [comment]
I do not think every single potential situation warrants a settable preference. Mechanical vore prefs are for checks related to mechanical interaction and their visibility was only really added so that people could know in advance whether drop-nom would work or not. And there are many, many other things where if you cant say from looking at notes and/or have no time to ask, and in those situation its best to go with safest default option. In case of healbelly, that would be avoiding using it.

Mechanical prefs are called that for a reason: all of them are prefs related to specific mechanics' ability to at all _affect_ the person in question. Of course, its possible to make it so opting out of healbelly prevents ability for any form of healbelly to ever affect them. Then I would understand that option being there. But in general. We do not need to add 'mechanical pref' that has no mechanical effect and is there just for people too lazy to set their notes/read through someone else's notes.

**Comment by Wickedtemp** [comment]
Okay, neat. Suggestion was for either a lil bit underneath OOC notes, still available by examine, or in Mechanical Vore preferences. I kinda figured the latter one may be a better fit as it's regarding, y'know...vore mechanics. Even if the vore mechanics addition wasn't added with the explicit intention of "This can be used for healbelly prefs", that doesn't mean we're magically unable to include it for the sake of having it be in a place that's readily visible, and even if that was the case...Put it below the OOC Notes bit. 

And I know some people are still going to go BUT TEMPEST WHAT ABOUT JUST OOC NOTES. TEMPEST IS IT **REALLY ACTUALLY SUPER VITALLY IMPORTANT?!?!**, and to be honest, I don't really expect everyone to agree that this is important, but I'm hoping that enough people just kinda chill out and look at what's happening. There's a vore mechanic that's a lot of fun that can actually be used to heal people viably. Generally, when people need healing, it's difficult to LOOC everyone who needs help and have them respond quickly enough or read through their OOC Notes every time. We've  also had cases where it's fine in OOC Notes for the few people who have it listed, a doctor uses it, and then gets flak because it turns out the patient only likes it when it's done by macros. Or because the doctor used the wrong orifice, for another example that's happened.  

Or, we can go for the safest option and just not use a vore mechanic on a vore server.

It'd be a pretty big QOL for a lot of people, not just medical, because literally everybody has this ability. This would pretty much be a net benefit for everyone.

**Comment by Heroman3003** [comment]
What I am saying is. It does not belong there if it does not affect mechanics. They are not mechanical vore preferences because they are referring to mechanic, they are because they AFFECT mechanics. If its nothing but visual, then its not mechanical, but regular preference. We do not need a yes/no slider for healbellies. Add one for healbellies, "what about soulcatcher, vore subtypes, species prefs, etc, etc", until mechanical prefs replace normal, just in generic chart form. And you yourself specify why it would be an issue to add there: conditional situations. If it requries 150 characters? Put it in OOC notes. Yes, safest route being not doing it at all is  far from perfect. But its what always allowed to avoid prefbreak.

Plus, not everybody has this ability. Some people actually respect fluff of characters and don't just have healbelly because mechanically its two clicks away at any point in time.

In general. Use OOC notes. And if you don't, don't be surprised when you miss out on stuff. Be it healbelly or anything else.

**Comment by Wickedtemp** [comment]
- First point, Scree was the one who suggested the Mechanical Vore Prefs bit and I figured it'd be a better idea than just putting it under the OOC Notes, but either works, I don't really care.

- Second, Soulcatcher, vore subtypes, species prefs, etc, aren't all fair comparisons as those aren't "time sensitive" to any degree. Healing, at times, is For scenes, you have plenty of time to read through prefs. For someone who's dying in a breach, you kinda don't really have that luxury and some people hit the size limit on their OOC Notes (me included), can't really read through everything if it's a small wall of text, in a timely manner. Additionally, some people have LOOC disabled or just don't respond quickly. Already kinda covered why I think it'd be a good thing to add aside from this.

- Most situations we have are kind of conditional. Drop-noms, for example. The point is, it's coming up often enough that a few people think this would be a good addition. That's the important bit here, I think, and that point really isn't an argument _against_ this addition, but rather just asking "okay but why". 

- For the character limit, literally was just an off-the-top-of-my-head number because Twitter used to have 140 as its limit so that's what I thought of when I pictured a 'character limit'. 

- "Yes, this option is far from perfect, but..." Okay. We can make it slightly _better_ though, right? 

- "Not everybody has this ability..." - Nah. Everybody has it, just not everybody actively uses it, and a few kinda want to but can't always do so due to issues mentioned above. 

Like... I get that you might be opposed, but I don't really know why. You might not think it's necessary, but would this addition be a _bad_ thing?

**Comment by Heroman3003** [comment]
I do think so, because adding a 'toggle' preference that doesn't affect mechanics just opens floodgates for more and more "But why not its not bad" slider additions to the mechanical prefs beyond that. They affect mechanic. Participation _desire_ has and always will belong to OOC notes. That or make another, SECOND set of notes. Just don't put it into mechanical preferences. Because doing so is beginning of a slippery slope.

Drop-noms ARE conditional, yes. But the preference is there because preference is related to mechanics. Preference determines your ability to be eaten via telenom or dropnom. Your suggestion does not include ability to 'be healed in healbelly' being togglable. All mechanical prefs are conditional, really. Thats why OOC notes exist. They are to explain how you want it to happen. Prefs are just to enable/disable mechanical support for it. Thats why it should not be there. It is not what mechanical preference is.

And 'everyone has that ability' is same as saying 'everyone is a switch' or 'everyone can do every job'. You basically say just because someone is mechanically capable, they should be doing it, and if they don't its because of those 'issues', not because it doesn't make sense. Its also partially why I was opposed to healbelly being buffed, because now those coercions into it being used more are gonna be happening becuase 'but its good and you always have it'.

**Comment by Wickedtemp** [comment]
Your first two paragraphs are just kind of repeats that were already addressed but will post again.

I do not care if it's listed in Mechanical Preferences or not. Scree mentioned it, I thought it was a better idea than just putting it on initial examine, but I honest-to-god do not care which one is used, it doesn't matter to me, it isn't important, it's to be decided, it's utterly and entirely irrelevant. The reason why healbelly would be listed explicitly and not soulcatching, species prefs and other examples you mentioned is due to the fact that healbelly is more time sensitive. You usually have time to sit down and read notes of someone you want to scene with. You have time to work out a soulcatcher scene. You don't always have time when it comes to saving someone in crit or in a hazardous environment. Sometimes, you do have time and it's neat, but that isn't always the case. If it was, I wouldn't be suggesting this and I wouldn't have anybody go "huh that could actually be really nice" when I float the idea in discord.

For the new bit,

- "And 'everyone has that ability' is same as saying 'everyone is a switch' or 'everyone can do every job'."
All I said was that everybody has the ability to do it if they wanted, that's literally an objective fact. 

- "You basically say just because someone is mechanically capable, they should be doing it, and if they don't its because of those 'issues', not because it doesn't make sense."
Citation needed. Never said people _should_ use it, never said the sole reasons everyone doesn't use it is due to the issues I mentioned prior. 

- "Its also partially why I was opposed to healbelly being buffed, because now those coercions into it being used more are gonna be happening becuase 'but its good and you always have it'."
Covered in that PR. The only real 'buff' was that I changed it back to kinda-close how it used to be and added a sloooow genetic-heal. I even nerfed the amount of brute/burn it healed per cycle by _half._ People who want to use it can use it on people who want it used on them. All this does is make it easier to determine who wants it used on them. Nothing else changes. Already covered why I think it's important that the prefs for this are more 'visible'.

Which is to say...This suggestion wouldn't even do anything new, it'd just take information that would ideally already be in OOC Notes somewhere and makes it easier to locate and read in less time, which would come in handy in time-sensitive situations where the healing belly-mode could be used. Can you explain how this is a bad thing?

**Comment by Screemonster** [comment]
You know what, I wanna put other things on the "mechanical vore prefs" popup now and make it more like a quick prefs reference for the _common_ prefbreaks. 

Like AFK noms. Hell, if that was a toggleable var on someone to say whether they're okay with AFK-eats or not we could have a check during swallowing that alerts admins if the prey is AFK.

**Comment by CockatriceXL** [comment]
So I think this would be very helpful, especially for borgs. Reading through somebody's OOC notes while they're bleeding out and being attacked by mobs is pretty difficult. LOOCing, when you don't find anything about nomming them to save their life but they're screaming at you to save them anyway, can be even harder. There have been times where this would have helped a lot, like when a pred-only player was, in fact, alright with being swallowed by a sec borg but I had to run around, kiting a dragon and trying to type for a while to find this out.

I've also been in situations where I've been dragged around by a borg, and I have to wonder if they didn't think I'd be okay with being nommed even though my prey prefs are very open. I'm pretty sure I even have the words "just grab me without asking" in there somewhere.

Frankly, I don't think displaying a few common or time sensitive pref issues on examine is much of a slippery slope. I also don't think claiming that something is a slippery slope is a good argument, since crowding the examine text with soulcatcher or species info would be separate decisions, and you could just reject those suggestions when they come up. Adding belly heal pref information doesn't force you to add other things.

This change would make it easier to see who's okay with healbellies and protective endo situations, and who isn't. I would really like to see more practical applications of vore on the server. Healbellies and belly brigging just seem so rare despite this being a vore server.
