### ISSUE TITLE
[SUGGESTION] Cancel button for cloning pod/way to recycle bodies

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5256]
#### Brief description of the issue
As anyone who has worked medical knows, there's plenty of times you print a body and then UH-OH turns out the person didn't need resleeving, quit the round, or was supposed to be DNR. Well, this is problematic as there's no way to stop the process, or get rid of the body if it finished aside from voring it, but that's not always an option (and kind've creepy for some people)! My suggested solution is a two step fix: first is adding a cancel option to the cloning process which just halts the process, deletes the growing mob, and refunds biomass. Second is being able to just dump blank sleeves into the cloning pod to have it cycle them back into biomass. That way there's a non-prefbreak way to get rid of whoopsie daisy bodies instead of just filling the morgue with them.

**Comment by Wickedtemp** [comment]
Can confirm, this happens frequently. At times, every time I've printed a body to resleeve someone, they're doing soulcatcher stuff, or they QTR'd, etc, and it's like... what do I really do with the bodies. I can leave them in patient recovery, which kinda feels more like the 'right' option because the morgue is usually for corpses, but it's just weird because I'd have like 4 bodies just chilling there. The morgue is sometimes better mechanically/OOCly because you can just label the bodybag that it's an 'empty' body, but feels weird from an IC standpoint because they aren't actually a corpse. 

I think out of the two options, the second is more important. It'd be super helpful.

**Comment by SpadesNeil** [comment]
A cancel button is probably a good idea.
