### ISSUE TITLE
[SUGGESTION] Crematorium in the chapel

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5257]
#### Brief description of the issue
Every other station has one, why not our own? Plus on here at least it has the RP use of some people wanting to be cremated over just being dumped in a morgue, instead of it just being a changeling kill tool.

**Comment by Wickedtemp** [comment]
IIRC on one map we used to have one in maint, somewhere, but Iunno if it was ever functional. I'd be fine with this. Could potentially put them near Med/Sci for body disposal (for science's monkeys or whatever if they don't want to vore, and for patients who's records indicate preference for cremation). 

Might be hesitant to just leave it at one cematorium in the chapel but have it accessible by these departments because, well.. the morgue used to be like this on a previous map and it sucked super hard. Security, Science and the Chaplain all had access to it because one of its airlocks bordered on a public hallway, and some shifts I'd hear all of the gulping noises and run in to see an idiot eating all of the corpses, it got to the point where I'd literally just station myself in the morgue instead of reception some shifts to keep an eye on things.

But, yeah. This would be nice.

**Comment by Ketrai** [comment]
seems like a mapping oversight. Talking about that... DOES THE CHEF HAVE A BIRTHDAY HAT AND A PAPER TRAY YET?

**Comment by SpadesNeil** [comment]
This is a pretty simple change. You can make the PR, I'm sure.
