### ISSUE TITLE
[Suggestion] Please disable solar grubs. 

### ISSUE THREAD

**Issue by chaoko99** [VOREStation/VOREStation#5280]
#### Brief description of the issue
Solar Grubs are frequently found to be rather hated by most players I've asked, including myself. They add very little to the game experience, and for engineers, force them out of their scenes as they are seemingly expected by the crew to fix the problem (Because the crew doesn't have multitools apparently, or are just straight up too lazy.) I propose disabling the event until it is reworked.

They're disruptive and annoying to deal with in general. 
#### Anything else you may wish to add: 
I can gather a vote if I have to.

**Comment by Wickedtemp** [comment]
As CMO, I'd usually have all of the grubs in Medbay handled right about the time we get the NT Announcement. Multitool and Toolbox are both in storage so it only takes a minute or so to sweep the department.

I think the map just isn't friendly to this type of event. Sure, departmental crew can sweep their own departments if they'd stop being lazy-as-fuck, but the Civ areas are spread all throughout the station in a way that makes it seem almost random. 

Library, bar, pool, rec, chapel, cafe, etc, span multiple floors and are just kind of all over the place "wherever they fit", so when it comes to Civ areas, it goes from "Sweep a department" to "Sweep most of the station", and I can kinda see why people are reluctant. A short term fix would be code that only allows grub spawns in actual departments with 2 or 3+ crew in them on the manifest. A better longterm fix would be a map edit to make the tether less tedious to traverse and have a designated Civ area.

**Comment by Ketrai** [comment]
I have been thinking on making grubs spawn in one specific department, and then announcing it as such for a while. I'll see if I can update the event as such. Shouldn't be too hard seeing as departments are just groups of areas. So instead of picking a random on station area i'll have it pick a specific department.

I don't think they should be removed entirely. There's more annoying things to fix like hunting down that one vending machine, or fixing all the lights that have just sprung. The main issue with solar grubs is that if you don't deal with them they become more than just an annoyance.

**Comment by SpadesNeil** [comment]
We can crank down the frequency, but we're not going to remove them because one group of players doesn't like them.

Another group of players, which includes myself, will be upset if they are removed entirely.

**Comment by Novacat** [comment]
We already cranked down the frequency enough to where they only show up in highpop rounds with lots of security/engineering.
