### ISSUE TITLE
[BUG] AI control wire does nothing

### ISSUE THREAD

**Issue by Low3** [VOREStation/VOREStation#5377]
#### Brief description of the issue
When you cut AI control wire on airlock, AI can still control it.

#### What you expected to happen
AI not being able to interact with airlock

#### What actually happened
AI was able to bolt, electrify and do other naughty stuff with airlock.

#### Steps to reproduce
- (Step 1) Cut AI control wire
- (Step 2) Ask AI to do something with door
- (Step 3) AI actually does something with door

**Comment by mistyLuminescence** [comment]
Intentional- if an AI interacts with an airlock with its AI control wire cut, it'll take them about a minute to regain control (and the wire will stay cut, naturally). You have to mend and re-cut it again once the AI regains control to lock them out again- or just kill power to the airlock or disable the cameras nearby so they can't interact with the airlock at all.
