### ISSUE TITLE
[SUGGESTION] Off-Duty OOC Button

### ISSUE THREAD

**Issue by mistyLuminescence** [VOREStation/VOREStation#5560]
#### Brief description of the issue
You know how people go off to do scenes all the time without going off-duty, and then something bad happens that everyone thinks they'll respond to, but they actually don't, and then the bad thing just gets worse? (That isn't a hypothetical. People don't do their jobs.)

#### What you expected to happen
People go off-duty to scene, or pause the scene to do their job.

#### What actually happened
People don't do that, and bad things happen as a result.

#### Steps to reproduce
- Play on VOREStation
- ... that's it, that's really it

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/3ecec80c42f7693dd3fe7af675b44b6795115b21
 
#### Anything else you may wish to add:
- Solution: add a button that lets you go off-duty remotely without needing to visit a time clock. It works exactly the same way as the time clock, but can be done anywhere. You wanna scene? Go ahead and use it and nobody will shank you for ignoring your duties. If you don't use it, people might bitch at you, and reasonably so.

If you want to scene and not be interrupted: either go off-duty, or play a role where you're not expected to Do Things (e.g. command secretary).
If you want to scene and you're fine with being interrupted: scene away!
If you want to scene and you don't want to be interrupted, and you also don't want to go off-duty to tell other people that you're not available to do your job: you're a dick.

**Comment by SpadesNeil** [comment]
>code revision: current

That's not how that works you dunce. :U 

I'll just change it myself.

**Comment by SpadesNeil** [comment]
Anyway,

Clocking out is in a pretty good place where it's convenient enough for people to reasonably do it without being so convenient that it's reasonable to tell people to clock out every time they put their tools down to grab a snack out of the vendors.

I want to keep it that way. If things go to shit and your staff is missing, figure it out IC. I have no desire to have this feature. We did fine without it for five years. Just because people are suddenly crybabies about other people having scenes doesn't change that fact.

**Comment by Screemonster** [comment]
I don't like this. If clocking in/out becomes as convenient as clicking a button, that creates an expectation to actually use it - as the suggestion post stright-up says - "If you don't use it, people might bitch at you, and reasonably so."

I don't _want_ to create an environment where it's considered "reasonable" to bitch at other players.

And ace replied while I was typing and just pretty much said exactly what I was going to say. The last thing I want is for people to be eaten, then sec to check the manifest and be all "AAH, BUT THEY DIDN'T HIT THE OOC BUTTON SO EITHER THEY'RE UNWILLING OR THEY'RE WILFULLY NEGLECTING THEIR JOB, EITHER WAY WE'RE FILLING YOU WITH ICKYPACK AND AT LEAST ONE OF YOU IS GETTING ARRESTED"

**Comment by SpadesNeil** [comment]
ni🅱️🅱️a did you just copypaste what was said in the admin chat too

**Comment by Screemonster** [comment]
"what was said" BITCH I WAS THE ONE THAT SAID IT

**Comment by SpadesNeil** [comment]
NUH UH IT WAS MY IDEA

I'M IN CHARGE SO I CAME UP WITH IT :]

**Comment by CameronWoof** [comment]
If you were going to be arrested for dereliction, you'd be arrested with or without the OOC button existing. I don't think that's a very good argument.

As for the existence of the feature creating an expectation to use it... yes? If departments being "secretly unmanned" as all of its employees individually slink off to scene is a problem, this is the solution. Ignoring the solution because (??? fill this blank in for me, please) is you signaling that you'd rather cause a problem than not cause one.

**Comment by Screemonster** [comment]
If there's nobody in the department that's able to respond to a call then it makes no difference whether they're on or off duty, people clocking off isn't going to magically make your screaming over the radio get answered. Clocking off-duty doesn't even free the slot.

And where you say "expectation to use it", I read "invitation for elitist assholes to bitch about people that forget to do so because how DARE they play a game wrong".
We got on without having timeclocks _at all_ for the best part of half a decade, and if the kind of bitchy vagueposting I had to deal with last night is what's going to come of them because OH NO SOMEBODY DIDN'T CLOCK OFF TO SCENE then I'd rather the fucking things get removed altogether. We had people who weren't even fucking there coming out with shit like "that EMT should have been jobbanned" because someone mentioned that they called for someone on the radio and weren't answered and there was an EMT on the manifest. Nobody in the conversation knew what the EMT was actually doing, it was deadshift so they could have been AFK or dead for all anyone knew. But no, the peanut gallery says that they (whoever they are) deserve a jobban.

I almost want to add this just so I can use it as a fucking ban trap to yeet anyone who bitches at people for not using it now.

**Comment by CameronWoof** [comment]
The likelihood of newcomers joining the department to fill the void is increased if the manifest correctly notes that there's no-one working in it as opposed to saying "it's all full here, chief" when in reality, no one's there to help.

This would not be necessary for *every* time you scene--only if you want to scene *and* have no intention of interrupting it to deal with your job's responsibilities if called upon, whether that's your choice or the boundaries of your scene make it awkward.

**Comment by Screemonster** [comment]
That's what the HoP is for. Or people can _join_ off-duty and clock on if they find that there's nobody in their department actually active. Or call admins in to put out a bulletin.

And you say "it would not be necessary", but if we make it as easy and convenient as pushing an OOC button, it'll de-facto _become_ necessary if you don't want to risk shitheads whispering behind your back.

Oh, and adding an OOC button to change an IC manifest is ickock. The only time OOC buttons get a pass for drastically affecting IC situations like that is when vore preferences are involved.

**Comment by CameronWoof** [comment]
It being a PDA function would be equally convenient, as the sub or the dom can just punch out remotely.

**Comment by SpadesNeil** [comment]
Beating a dead horse methinks. I am vetoing this on the grounds that too fucking bad it's space station 13 and sometimes crew are dead. Deal with it IC.

Not giving the elitist twats more excuses to yell at other players.
