### ISSUE TITLE
[SUGGESTION] Add Auto-hiss toggle under character setup

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#5629]
#### Brief description of the issue

You have to manually re-enable autohiss every single round/reconnect

#### What you expected to happen

Select Autohiss under the "custom traits" (or a race that has it), and it automatically does it

#### What actually happened

You have to remember to manually go to "OOC" tab and enable auto-hiss to either basic or full. (as a new player that threw me off)

#### Steps to reproduce
- Choose Autohiss
- Spawn in
- Type.
- ???
- Profit

**Comment by Heroman3003** [comment]
Autohiss is weird like that because its tied to your client's current connection and not your character's settings. So for example if you were to quit the game and re-enter, autohiss would get disabled. That would really require redoing how autohiss works entirely to achieve. Or at the very least what its tied to.
