### ISSUE TITLE
[SUGGESTION] "Request Spice" Button should display a message if successfully requested

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#5631]
#### Brief description of the issue

When pressing Request Spice, you get a confirm box, then you hit yes, and... nothing. No message saying (request sent succesfully) or etc, or a "IT IS UP TO THE GODS" or something.
Note - Also, no notification of the "10 minute wait before another spice request". You hit the button once, then yes, then... nada. Hit it again, hit yes, nada. No reminder you have to wait x more minutes before requesting spice again.

#### What you expected to happen

Press button, answer yes, then get a message in chat saying (request in) or something so you don't wonder if your client didn't actually send it

#### What actually happened

Press button, hit yes... nothing else. Unless admins choose to say "the dice have been rolled"

#### Anything else you may wish to add:
- The IC "Pray" verb does it well, it says "your prayers have been received by the gods" <3
- Having it say "x people have requested spice" is nice too, saying basically "this many people are bored too, or just want their shit fucked up"

**Comment by SpadesNeil** [comment]
I don't see the point of telling the players how many people have requested spice other than creating a false idea of democracy, when in reality, it's up to the admins, and any other implication would feel like lying. An admin is encouraged but not required to fulfill such requests regardless of how many people ask for it. Sometimes we're just too busy or have no ideas.

Furthermore, "request spice" is vague as fuck. We prefer when people offer up actual ideas and effort instead of making us do all of the work including even the conceptual stage. Kind of like these suggestion issue posts. Not yours in particular, not trying to single you out, but I feel like this would add more to that problem by encouraging more lazy demands of "MORE FUN" without anyone actually offering help to make it happen.

**Comment by Rykka-Stormheart** [comment]
> I don't see the point of telling the players how many people have requested spice other than creating a false idea of democracy, when in reality, it's up to the admins, and any other implication would feel like lying. An admin is encouraged but not required to fulfill such requests regardless of how many people ask for it. Sometimes we're just too busy or have no ideas.
> 
> Furthermore, "request spice" is vague as fuck. We prefer when people offer up actual ideas and effort instead of making us do all of the work including even the conceptual stage. Kind of like these suggestion issue posts. Not yours in particular, not trying to single you out, but I feel like this would add more to that problem by encouraging more lazy demands of "MORE FUN" without anyone actually offering help to make it happen.

Can I look into adding an option to "type idea" under request-spice? I've had to do "request spice" and then also do "pray" my idea in. 
If it was "request spice: 'player types idea here'", perhaps that might be better?

**Comment by Heroman3003** [comment]
Its literally an ahelp with a different name for no reason at that point tbh. Also, the message thing has been added on master so the original issue is resolved anyway.

**Comment by SpadesNeil** [comment]
>Can I look into adding an option to "type idea" under request-spice? I've had to do "request spice" and then also do "pray" my idea in.

If you require players to fill in an idea to accompany the request, I will allow it. Yes, it's just another form of ahelp, but it's a form of ahelp that encourages a specific purpose.
