### ISSUE TITLE
[SPRITE ISSUE?] Footwear don't show contamination

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#5642]
#### Brief description of the issue
For some reason, black shoes don't show the giant biohazard symbol over them when contaminated, which leads to people just continuing to wear the things while wondering what's poisoning them.

#### What you expected to happen
They'd show up as contaminated like pretty much all other articles of clothing.

#### What actually happened
They did not.

#### Steps to reproduce
- Go outside with black shoes on
- Hit a patch of phoron to get contaminated
- Watch as your shoes don't show up as being contaminated, despite the fact they are.

#### Code Revision
-  release - 
0015a40b20070fa8cc03fd2c80ca7655174b50da

**Comment by Heroman3003** [comment]
Are you sure that its A) just black shoes and B) they are actually contaminated?

**Comment by Novacat** [comment]
Can confirm this bug, except it was workboots that were contaminated. Seems to be a footwear related problem?

**Comment by Rykka-Stormheart** [comment]
Any update on this?

I'll start tackling it soon if nobody else has.

**Comment by Cameron653** [comment]
I tested this and found the following:

- It's a bug that has to do with **_only_** shoes.
- The bug is due to "update_icon".
- When update_icon is called on shoes, it removes almost all existing overlays.

More detail:
- Stepping onto blood will remove all overlays, including contamination and boot knives.
- Putting a boot knife in will remove all overlays.
- Calling update_icon removes all overlays EXCEPT for the boot knife overlay. If a boot knife is being hidden by blood, the blood will be removed and the boot knife will show.

**Comment by Cameron653** [comment]
nvm I found a fix, sending to polaris now.
