### ISSUE TITLE
All Races Trash Eater

### ISSUE THREAD

**Issue by SioxGWolf** [VOREStation/VOREStation#5664]
#### Anything else you may wish to add:
- All races should be able to just eat items... that they are able to logically eat. When I eat a person covered in items I can but take off one item, say a bandana and eat the person...I require a whole new person to eat, just to devour that bandana... I rather just skip the step, and eat item... especially when I want to reunite that item with the softcore pred I have in my belly!

**Comment by Heroman3003** [comment]
I have to agree. Trash Eater may be called that, but in reality with its pool expansion and practical applications, it became Object Swallowing as a rather peculiar way of teasing people or mechanically contributing to scenes. It really should be available to everyone, though it should be an OPTION as to whether you want to have it or not, considering it can result accidental swallowings of items you didn't want to eat.

But there's no tease more fun than snatching a nerd's hat/glasses/headset, swallowing it sensually and slowly in front of them and making them "Go get it". It really shouldn't be locked so hard as it is now.

**Comment by KasparoVy** [comment]
Could probably just break it out under the egg choice as a yes/no, looks like this:

![virgo ss13 swallow obj yes or no](https://user-images.githubusercontent.com/12377767/63312045-b455b980-c2ef-11e9-8bee-f4a93ef696df.png)

**Comment by SioxGWolf** [comment]
Kinda like it, yeah~ Either that or above it.

**Comment by SpadesNeil** [comment]
So, I have in the past denied object swallowing because I am not allowing players to use their stomachs as an extra backpack (possibly unlimited) to store loot in.

**I am still not going to allow that.** No argument will change my mind, because it's a game breaking balance change.

Trash eater only allows you to eat, well, trash. There's no point to collect those items except to dispose of them. All races having trash eater is something I am also against because it makes no sense for the other races.

**Comment by SioxGWolf** [comment]
It does nothing to explain the logical illfalliacy! If your gonna limit it in that way then limit it blanketly, and if you can eat N item, and eat a person to store an item, you logically can use a person as an extra backpack in that sense. The solution is to give debuffs and damage to items held in the stomach or limit the stomach storage capabilities in some fashion at that regard. And eating something you can already eat when it's placed on a person is just fact.

**Comment by SioxGWolf** [comment]
The contaimination system and semi digested items are already a start to dissuading using the stomach as a storage medium, so build on that!

**Comment by SioxGWolf** [comment]
And as for, it's illogical on other races, if your gonna be able to eat a person and all the items on them already, then there ya go, that race can eat the item. Either limit what items the races can digest one side, or allow them all to have trash eater on the other, none of  this middle of the road bull.

**Comment by Very-Soft** [comment]
To ace's point, I've seen people use the vore mechanics to store items in their bellies a few times in the past, which is part of why the vore mechanics are as they are now, what with not being able to just drop stuff in tums anymore, and with many items becoming unusable until cleaned.

That said, we already allow people to do this with custom species, and the list of things people can eat is limited enough I think. I'm less worried about people using it to act as a second backpack, since if people were able to abuse it that way, I'm pretty sure we'd have seen that become a more meta thing, and quite plainly, it hasn't. 

I'm just more worried about more people using it as an excuse to vacuum up all the food in the kitchen in 10 seconds. (It'd be super cool if there was like a 15-30 second cooldown on trash eater)

**Comment by SioxGWolf** [comment]
I can confir that food should be a major issue on a vore station. Kinda why I wish to include husbandary, and maybe a cooking bot would be nice... and yes, an insertion delay. Make a blanket object swallowing and just give it a insertion delay... call the insertion delay something like ingestion, force the player to have to wait till their stomach settles, and then they can gulp again.

**Comment by Heroman3003** [comment]
Thats the very point of the limited list of 'edible items', to make sure that nothing of actual potential balance-affecting benefit can be easily swallowed. Trash Eater's list is lenient enough to allow swallowing food whole and a bunch of inconsequential minor items. Plus, if somebody wanted to pull a big powergamer move with vore and storage, its already easy to do, all you'd need is either partner or a monkey (which aren't that hard to obtain, if obscure to). And of course, let's not forget that Trash Eater itself is a 'neutral' trait. Those traits are traits that either have same amount of upsides as downsides (cold/warm blood), negative traits with minimal impact (colorblindness), or traits that exist purely for fluff and/or scenes. And Trash Eater doesn't fall into either of first two categories, it IS a fluff/scene trait.
Existing custom species can already swallow all that stuff in the pool of trash eater, but there are no balance concerns about it.
There was a recent addition of Trash Eater use logging specifically to help track down people who abuse it to delete kitchen counters, but also could be used to help those fears of abuse.
Realism really has never been relevant for scene-based stuff in the first place, as never was staying true to species nature.

In the state we are, some players literally only play Custom Species just to allow themselves to have access to object swallowing via Trash Eater for scene purposes, and otherwise fluff it as regular species. As a scene trait, it doesn't have to make sense. As a non-scene trait its already balanced to prevent any potential abuse with its allowed pool. Why should we limit the options for vore on Vorestation based on "You're not Custom enough to swallow a whole steak to tease a prey"?

**Comment by SioxGWolf** [comment]
I have nothing profound to say to this, so I will keep it simple, I am in agreement on every level.

**Comment by SpadesNeil** [comment]
The answer remains no. We're not allowing all races to have access to the trash eater perk.
