### ISSUE TITLE
[BUG] Xenochimeras are perma-fed on by slimes, even when dead

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#5701]
#### Brief description of the issue

When attached by a slime, it feeds (Which is normal), but all attempts to pry it off fail, even with batons/extinguisher/etc. After death, it's in a permanent loop of feeding on me, and then even after the SLED-209 and Verdi started beating on it, it registered every single discipline as valid... but still continued to feed. It was also completely immune to damage/harm, until Verkister exploded a water bomb.

#### What you expected to happen

Get latched, remove it and survive or fail and die, then reconstitute later.

#### What actually happened

Unable to remove slime, and once dead, it perma-feeds, and ignores all discipline, permanently feeding and immune to damage or tasers.

#### Steps to reproduce
- Be Xenochimera
- Get latched by Slime
- Ded.

**Comment by Huenererschrecker** [comment]
Verdi player here, to put a few things into it. It only might have gotten immune to damage. I'm not entirely sure about that, since the sprite of Nysku (or something else, but most likely her) was blocking the water I was shooting via the chemsprayer. The SLED also had a message of saying that it attacked with a stunbaton, so it might have been the wrong type too. All in all it is a bug tho.

https://i.gyazo.com/404c1048bdfa48a09c862af57a2ffda6.png

**Comment by Novacat** [comment]
I think this was fixed by heroman's fix? Will just re-open if not.
