### ISSUE TITLE
[BUG] Cyborg's are screwed if digested inside a mob

### ISSUE THREAD

**Issue by Rykka-Stormheart** [VOREStation/VOREStation#5770]
#### Brief description of the bug

When digested inside a mob, cyborgs and synthetics, I believe? Are screwed if nobody knows _where_ the mob is. Their posi/mmi brain is indigestible, leaving you "nonfunctional" and stuck inside your predator's body. While this is hot for... a few minutes, it quickly gets boring - you can't call for help, can't get help, etc etc.

#### What you expected to happen

Either die fully as a 'borg, or simply be un-eat-able. Or, barring that, have some method of 'escape'.

#### What actually happened

Get stuck inside a gaslamp gut, unable to do anything, call for help, nada.

#### Steps to reproduce
- Be borg
- Be eaten by 'mob
- Be digested
- You're screwed

####

Other suggestion:
Simply add an option for your MMI/Posibrain to "ping Transcore" or "ping Robotics/Science" with the message "Unit X has been destroyed, please locate brain." This would require giving the brain a GPS, yes, but it lets you be digested and stay in-round.

**Comment by Heroman3003** [comment]
Tbh I think its equivalent to just dying to a mob without being eaten/digested as a borg. If you haven't notified that you're in danger BEFORE death occured, you're just dead and thats it. Your only recovery potential is if someone actively looks for you, and finds your body (or in this case, mob that digested you).

The only issue is that you cant simply ghost out as easily as you can when your body is destroyed into unfunctionality with opportunity to re-enter should it be found and brought back for repairs and/or disassembly into brain.

**Comment by Sebbe9123** [comment]
Necroing this a bit, considering IPC's are usually "expensive machines" wouldn't be the worst idea to make them start off with a deathalarm or something.

**Comment by SpadesNeil** [comment]
We're not giving them a death alarm by default.

**Comment by SpadesNeil** [comment]
Furthermore, I don't understand how this is any different from a regular player. If you get digested by a mob and nobody is around to help you, yeah, you're kind of screwed already.

You can always ghost out of the MMI and quit the round. I don't know how else to fix this problem. I also don't see it as a problem.

**Comment by Shophaune** [comment]
> Furthermore, I don't understand how this is any different from a regular player. If you get digested by a mob and nobody is around to help you, yeah, you're kind of screwed already.
Except 'regular' players can get backup implants, or order death alarms from cargo. Getting them back into the round is pretty much trivial so long as Medical isn't swamped with people, or Science in the case of synthetic 'regular' players. But for a cyborg, to get back into the round without the OOC method of ghosting/respawning (or as you suggested, quitting the round entirely) the mob that digested you HAS to be hunted down, your mind retrieved and then a new body constructed through multiple steps - and sometimes even that bugs out.

Should getting digested as a cyborg be incentivised in any way? Probably not, no, but on the occasions it DOES happen - or on the rare occasion someone actually wants to scene in a way that leads to such - there should be some method of practically getting back into the round. You can't say they're not different from regular characters unless they actually AREN'T different from regular characters.

- sincerely, someone who's been screwed out of an entire round by scening, and whose mind boggles at how anti-fun such a screwing must be if it's not caused by something you sought out.

**Comment by SpadesNeil** [comment]
Hm, then I guess a distress signal verb is fine once the borg is destroyed. Have a console in Science telling the coordinates to retrieve the borg brain. The console blinks when there's an alert or something.

**Comment by KasparoVy** [comment]
Or perhaps a notification on the science radio channel 🤔

**Comment by SpadesNeil** [comment]
No notification on the science channel. That's what a death alarm does.

A console is enough. A death alarm would make it better than what regular players already have.

**Comment by Rykka-Stormheart** [comment]
> No notification on the science channel. That's what a death alarm does.
> 
> A console is enough. A death alarm would make it better than what regular players already have.

Regular players have a death alert, though? That's not "better", that's equal?

A console is a bit harder to implement, I think, than a built-in death alarm?

**Comment by SpadesNeil** [comment]
>Regular players have a death alert, though? That's not "better", that's equal?

Regular players have to have a death alarm implanted, last I checked.

A borg upgrade to do the same thing is probably fine.

Both can use LOOC to ask another player to revive them if the death was due to vore.
