### ISSUE TITLE
SDQL2 delete queries is slow as hell.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#5990]
#### Brief description of the bug
It takes forever for an SDQL2 delete query to process. The server slowly processes the request in order to  not insta-freeze it to allow peeps to continue playing but for stuff like slimes? It needs to be INSTANT to prevent further production.

#### What you expected to happen
Being able to easily delete amber slimes that grow out of control, resulting in a frame rate of 1.

#### What actually happened
Long. Tedious and annoying cause the deleting process runs at 1 frame rate as well.

#### Steps to reproduce
- Grow a sizable amber slime army.
-Attempt to delete amber army via SDQL2 query in the debug tab.
-Stare as you scratch your head in sheer confusion as you watch numbers tick up but nothing seems to be getting deleted.
-Cry.

#### Code Revision
a865b57542af4ee6d4d8cd57f7cd205f814a35e3 
 
#### Anything else you may wish to add:
N/A

**Comment by DemicusMaximus** [comment]
Can confirm: When spiders get out of hand, a SDQL delete command can take up to forty-five seconds to complete, either freezing up the entire server or slowing it to a slideshow while it runs.

**Comment by Arokha** [comment]
Keep in mind when you delete everything of a certain type, it literally checks *every single atom in the world, every turf, every object on every turf, every object inside those objects, every mob, every organ in every mob*, etc, to find the things you asked it to delete. And to prevent this from lagging the server, it pauses to let the round continue instead of just stopping the game for everyone for like 15 seconds. So the added pausing makes it take longer.

You can cut this down by doing things like 'in mob_list' or one of the other global lists in global_lists.dm.
