### ISSUE TITLE
Surface Library Issues

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#6050]
#### Brief description of the bug
No Librarian Spawnpoint landmarks, plural, for 2 max.
No public access to the light switch that turns lights on in the room.

#### What you expected to happen
Spawn in library at roundstart.
Free access to a light switch.

#### What actually happened
Spawn at the tram instead.
Require Librarian access to light switch.

#### Steps to reproduce
- (Step 1) Ready up at new round before it starts, librarian (alt titles) selected.
- (Step 2) Spawn at Tram or wherever instead.
- (Step 3) Go to library.
- (Step 4) Try to find light switch to turn lights on.
- (Step 5) It's restricted behind library access in the private booth.
#### Code Revision
- 384cb4605e5215564230d2f21e4ddb488e4cca2a 
 
#### Anything else you may wish to add:
- New Library is the location for said issues. Also, maybe add a camera inside the Private Study? 🤷‍♂

**Comment by Very-Soft** [comment]
The missing landmarks is an oversight. I'll fix it in a bit.

I don't actually think the lightswitch being restricted behind librarian access is a problem, personally. The library is dimly lit, but it is still lit everywhere except by the bookshelves that spawn with no books in them under normal conditions even when the lights are off thanks to the table lights.

And! The librarian closet lacks a security camera by design, so you can sneak people away into there without people spying on you. There's cameras all around it, so if anyone's breaking in there, you ought to be able to spy them coming in or out.

**Comment by TheFurryFeline** [comment]
From what I've been seeing, the desk lamps don't seem to be casting much of
a glow like I remember them doing at the old library. Unless that's a side
effect of some subsystem changes?

On Oct 13, 2019 23:08, "Casey" <notifications@github.com> wrote:

The missing landmarks is an oversight. I'll fix it in a bit.

I don't actually think the lightswitch being restricted behind librarian
access is a problem, personally. The library is dimly lit, but it is still
lit everywhere except by the bookshelves that spawn with no books in them
under normal conditions even when the lights are off thanks to the table
lights.

And! The librarian closet lacks a security camera by design, so you can
sneak people away into there without people spying on you. There's cameras
all around it, so if anyone's breaking in there, you ought to be able to
spy them coming in or out.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/VOREStation/VOREStation/issues/6050?email_source=notifications&email_token=AJGMTYZUWYJ4ML3MSYLC5RLQOPPB5A5CNFSM4JAEVU4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBDHWTI#issuecomment-541489997>,
or unsubscribe

**Comment by TheFurryFeline** [comment]
Also, if an AI needs to disable some lights, the light switch is out of
view range of the camera closest to it
