### ISSUE TITLE
Bump noms broken

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#6051]
#### Brief description of the bug
Bump noms such as with gas lamps doesn't work.

#### What you expected to happen
To get stunned and eaten almost immediately.

#### What actually happened
I get the eating message but never actually get eaten because the mob typically moves before I get eaten.

#### Steps to reproduce
- Enable bump noms.
- Bump into a gaslamp.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/384cb4605e5215564230d2f21e4ddb488e4cca2a

**Comment by ArgobargSoup** [comment]
Are they knocking you over?  I remember back when I used to mess with gaslamps, due to having a character that could go outside easily, that I could brush through them a lot... like they had a high chance of *attempting* to nom you, but a separate, rare chance of actually pushing you down to keep you still while they tangled you up.

**Comment by SpadesNeil** [comment]
Not even knocking you over. I tried standing right next to it to try intentionally getting eaten but the mob moves before it can finish the vore attempt, which is broken when you move.

**Comment by Razgriz1032** [comment]
Any progress on this?

**Comment by Zeldazackman** [comment]
Still an issue as of ed5431e

**Comment by Shadow-Quill** [comment]
Still a bug?

**Comment by Arokha** [comment]
Works
