### ISSUE TITLE
Vox exhale Phoron and it's kind of a problem.

### ISSUE THREAD

**Issue by AaronSherwood117** [VOREStation/VOREStation#6103]
#### Brief description of the issue
This one kind of went under the radar due to the species not really being played, but Vox exhale phoron over time.  Most of the time, this isn't really an issue, it gets filtered out by the air system over time.  But not all of it.
     If, for some reason, you would find yourself on the same tile as someone or even right next to them for an extended period of time, they end up getting steadily rising toxin damage that's a huge hassle to deal with mid-scene.  Any longer than an hour, and entire rooms can start taking damage if they're unfiltered.
     I don't know what could fix it, but it semi-regularly screws up my personal interactions by trying to kill my partner, and it seems that absorption doesn't even stop them from trying to be murdered by the aura of death.

#### Steps to reproduce:
Be a Vox, get someone alone in a small space, wait thirty minutes to an hour, then check the partner's damage levels.  Or wait until said partner starts puking.

**Comment by Very-Soft** [comment]
nothing better than taking someone feet first and having them puke on the way down mmmn

**Comment by SpadesNeil** [comment]
Vox should proooobably not exhale phoron if they _breathe_ phoron. Otherwise, why should they breathe at all? They should ideally exhale whatever the other races exhale.

Or maybe even exhale oxygen. Isn't oxygen toxic to them? Is it not the byproduct of their respiratory system, or is that just because oxygen itself is dangerous to them somehow?

**Comment by Heroman3003** [comment]
Well, other than in-lore chemical reasons, there really is no issue with them exhaling something else or nothing at all. But other races all either exhale CO2 or nothing to my knowledge. It COULD be set to be any gas we have of course.

**Comment by Very-Soft** [comment]
I don't really see a problem with them exhaling CO2 personally. Doesn't make the air flammable in either oxygen or phoron heavy atmos, and doesn't immediately start poisoning people.

**Comment by Wickedtemp** [comment]
Vox used to breathe nitrogen. Why it was changed to phoron is beyond me. I feel like nitrogen has always made much more sense anyway.

**Comment by KasparoVy** [comment]
Lmao, I felt like it should've been mentioned but also didn't comment because it had taboo vibes. My experience with Vox in SS13 has generally been with nitrogen.

I mean I thought it was extra hardcore they somehow breathed phoron in Polaris code but nitrogen was the OG for me.

Still, I figure changing them from nitrogen would mega cheese people who enjoy that aspect and it'd be a much more positively impactful undertaking to switch the exhalation breathtype

**Comment by SpadesNeil** [comment]
I think breathing Phoron has a bit more flavor to it lorewise. I don't want them breathing nitrogen now that we have them using phoron.

They should not however **exhale** fucking phoron.

**Comment by Novacat** [comment]
So I looked into fixing this, unfortunately due to the very complex way breathing works, there is no easy fix.

Basically, when you inhale a gas, your body only consumes 1/6 of that gas, so even if I give Vox an exhale-type of a different gas, only 1/6 of the exhaled gas would actually be that gas type, while the remaining 5/6 would be Phoron, still.

The only way I can fix this is by either changing how Vox breath, which would require a lot of snowflake code, or changing the gas that Vox breathe.

**Comment by Wickedtemp** [comment]
...Could probably change it to nitrogen and it'd be fine, given that the atmos is mostly nitrogen anyway

**Comment by Arokha** [comment]
I should have just read Ascian's comment since it would have saved me the time of discovering the same thing! But, basically, 'what he said'.

You convert 1/6th of the gas your species uses into your exhale type per breath (which means you DON'T convert any nitrogen unless you breathe nitrogen, etc). It's semi-realistic... though it's not particularly realistic to convert 1/6th *regardless of amount*. Humans can't spontaneously process more oxygen if they're breathing 100% oxygen (and will actually develop poisoning from it).

But, yes, what he said. This would probably be difficult to fix. Vox technically exhale CO2 like humans, but also like humans, only convert 1/6th of the ~~oxygen~~ phoron they inhale to CO2. You could add a species breath conversion rate or something that adjusts what ratio (like 1/6th) you convert to your exhale type, but then people would just get CO2 dizzyness messages instead most likely! And it might cause problems with their tanks running out faster? I'm not sure if exhaled air goes back into tanks or is just deleted or how that works.

They could just be made to breathe nitrogen again, though that takes away like the only interesting part of their gameplay (that the normal station atmos is hostile to them), and if that's removed they're basically just a resprited every-other-species so that seems dumb.
