### ISSUE TITLE
Allow fluff items to be changed by Github.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#625]
#### Brief description of the issue

Manually typing in fluff items through the command prompt is **not fucking practical.** Can we just remove the custom items text thing from git ignore? I do not know how to do that though.

Whitelists for aliens should also be included.

**Comment by Arokha** [comment]
Originally it was ignored because we wouldn't want forks ending up with all our custom items, but there's another good reason not to.

It's pretty meta, tbh. If the list is public, then you know that X always has item Y, whereas right now the fluff approved/denied requests are hidden on the forums so who knows.

Like you could tell that someone probably has a concealed taser/stun revolver/laser/whatever without them ever having shown you.

**Comment by SpadesNeil** [comment]
Actually approved and denied item requests are not hidden, or they shouldn't be. So, this is a somewhat moot issue.

**Comment by JoanRisu** [comment]
Back to the issue at hand, 

WEH, I really do need access to that list of items.

**Comment by Screemonster** [comment]
If someone can code-dive all over the github for the list they can browse the forums just as easily. If nothing else, making the .txt public would make it a lot easier to dismiss the "so many snowflakes with so many guns" bullshit arguments that crop up from time to time as we could just link them to the .txt and point out how few weapon permits and weapons there actually are.
