### ISSUE TITLE
DogBorg Pounce has No Functionality

### ISSUE THREAD

**Issue by Damarik** [VOREStation/VOREStation#6296]
Brief description of the bug
Pounce Feature on DogBorgs has no function.

What you expected to happen
Equipped the Pounce Feature on my character. Went into Aggressive intent. Clicked on target. Expected mob-like pounce attack with knockdown.

What actually happened
Nothing happens.

Steps to reproduce
Follow steps above to repeat.

Code Revision
1904e1e365d0e382ca11a925ef1d616f18d484f1

**Comment by Verkister** [comment]
I wish I could make the pounce mechanic work llike the way you attempted to use it, but due to extensive feedback it was made to be activated by approaching within 3 tiles from target, then pressing the pounce icon itself, and then selecting the target from popup, and even then the knockdown chance would only be 33%. Hell I'm all for buffing the crap out of that _entirely useless_ mechanic.
