### ISSUE TITLE
Cryo-ing/teleporting/elevator-ing/etc doesn't free job slots.

### ISSUE THREAD

**Issue by cthuloid9** [VOREStation/VOREStation#631]
Like the title says, cryo-ing and it's equivalents don't seem to free job slots.

The manifest listed only one chemist, yet I couldn't join as chemist. After asking what was up, I was told the problem was job slots not being freed. I thought it might've actually just been the HoP, but checking the available jobs showed it had also happened with the HoS slot, which meant that wasn't the case.

The easiest way to recreate it would be having someone take a head role, then cryo, I guess. Or for my specific case, take two chemist slots.

Edit:
Server revision: release - 2016-10-02
71dcaf6

Also, to clarify, I was told it's because of a bug with cryo/etc in ooc and was told to make it an issue after seeing there wasn't one already, so I'm not completely sure that cryo is the issue, it's only what I've been told.

**Comment by SpadesNeil** [comment]
Missing server revision. We need to know that so we can know if this has been fixed or not on a newer version.

**Comment by Screemonster** [comment]
Strange. List Free Slots pretty clearly shows "Chemist: 2" right now, but I couldn't join as one and the Free Job Slot menu shows chemists. So let's...
ADMIN LOG: A job slot for Chemist has been opened by Scree/(Scree)
List free slots now reads "Chemist: 3"
Join menu now shows "Chemist (2) (Active: 0)"


Server revision: release - 2016-10-02
71dcaf6e10554a5c268e4c26ace4236681ad4969

**Comment by Screemonster** [comment]
However, while this was all going on, the CMO went into cryostorage and it freed the slot correctly.

**Comment by Eearslya** [comment]
Okay, well, for starters..I looked into this, and it irks me deeply. Every job has two variables, `current_positions` to track how many people **have** that job..and `total_positions` to track the maximum number of people who should have it. It irks me because cryoing does not *subtract* from `current_positions`, but rather *adds* to `total_positions`...

That being said..As stupid and backwards as that implementation is..it should work, and has worked as long as I've been playing.. I can't figure out why this is happening, unless there was another outside force that messed with it (like a job reassignment).

**Comment by SpadesNeil** [comment]
Is this still a problem?

**Comment by Arokha** [comment]
Probably not a problem, and I'm merging code that fixes job slots for prey in mobs who are cryoing too. So. Definitely super not a problem at that point.
