### ISSUE TITLE
WereBeast Front sprites with have wings appear over their arms.

### ISSUE THREAD

**Issue by H0lySquirr3l** [VOREStation/VOREStation#6329]
#### Brief description of the bug
Werebeast's will have wings appear on top of their arms in their front faceing sprites.
https://cdn.discordapp.com/attachments/638585470770479106/656358844607496223/unknown.png
https://cdn.discordapp.com/attachments/638585470770479106/656359406757478410/unknown.png
#### What you expected to happen
For your werebeast's wings to appear on their back.

#### What actually happened
The wings appear on their front not being blocked by the arms of the sprite.

#### Steps to reproduce
- Make a werebeast.
- Add wings of any type.
-

#### Code Revision
- release - 
b9118b58b6d29bb51d679ae55945359c351d97cd 
#### Anything else you may wish to add:
- https://cdn.discordapp.com/attachments/638585470770479106/656358844607496223/unknown.png
https://cdn.discordapp.com/attachments/638585470770479106/656359406757478410/unknown.png

**Comment by Verkister** [comment]
Yeah this is due to the fact that nobody here has yet ported the separate layers system for front and back tail/wing icons so wings and tails both are currently on a layer above the body with the front sprites just having a regular human shaped silhouette cut out and the werebeast body doesn't quite fit that hole
