### ISSUE TITLE
[Oversight] Unmutable Merps, etc.

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#6332]
#### Brief description of the bug
Had a complaint happen during a tram ride last night about not being able to mute the sound outputs that happens when some people take a fancy to fill the trip home to Central with awoos and the like. We have mutes for weather sounds, digestion, and eating, but not for these recently added palooza of noises.

#### What you expected to happen
Mute merps and awoos.

#### What actually happened
Get blasted with spammage on the tram ride.

#### Steps to reproduce
- (Step 1) tram trip
- (Step 2) hear awoos
- (Step 3) look for mute option in Preferences tab
- (Step 4) endure the whole ride to Central as people Awoo like madman, praying you don't join and snap.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Wickedtemp** [comment]
I know that some folks in Discord weren't fond of this, but the last several round-ends Ive been on for, I had to mute my computer because of the sound spam of 20+ people.

**Comment by KasparoVy** [comment]
I really enjoy the sounds (making and hearing them is a good laugh) but totally understand where folks are coming from in theoother angle. I agree with a pref that'd shut me up to those who don't like it

**Comment by Wickedtemp** [comment]
It's not an issue with one person, either. Just when 10+ people are in a group doing it so its a constant stream of noise even with the short 'cooldown' that using the verb has. It completely destroys the chatbox, too, which can really suck when I'm still trying to RP or talk to someone. A few times, we've had injured people on the tram. I can't really even talk to them much of the time because the chat spam is too much to follow. Did they want treatment, did they not care, did they get irritated at me for treating them, I've no idea because the chat was flying by due to constant emotes.

**Comment by Sebbe9123** [comment]
Muting emotes will not change the change the chat bar

**Comment by SpadesNeil** [comment]
##M E R P

**Comment by KasparoVy** [comment]
> ### M E R P

NOW you're speaking my language

**Comment by KasparoVy** [comment]
Bollocks
