### ISSUE TITLE
HV Death, Resleeving Sickness Oversight

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#6569]
#### Brief description of the bug
Seems that hard vore mechanics are not counted towards vore related deaths that lets you avoid resleeving sickness.

#### What you expected to happen
No resleeving sickness after an HV scene results in organs removed from a vital area.

#### What actually happened
Death, resleeving sickness on resleeve.

#### Steps to reproduce
- (Step 1) Target brain with HV
- (Step 2) Watch prey die
- (Step 3) Resleeve them.
- (Step 4) They get resleeving sickness.

#### Code Revision
- ff00f4280fbdbe5faf91b4328669dfdf8e539d11 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Screemonster** [comment]
aside from using a _second_ status condition that's inflicted upon people by hardvore mechanics with the effect of "for x time, assume death is directly caused by this vore action", I can't think of an easy way to do this.

The only way to powergame with it would be to have the explorers all bite each other and patch themselves up before combat, which would be not only obvious and detectable, but also hilarious.
