### ISSUE TITLE
Cloaks do not appear on my character sprite.

### ISSUE THREAD

**Issue by JoltDerg** [VOREStation/VOREStation#6598]
#### Brief description of the bug
I join, seeing that my cool green cloak suddenly becomes invisible, despite wearing it.

#### What you expected to happen
I expected for my cloak to be actually visible.

#### What actually happened
It turns invisible, even in the character creation screen.

#### Steps to reproduce
- (Step 1) Wear a colourable cloak
- (Step 2) Join the game

#### Code Revision
- 21531a84075ded32664da8521bcd8162e1ac7a09

**Comment by JoltDerg** [comment]
I found a work around, actually. You can wear the cloak on your uniform.

**Comment by Leshana** [comment]
* This runtime is caused by equipping /obj/item/clothing/accessory/poncho/roles/cloak/custom into suit slot.  
  * It is not an /obj/item/clothing so it shouldn't be equipped there; you can't equip it there in game, it only goes there in  preview because it forces it (probably because it DOES sort-of go there if you ALSO are wearing a suit it can attach to)
* So the real root cause is wearing a non-suit in suit slot.
* Nonetheless, would be good if update_inv_wear_suit() would be robust to this case.
```
[2020-02-24T13:21:39] Runtime in update_icons.dm,784: undefined variable /obj/item/clothing/accessory/poncho/roles/cloak/custom/var/taurized
  proc name: update inv wear suit (/mob/living/carbon/human/update_inv_wear_suit)
  usr: (NULL) (0,0,0) (NULL) (ckeyhere)
  usr.loc: (NULL) (0,0,0) (NULL) (ckeyhere)
  src: Mob Name (/mob/living/carbon/human/dummy)
  src.loc: null
  call stack:
  Jolt Vehze (/mob/living/carbon/human/dummy): update inv wear suit()
  Jolt Vehze (/mob/living/carbon/human/dummy): equip to slot(the cloak (/obj/item/clothing/accessory/poncho/roles/cloak/custom), 14, 0)
  Jolt Vehze (/mob/living/carbon/human/dummy): equip to slot if possible(the cloak (/obj/item/clothing/accessory/poncho/roles/cloak/custom), 14, 1, 1, 0)
  Jolt Vehze (/mob/living/carbon/human/dummy): equip to slot or del(the cloak (/obj/item/clothing/accessory/poncho/roles/cloak/custom), 14)
  /datum/preferences (/datum/preferences): dress preview mob(Jolt Vehze (/mob/living/carbon/human/dummy))
  KeyHere (/mob/new_player): Topic("src=\[0x3000045];observe=1", /list (/list))
  KeyHere (/client): Topic("src=\[0x3000045];observe=1", /list (/list), KeyHere (/mob/new_player))
```
