### ISSUE TITLE
Dogborgs cannot digest/clean

### ISSUE THREAD

**Issue by DemicusMaximus** [VOREStation/VOREStation#661]
#### Brief description of the issue

Dogborgs have the self-clean feature for their bellies. It is not working at all, on either medihound or K9.
#### What you expected to happen

People to go gurgle :P
#### What actually happened

Nothing at all.
Tried manually turning it on via vars, nothing happens.
#### Additional info:
- **Server Revision**: release - 2016-10-10
  7657fab851dc0886c2beba788ee4538793ddf08a

**Comment by Arokha** [comment]
I'm able to digest people with both the current github master code and I spawned a medihound and tajaran on the current server and was able to digest the taj with the medihound.

**Comment by SpadesNeil** [comment]
Marked as "cannot reproduce". Will close unless it can be reproduced reliably.

**Comment by Arokha** [comment]
I can throw out some things to check next time you see this:

- Does the person have digestible set? Double-check them on VV. It should be "digestable = 1".
- Did the dogborg use 'normal' vore rather than the sleeper? This isn't supported. VV them, then drill down into their sleeper module item, and look at the contents. Ensure the person is in that, NOT in the dogborg's contents itself.
- Is the person being digested a synth? Brute/burn/oxy/tox values won't rise on synths, but you can look at the 'Total Health' value decrease. This might be misleading to some.

**Comment by DemicusMaximus** [comment]
I have no idea. Tried it a dozen times with many combos, WOULD NOT WORK. And now it's working fine. Seems to have fixed itself, or had some other variable I cannot reproduce.
