### ISSUE TITLE
Examine icons for characters in chat are :b:roke

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#6737]
#### Brief description of the bug
Examine preview that showed basic shape of character in chat isn't functioning

#### What you expected to happen
Small silhouette of character appears next to their name

#### What actually happened
Weird grid thing

#### Steps to reproduce
 - Examine a humanmob

#### Code Revision
- ae16f6afb928528ed0e3161085c33211be42a6e6 
 
#### Anything else you may wish to add:
- http://prntscr.com/ra2qmv

**Comment by Arokha** [comment]
Prior to the 'weird grid thing' it was just a naked human. Is this really the first report of this issue? It's been broken for months.

**Comment by Heroman3003** [comment]
I mean, it was a naked outline of whatever character is is, for me at least. it was only broken with taurs who had bottom cut off.

**Comment by Arokha** [comment]
Yaya. I didn't bother fixing it in vchat because it was already broken and unrelated.

The grid is for animated tails, if they have a tail animation going, that's every frame in the animation.

**Comment by Arokha** [comment]
Probably needs a rewrite of how get_flat_icon handles humans. Or just a proc on humans that it calls to do it's work.

**Comment by AegisOA** [comment]
Regarding this, I think it might have **improved**, but it hasn't been entirely fixed yet. I don't think I've gotten the grid thing happening in a while, but, instead, I think it picks the sprite of the first person you've examined in a shift, maybe? For example, I examine some folks after joining, and then examine myself; instead of myself, the sprite depicted in the logs is a demon I examined previously.
