### ISSUE TITLE
[Feature] VChat logging system doesn't continuously save

### ISSUE THREAD

**Issue by Tename** [VOREStation/VOREStation#6757]
#### Brief overview of the feature
Add support for continuous logging in Vchat.

#### What you want to happen
Add the same functionality included in the old system for continuously saving logs so you don't have to wait till round end to export history.
 
#### Anything else you may wish to add:
https://github.com/Yawn-Wider/YWPolarisVore/issues/633#issue-575908772

**Comment by Arokha** [comment]
Not possible to implement. VChat, Goonchat, and other chat 'overhauls' are using Internet Explorer because that is what Byond allows us to use. Internet Explorer cannot continuously update a file on your computer, so as far as I'm aware, there is no way to ever implement this. Goon gave up on doing it, and I have too.

If anyone ever figures out a way, we would want it. But I doubt it's possible.
