### ISSUE TITLE
[Suggestion] While westill have super devs, please fix sound

### ISSUE THREAD

**Issue by Sebbe9123** [VOREStation/VOREStation#6771]
#### Brief description of the bug
You can hear sound from one end of the Z level to the other end, through walls, barriers, even Joanna's ass.

#### What you expected to happen
Walls to muffle like it does on any other station

#### What actually happened
The station acts like a house built in the late 1600's

#### Steps to reproduce
- (Step 1)turn on a shower
- (Step 2)go to research 1/the bar,
- (and so on)

#### Code Revision
c0708dbb0c25ff4445d098d5bd3c93d6d69117b5 
 
#### Anything else you may wish to add:
plz, I'll trade NSFW favors for fixing this

**Comment by Sebbe9123** [comment]
> Turn on a shower where?
> 
> Also, to note, shower loop is rather long and _stacks_, similarly to some other soundloops. So it might be that you just have a bunch of stacked sounds of same loop playing simultaneously and still haven't finished playing as you left (only with more quiet versions beginning to be queued in)

Please read the issue before commenting.

**Comment by SpadesNeil** [comment]
>Please read the issue before commenting.

Please provide information that is important to resolving the issue. ¯\_(ツ)_/¯

**Comment by Leshana** [comment]
I just checked, we already have support for sounds being blocked by walls, but it is on a sound-by-sound basis, so it depends on exactly which sound.  Quick check of /tg shows most sounds go thru walls but a few don't.  Interesting idea to go thru stuff and work on this tho.

**Comment by Rykka-Stormheart** [comment]
This is a bit more complicated than is possible to do - Aronai explained that basically if we set it so all sounds checked if there were walls between sound and mob, there'd be a huge increase in server CPU usage.

However, there is a method to just set IGNORE_WALLS to FALSE for specific sounds - muting the shower so you don't hear it through a wall, or just increasing the sharpness/falloff of a sound.

I'll be looking into it, Aronai was super helpful in explaining how it all worked and *gently* nudging me away from the idea of just setting `IGNORE_WALLS = TRUE` because that tends to be a bad idea and there's better ways to do it.

<3 @Arokha if you can tag this "more complicated than you think"?
