### ISSUE TITLE
Floorlength Braid hair broken

### ISSUE THREAD

**Issue by SariNeruda** [VOREStation/VOREStation#685]
Brief description of the issue
Floorlength braid hairstyle showing as "Cat" ears

What you expected to happen
For Floorlength braid during character creation / mirror selection

What actually happened
got cat-like ears

Steps to reproduce
Select Floorlength Braid from Character Hairstyles or a mirror menu

Additional info:
Meow?
release - 2016-10-22
6f3cb6bf7b33650a94068197e238f07f546e9567

**Comment by ArgobargSoup** [comment]
Was able to recreate the bug, and fix it, at least on my test server.

https://github.com/VOREStation/VOREStation/blob/master/code/modules/mob/new_player/sprite_accessories_vr.dm#L38

`icon_state = "hair_braid_s"`
This here is what's causin' the bug.  I think the player renderin' code appends a "_s".  Since there's no "hair_braid_s_s" icon in the file, it defaults to the sergal ears instead.

Changin' it ta
`icon_state = "hair_braid"`
fixed it.

**Comment by Cameron653** [comment]
Ack, I've tried to fix this multiple times but it seems broken every
update. I'll look into this later.

**Comment by Cameron653** [comment]
Fixed in the Polaris sync.
