### ISSUE TITLE
useing the succumb command in a gut cuases full resleveing sickness

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#6889]
#### Brief description of the bug
title

#### What you expected to happen
not to have resleveing sickness form scene, or for dislikeing sitting there unable to emote for ages

#### What actually happened
get resleveing sickness

#### Steps to reproduce
- (Step 1) get digested
- (Step 2) use succumb command
- (step3) you feel week and disoranited+ message saying when you are better later
 
#### Code Revision
f9ed138687ee6ca130a7c11cd3601319e8a03781 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
f9ed138687ee6ca130a7c11cd3601319e8a03781

**Comment by Arokha** [comment]
I tested this and it worked using the succumb verb. If I had to guess, it was because the predator didn't have the belly set to digest mode, which is the only mode that is considered as causing vore deaths. So if you were injured by digestion or other means, and then put in a belly on Hold or some other mode, and used succumb, it would not count as a vore death.

If you think this should be changed, you can suggest it on the forums or discord.
