### ISSUE TITLE
Resting animation glitching (potentially VChat performance thing?)

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#6934]
#### Brief description of the bug
Resting animation has extremely low FPS

#### What you expected to happen
Smooth rotation resting

#### What actually happened
Standing -> 45 degrees -> resting. Just those three frames and nothing else.

#### Steps to reproduce
- I just kept resting and unresting and coulnt see any frames beyond three mentioned. Sometimes even halfway through one didnt appear.

#### Code Revision
- 735f447ad4dcd4749163132cd6936f3fa49ade4e 
 
#### Anything else you may wish to add:
- Might be a performance issue related to VChat printing a message at same time animation is playing? Possibly.

**Comment by Heroman3003** [comment]
Extra note: seems to happen to any ingame animation when it happens at same time as message being printed into the chat.

**Comment by Arokha** [comment]
Is this on a laptop or something? Or a desktop with a graphics card? I mean it's possible if the hardware is insufficient you get dropped frames because of that it can't keep up with drawing a message AND transforming a sprite at the same time, otherwise I'd think it's just byond being awful at handling anything.

**Comment by Heroman3003** [comment]
Desktop and it usually can handle most things just fine. Probably mostly a byond thing.
