### ISSUE TITLE
Feedback: The pilot job is stupid and shouldn't exist

### ISSUE THREAD

**Issue by nerdass** [VOREStation/VOREStation#7199]
Just make it an alt-title of explorer and let any explorer fly the shuttle regardless of whether they're wearing the tag, because all it is is a fluff title and explorers fly the thing 9 times out of 10 anyway

**Comment by nerdass** [comment]
also pretty much everyone on the station says they own their own spaceship so yolo

**Comment by Novacat** [comment]
Explorers cannot fly the shuttle, I removed their access to the shuttle control consoles months ago, and, usually, most expeditions have either the pilots flying the ship, or the Pathfinder if there is no pilot.

**Comment by nerdass** [comment]
so you're saying the justification for the job existing is because of access restrictions on a single computer

**Comment by nerdass** [comment]
like i'mma be real with you here, the job has no reason to exist, the access restrictions have no reason to exists

right now it's a job that's only there because "this thing should be here" rather than having an actual reason. it isn't even a station job, his job is literally to leave, like, what's the point of that it's dumb. the entire idea of it being its own job is dumb. just patch it into explorer and get rid of the artificial difficulty created by having someone have to draw the short straw of spending the expedition sitting in a goddamn chair

it's stupid. this is stupid. make it a sub-title.

**Comment by nerdass** [comment]
oh and if the pilot participates in the exploration, they are an explorer, so, cut out the middle man

**Comment by SpadesNeil** [comment]
The pilot is artificial difficulty. It exists only to prevent anyone else from doing it. There is no skill the job requires.

The only other job on the entire station that is like that is janitor, and that's the way it is so everyone can't raid all the space cleaner.

The shuttles that the pilot can fly are already locked behind the doors of their departments. There is zero reason that any department should be required to find a pilot to use their own things.

**Comment by KasparoVy** [comment]
> also pretty much everyone on the station says they own their own spaceship so yolo

Not being a space-hobo or taking public space-transit mmmmaaaannn

**Comment by Very-Soft** [comment]
I would prefer if the pilot was more an alt title of intern or such, personally. (Since I would still like it if we removed explorer as a job) That way people can know that you are interested in or skilled at doing piloting. 

I think the shuttle consoles themselves should not have access restrictions on them, but the doors should have the access restriction of whatever the department is. 

That way if you want to be medical's pilot, medical can give you medical guest pass, or go open the door for you, and you can go fly. 

Pilot is not a -station- job. It only has a function when you're leaving the station, so I don't actually think it needs any special access, and should generally not be -required- to use equipment that is a part of a department.

**Comment by TheToaster98** [comment]
As someone who basically mains pilot, I think I should add my point of view, so here I go.
I don't even know the purpose of many of this comments, seems just the cries of people that got either shush away from exploration once or twice, or didn't try it at all, but still need to keep pushing it forwards.

> The pilot is artificial difficulty. It exists only to prevent anyone else from doing it. There is no skill the job requires.

Please delete medical, the medical system is added dificulty and there is no skill needed to resleeve someone.
Now seriously, pilot is given something to do apart of "haha button go CLICK", a previous serious concern of people, now is regarded as "artificial difficulty"
Apart of the initial fuckups of people experimenting, we haven't suffered anything that makes me think "oh man, this is SO DIFFICULT", but what do I know? I **only play the job.**

**Comment by TheToaster98** [comment]
> Pilot is not a -station- job. It only has a function when you're leaving the station.

Currently, a good pilot will join efforts with science and/or engineering for more phoron to fuel the shuttle, for materials in case the hull/ windows get damaged, for a new cannister of air mix for the airlock.
If you also like being extra, with mining/cargo for more tritium to power the PACMAN in the shuttle.
Last time I checked, those things were in station.

> like i'mma be real with you here, the job has no reason to exist, the access restrictions have no reason to exists

As far as I know, it was originally there to stop XxX__C00lExpl0RER__XxX of going to V4 and be wiped in five seconds because they thought we are CM...oh wait, you are right, we don't need the access anymore because the "**artificial difficulty**" will keep them away.
I am always open to keep talking, here is my discord! TheToaster#4749

**Comment by nerdass** [comment]
yeah but those departments are all allowed to fly their own shit, pilot only exists because it's flavor for exploration.

it's like some people who play doctor just so happen to be nurses. if a job needs a map change and a lockout added so that ONLY THAT JOB can do the thing, then there's really no reason to keep the job. the only thing that justifies the job right now is an access requirement, and that's stupid.

**Comment by nerdass** [comment]
and i can already see the cry of MAKE DEPARTMENT SHIPS NEED PILOTS TOO no, fuck that.

are we gonna add medical pilot, mining pilot, engineering pilot, security pilot? 

do we need a cargo pilot to push the button that summons the supply shuttle?

it's legitimately the dumbest fucking job on the station, i'd throw it up there with clown and mime but at least they serve the purpose of being the best goddamn person to give the nuclear authentication disk.

**Comment by nerdass** [comment]
also BUT MUH CHARACTER HISTORYYYYYYY

you would still be able to label yourself as a pilot, you'd just click a different button on character spawn, and if your coworkers aren't dicks, they'll let YOU be the one who flies the shuttle.

**Comment by TheDavestDave** [comment]
I think we've added mechinaces to accaully flying the exploration shuttle now. This is a recent thing it used to be press a few buttons and done. Now it needs fuel and accaully driveing using 2d kerbal physics or something. I've not had a chance to play with it. Pilots are one of the few people who can use the teather back up shuttle when the lifts breaks, granted they are often off station flying the real shuttle every time it happens.

however when the job was first introduced it was basicly the cargo  shuttle for driving. Existing to stop admins having to deal with a explorer running away by himself round start, instead of telling them off or job banning them.

to bring medical up as an example people would be upset if only chemists could do chemistry. We don't call nurses who use the lab power gamers ethier. We don't have coded ways to stop people breaking into to chemistry to power game we bonk them instead.

**Comment by Runa-Dacino** [comment]
Why exactly are we hating on pilot? Does removing it bring anything to the server?

**Comment by SpadesNeil** [comment]
Yes. Explorers no longer have to obtain one specific person just to perform one singular role.

It would be far less bothersome if we got rid of pilot and let explorers fly their own ship. The other ships on the station which also require a pilot would also no longer be barred behind allowing only one person to access it when many different people and departments also have need of that role.

We discussed this not long ago in Discord when we were talking about removing Exploration, but while people provided a lot of support for Explorer and Pathfinder, the mood around pilot was almost entirely negative.

No other job in the server or its history is so simultaneously necessary and yet exclusive in its role and function. Pilots fly the ship. They don't get to do anything else. If there is no pilot, then explorers can't do anything.

Removing pilots and allowing explorers and other departments to fly _themselves_ around is beneficial rather than keeping pilot.

**Comment by SpadesNeil** [comment]
Imagine if the Janitor was **required** for medical to function because the janitor had to disinfect the medbay at the start of every shift. Now imagine that was the only thing they did.

Or imagine engineering's job was to start the engine, but nothing else. No atmos, no construction work, no tinkering with the engine to optimize it, no repairs... start the engines and log off. Now imagine they had to sit there and monitor the engine for the entire shift.

That's a pilot's life. I'm sure a handful of people are content with this. This is the first time I have seen _any_ support for pilot anywhere, and the argument amounts to "BUT WHAT ABOUT-" and that's not a very good argument.

**Comment by MrSign** [comment]
With the additional of ACTUAL piloting being implimented. Y'know, working with grid co-ordinates, avoiding asteroid fields, etc. I'd say pilot should still be a thing. Perhaps, not exactly an EXPLORER MAIN thing but considering we have a tour bus, they should be able to participate  in a lot of activities. Whether it would be ferrying explorers or a bus of 'tourists' to Virgo 4 or assisting medical by piloting the medical shuttle while the doctors focus on stabilizing patients from an expedition. I'd say there still a lot of  opportunities to allow the title to remain as a 'specialised' job.

**Comment by Screemonster** [comment]
Once we get more shuttles, I can't wait to see the departments that have them be unable to use them because only one person joined as pilot and now everyone has to fight over who gets the person to fly them around.

Pilot is helping engineering build a space fort? Well tough shit exploration, guess you're sitting idle this shift because an entire section of the game that large numbers of players want to participate in is gated behind a single job that someone may or may not bother to join that shift.

The only way around this that I can see is giving each department a keyfob (essentially an ID with pilot access on it) that lets them take the department's shuttle out without a designated pilot, in which case... why bother having a separate pilot role?
That, or we make the department shuttles just need that department's access, in which case... why bother having a separate pilot role?

The only real reason to keep "pilot" as a role in and of itself is if we also do away with "explorer" as a role and go back to away teams being composed of people recruited from other departments - which isn't something I'd be opposed to either, but we were planning on keeping Pathfinder at the very least as an expedition lead anyway, so the pathfinder can just hand out access to the expedition shuttle to whoever wants to fly it that shift.

**Comment by Joannabonana** [comment]
Que no los dos? 

I dont see a particularly good reason as to why we cant have a pilot job as well as other shuttles. As it stands right now, the departments that need shuttles have access to them, and the pilot is a great fluff job. We arent actually going to start pruning fluff jobs because they dont actually serve a practical purpose right? 

If and when we get an overmap, there can be some more discussion on how exactly a pilot should be seen on the station and how they should work, but as it stands now, why not just have the pilot job? I think that Scree's suggestion is fine, but removing a job solely for the fact that it seems pointless is a bit of a slippery slope.

**Comment by Screemonster** [comment]
I'm absolutely fine with pilots staying as a job that can join and is effectively in charge of the tour bus and _can_ help other departments out with flying shuttles, but I'm not cool with them remaining in a way that gates those departments behind them existing.

**Comment by TheDavestDave** [comment]
chemistry is needed for medical to work. No one complains if a nurse does chemistry. Mostly because we bonk the chemists that do that

**Comment by Screemonster** [comment]
> chemistry is needed for medical to work. No one complains if a nurse does chemistry. Mostly because we bonk the chemists that do that. We also don't code the nurse away from doing chem

That's the issue, right now people _are_ coded away from flying the shuttles without a pilot. I have no issue with pilots existing in the same way as chemists - as in, it's their job and they should be allowed to do it, but if one isn't available it's not the end of the world and you're allowed to do it yourself.

**Comment by SpadesNeil** [comment]
Literally I would be fine with what Scree just described.

Pilots as they currently are, they are not fun.

A key fob was discussed previously as a solution for removing pilots yet preventing every jackass on the station from being able to fly the ship. Basically, it's a role you get assigned rather than a role you start with, and your "access" is merely having the keys. Obviously there'd be a spare set of keys in case someone ~~gets gulped~~ vanishes mysteriously.

**Comment by TheDavestDave** [comment]
keep shuttles to department access. Seems easier than makeing 100 fobs for ships all the time

**Comment by SpadesNeil** [comment]
Then we can't have ship hijacking shenanigans, which could conceivably be great fun.

**Comment by TheDavestDave** [comment]
what if you stole an id to hijack it? Or gave yourself access

**Comment by SpadesNeil** [comment]
Both a lot more difficult than stealing a key. When's the last time you managed to steal an ID off someone's person without killing or eating them? Probably never.

Key fobs would only apply to keys on station. Event shuttles like the trader shuttle would keep hard coded access because we don't want players flying it.

**Comment by SpadesNeil** [comment]
Alternative solution is _no access required_ for the flight computer. No key fobs, no shit like that, just access to the easily hackable door.

Actually I think I like that a lot better. Access restrictions will remain on event ships for the same reason as I said earlier. We don't want players piloting _event_ ships, typically.

**Comment by AmayaWah** [comment]
We have an overmap system! You can actually pilot a ship. It is kind of important that you have a person specialized for that role. In terms of serving the fluff, the job does incredibly well. 

You can have department specific access. Ship hijacking can still happen easily. You can _assign access_ to every one of the ship computers, like you can with doors.

 Also opening suggestions like this on github is a bad idea. :v

**Comment by Screemonster** [comment]
Yeah, this should really be on the forum if anything.

**Comment by SpadesNeil** [comment]
Ay yo someone link the forum thread then lock this pls
