### ISSUE TITLE
Synth Speech Bubbles Switch to Organic After Typing

### ISSUE THREAD

**Issue by KasparoVy** [VOREStation/VOREStation#7546]
#### Brief description of the bug
Since the new speech-bubble changes, while the speech bubble correctly appears as the synthetic one (while typing), the moment you actually send the message it switches to the organic normal speech version.

#### What you expected to happen
I expected my robot voice.

#### What actually happened
It looked like I was going to speak in a robot voice, but then I did a great human impression.

#### Steps to reproduce
- (Step 1) Type and witness the synthetic speech bubble
- (Step 2) Send message and watch it switch to the organic speech bubble

#### Code Revision
- 224a2f14ad055053bb327cfccbd5a775b188a14c
 
#### Anything else you may wish to add:
- I was a full body synth -- my head was DSI-Sergal but everything else was ward takahashi spirit or xion-whiteout or cyber-solutions wight. I also had all synthetic internal organs selected

**Comment by Arokha** [comment]
Did you or someone else remove your uniform or suit while you were talking?

**Comment by KasparoVy** [comment]
Oh hey, yeah good point! I was wearing a poncho and my voice was normal-- without any suit it's synthetio. Alright, if that's working as intended I guess feel free to close. I figured a synth voice is a synth voice no matter how it's obscured

**Comment by Arokha** [comment]
It has to do with whether you LOOK synthetic or not (since that's all I have to go based on in terms of synths being deceptive). I assume synths that look lifelike have lifelike voices.

Whether you look lifelike or not has to do with if you're a lifelike model, and if you're undamaged enough that people can't see your internal bits. But it ALSO has to do with the make/model of your head and torso. Mainly torso, but if that's not visible, it uses head instead. So that's why.

But yas that's basically as intended unless someone wants to come up with a better option like a var on voiceboxes that makes them lifelike or not or whatever.

**Comment by KasparoVy** [comment]
Thanks @Arokha my bad, I appreciate the explanation
