### ISSUE TITLE
Expensive Taste eating sheets below the character.

### ISSUE THREAD

**Issue by Nomium** [VOREStation/VOREStation#8102]
#### Brief description of the bug
Using the trait Expensive Taste on a sheet of material ignores ones character sprite and picks up other sheets of same material from the ground and consumes all of it instantly.

#### What you expected to happen
To just eat one sheet that I had in my hand

#### What actually happened
I had grabbed some titanium sheets and too one of them into my hand, dropping the rest of the stack below me. I proceeded to eat that one sheet of titanium, but ended up grabbing the rest of the sheet as well. Thus consuming a max stack of titanium instantly. This also does not allow one to get max energy or nutitional value from eating any number greater than one in sheets. As it just thinks you are eating one sheet.

#### Steps to reproduce
- (Step 1) Grab material to eat
- (Step 2) Move to off hand and pull one sheet out of stack
- (Step 3) Drop larger stack of sheets to ground below character.
- (Step 4) Proceed to click on ones character while still standing over other stack of same materials.

#### Anything else you may wish to add:
I would like to say that nutritional/energy gain from eating multiple sheets at once might be bugged as well.

**Comment by KasparoVy** [comment]
It's because of forcemove, I've noticed other horrifying stack-related bugs too. If you do certain actions like this, which procs forcemove, it triggers some stacking logic that nukes whatever's below you

I managed to make a crapload of 0-sheet stacks of wood the other day making a bloody Teshari den and regularly deleted stacks of metal by standing over stacks of floortiles, lmao. It will require further investigation of stacking logic, but ore eater simply (and correctly) uses forcemove

**Comment by KasparoVy** [comment]
Testing a possible fix

**Comment by KasparoVy** [comment]
By the combined powers of movement code & stacking, they are Captain Confusing

Stacking logic looks OK but ultimately I think it might come down to movementcode
