### ISSUE TITLE
Wire duping with airlocks

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#8289]
#### Brief description of the bug

When deconstructing an airlock, spamming wirecutters during 'cut wires' step will cause a tons of single-wire pieces to spawn.

#### What you expected to happen

Only single wire piece actually spawns.

#### What actually happened

Like a dozen or so because of how many clicks.

#### Steps to reproduce
- Deconstruct an airlock to the stage where you have to cut wires.
- Start spamclicking it with wirecutters
- Get showered in extra wire

#### Code Revision
- cc90a8399e118d5534fa07f7504be7f081678596

**Comment by Heroman3003** [comment]
I don't remember anything fixing this being PR'd, so gonna say its still an issue

**Comment by MarinaGryphon** [comment]
Turns out do_after has an `exclusive` argument to prevent this kind of thing from happening. Neat! Won't do much to stop multiple people from doing it at once, but I might make `exclusive` a bitflag with `#define DO_NONEXCLUSIVE 0`, `#define DO_USER_EXCLUSIVE 1`, and `#define DO_OBJECT_EXCLUSIVE 2` so that you can make it so only one action can be performed on the *target,* too.
