### ISSUE TITLE
Redsuits turning invisible when cycled

### ISSUE THREAD

**Issue by cadyn** [VOREStation/VOREStation#8306]
#### Brief description of the bug
When you cycle a redsuit to vulpkanin it turns invisible.

#### What you expected to happen
I expected when I cycle the redsuit to vulpkanin using the suit cycler, it would cycle correctly.

#### What actually happened
When I used the talon Captain's suit cycler to cycle a redsuit, it turned invisible.

#### Steps to reproduce
- Obtain a redsuit
- Put the redsuit in a talon cycler.
- Set the species to vulpkanin
- Press cycle

**Comment by Rykka-Stormheart** [comment]
This is the same as https://github.com/VOREStation/VOREStation/issues/8227

Meaning that cyclers are fucked entirely for Security vulps I think.

**Comment by KillianKirilenko** [comment]
I don't think it's quite the same, because the proto shouldn't be pointing at the server's subfolder for the dmis; it should be looking in the same places as every other hardsuit. If it's fucked for everyone, that's a problem with that suit in particular.

This is irritating though because I tested the vintage & talon suit variants locally, and they worked fine at the time. I'll do some more local digging later and see what I can do to get this straightened out, unless someone beats me to it.

**Comment by KillianKirilenko** [comment]
Okay, so the problem with #8227 is that the HoS is still being issued the fluff variant protosuit, not the "new" one.

I have a hypothesis as to what the problem with this specific issue is and am testing it currently, along with a fix for the protosuit "problem".

**Comment by KillianKirilenko** [comment]
..I forgot to use proper terminology in the PR, argh.

This should be fixed now though.

**Comment by cadyn** [comment]
I'll double check when I get the chance cheers

**Comment by cadyn** [comment]
Just checked and still comes out invisible.

**Comment by KillianKirilenko** [comment]
Looks like the release branch is out of date, yeah. Should be fixed For Real once it's updated though.
