### ISSUE TITLE
Airlock insufficient air

### ISSUE THREAD

**Issue by Arokha** [VOREStation/VOREStation#832]
#### Brief description of the issue
64x,153y,1z canister of air insufficient to actually cycle airlock

#### Code Revision
- release - 2016-12-30 df6ded37b5f0ab894eadb6a06c90510e93923e5e

**Comment by SpadesNeil** [comment]
Was this fixed yet?

**Comment by ArbyTheDragon** [comment]
IIRC, every airlock eventually becomes unable to cycle without a true supply loop- because not all the air can be recovered during depressurization due to gas dynamics. 

But if you can't even cycle it once, that'd be a problem.
What actual room is it in, or is not on station's main level or outpost?

**Comment by Arokha** [comment]
Irrelevant on Tether, as the airlocks pull from atmospherics.
