### ISSUE TITLE
Slimes hostile to Prometheans when monkeys are with them.

### ISSUE THREAD

**Issue by r4d6** [VOREStation/VOREStation#8392]
#### Brief description of the bug
A normally 100% friendly-to-promethean slime start being hostile to you with the same level as any other race when there's a monkey next to you.

#### What you expected to happen
That the slime doesn't try to break out when seeing a monkey, or at least doesn't **keep** trying to break out after the monkey is gone.

#### What actually happened
They stayed permanently hostile to me as if I was a human, and any tasering counted as discipline with no (As far as I can tell) resentment for unjustified discipline.

#### Steps to reproduce
- Make a slime.
- Water a monkey cube in front of them.
- Watch them attacking the window.
- Remove the monkey.
- Watch as the slime still try to eat your face.
 

#### Anything else you may wish to add:
- It is the only way for promethean to discipline slimes unless those slime attack other slimes.

**Comment by cadyn** [comment]
So, after doing some testing with what's going here isn't actually a bug. The slimes aren't becoming hostile to the promethean, rather they are attacking their cage to get to the monkey. Even if they can't see it, and it's pretty far away, sometimes they'll still chase after it. The solution to this is to move the monkey to a different Z level or have it die. And the discipline counts as valid because the slime is attacking its cage it normally shouldn't do when it's disciplined even if there's a monkey on the other side.

**Comment by KasparoVy** [comment]
Don't be cheatin' on the slimes

**Comment by r4d6** [comment]
> So, after doing some testing with what's going here isn't actually a bug. The slimes aren't becoming hostile to the promethean, rather they are attacking their cage to get to the monkey. Even if they can't see it, and it's pretty far away, sometimes they'll still chase after it. The solution to this is to move the monkey to a different Z level or have it die. And the discipline counts as valid because the slime is attacking its cage it normally shouldn't do when it's disciplined even if there's a monkey on the other side.

So, actually the bug is that, since the discipline code check for what the slime is attacking, instead of what it want to eat, and it check if it is not a monkey/is a monkey, and since it is a window, it say that it is a valid discipline tase.
