### ISSUE TITLE
Mechs with thrusters or Minishuttles can't move without gravity

### ISSUE THREAD

**Issue by Natje0** [VOREStation/VOREStation#8438]
#### Brief description of the bug
Mechs with thrusters, or the miniships such as the Pinnace, can't move without gravity.

#### What you expected to happen
Miniships to fly normally, mechs with thrusters to be able to go on sweet sweet voyages through space.

#### What actually happened
Doesn't move at all. Can't even turn.

#### Steps to reproduce
- (Step 1) Bomb the gravity generator
- (Step 2) Get in your escapemech
- (Step 3) Oh no

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 4c340c5dac0a7afa8f5f219ec3ba812c5ed67033

**Comment by lbnesquik** [comment]
Hmmm. I don't know if that's part of the mech reworks.

**Comment by lbnesquik** [comment]
Here are my findings. 

One, We should upgrade mech movement to copy the fighter or hoverpod. This is cleaner, more understandable. Even if according to bluehaus, it shouldn't check for gravity everytime you move but instead everytime you enter an area. TBD.

Second, Movement should just check whether you have thrusters or gravity, not if you have inertia. I am not 100% sure about it, but there needs to be a proc to figure when you suddenly gain gravity.

Third, there might be an issue where you can't move because your player has no gravity, so it gets denied. Not sure aobut it.

**Comment by lbnesquik** [comment]
Discovery. 
![image](https://user-images.githubusercontent.com/24830358/88474869-0739e700-cf2b-11ea-8550-7a46bdc7fb76.png)

Getting into this mech with my jetpack on lets me move, but not  when it is off.
