### ISSUE TITLE
Psychiatrist Department Reclassification

### ISSUE THREAD

**Issue by Vorrarkul** [VOREStation/VOREStation#850]
(Issue format dropped since this is more of a request.)

I propose that psychiatrist/psychologist be moved from the Medical Department on the crew manifest, into Civilian or Other. It is not a medical doctor position, and its placement there may imply such to people who only glance at the manifest or presume anyone in the Medical section is obligated to help. On my end, it may help to remind psychiatrist players that they don't have to do anything relating to the rest of medical; a position established by @Screemonster in the discord.

I propose no other changes; they will remain under the jurisdiction of the CMO, they will have a medical headset, and their office will remain inside of Medical. This only affects the crew manifest list.

**Comment by Arokha** [comment]
Psychiatrists are medical doctors with an M.D. and four years of required residency, FYI. I don't necessarily object to removing them from medical, though. I usually play medical and I've never really interacted much with them to be honest. They've never really needed anything from the rest of medical and the rest of medical has only referred people to them, which doesn't require them to be IN medical.

**Comment by Vorrarkul** [comment]
Psychiatrists have a medical degree, yes, but psychologists do not. Considering that the in-game job covers both, I erred on the side of less-training. Besides, they lack any relevant access to do any of the other jobs within the medical department.

I decided to propose this after a shift where, for the entire first half, I was the only medical player, and I was a psychologist. I was too good-hearted not to help people who got injured, but it ended up with the bolting of the chemistry door and hacking of the surgery doors in order to help them. As much as some crew need a reminder not to pressure the psychiatrist, people like me need a reminder to try and not overextend themselves in a niche job.

**Comment by Arokha** [comment]
Sure. I was only speaking about psychiatrists, which are the primary title for that job.

Well, here's your reminder: you don't have to do any of that! :P

**Comment by Wickedtemp** [comment]
I'd be in favor of this. Having a Psychologist/Psychiatrist listed as Medical in the manifest will likely only serve to confuse the crew into believing that there's someone in Medbay who can take care of Cryo and Cloning, when that isn't the case. 

Psych's know they don't have to do it. But general crew? They don't. And this would help them learn.

**Comment by Screemonster** [comment]
Basically, people have this odd attitude of "medbay's got staff? TIME TO BE RECKLESS AND THEN YELL AT THEM IF THEY DON'T PATCH ME UP".

Shaft miners have access to cargo, and cargo techs have access to the mining outpost, but we'd consider it unreasonable of a roboticist to screech out over the comms (or OOC) because the cargo tech is manning cargo as is their fucking job rather than piling a suit on and doing the job they didn't actually sign up to do.

Likewise, it'd be unreasonable for a miner to scream at the xenobiologist or toxins scientist to make them a ripley. It'd also be considered unreasonable for the chemist to yell at the bartender for not working hydroponics to grow whatever weird plant chems he might want. The bartender may have _access_ to hydroponics, but it's not his _job_ to work it.

Then again I've already got a low opinion of the usual shitter tactic of "drink myself into liver damage and yell for a medic then bitch at them for not doing their job which is apparently to fix problems that I deliberately created".

**Comment by BothNevarBackwards** [comment]
Yeah I think they should stay in medical myself. Paramedics also aren't required to clone and they're still in medical. Ditto chemists. Asking a xenobotanist to make you a mech is a great comparison in my opinion.

**Comment by SpadesNeil** [comment]
I agree heavily that we shouldn't move Psychiatrist/Psychologist from Medical.
