### ISSUE TITLE
Hair overlapping anthro ears

### ISSUE THREAD

**Issue by FirstSgtDan** [VOREStation/VOREStation#8501]
#### Brief description of the bug
"Hawk" haircut overlaps the "wolf, colorable" ear when looking from the side.

#### What you expected to happen
The hair sprite layer should be behind the ear sprite layer.

#### What actually happened
The "Hawk" haircut is overlapping the "wolf, colorable" ear when looking from the side. I'm seeing the hair first and the ear in the background.

#### Steps to reproduce
- In the Character Setup screen, select haircut "Hawk";
- In the Character Setup screen, select "wolf, colorable" ears;
- Look at the side previews on the right.

#### Anything else you may wish to add:
Bald (ear sprite entirely visible):
![image](https://user-images.githubusercontent.com/7003096/88541324-f05ac980-cfea-11ea-8828-90d086b2f1e5.png)

Hawk (ear sprite partially hidden behind hair sprite):
![image](https://user-images.githubusercontent.com/7003096/88541274-dc16cc80-cfea-11ea-82f5-39ea12d5f853.png)

**Comment by Verkister** [comment]
Oh I see the issue here. Those are not the wolf ears getting overlapped. The wolf ears are much smaller and the vulp ears that are getting visually overlapped are a part of the vulp head highlights marking, which for some oversight reason still includes the ears and as a marking it naturally goes under the hair stuff.

**Comment by KasparoVy** [comment]
This is corrected by using the "**vulpkanin, dual-color**" ears from under the VORE tab instead of the wolf ones

The all head highlights & ears + face markings are useful for those who mix the marking with other ear designs to craft custom sprites, or otherwise use the markings to colour pixels that they can't with other markings.
We don't need to remove otherwise usable markings
