### ISSUE TITLE
Apex Metabolism

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#8502]
#### Brief description of the bug
Apex Metabolism doesn't work

#### What you expected to happen 
To end up insanely hungry very fast, as expected of any gluttony demon and be forced to eat like one.

#### What actually happened
Didn't get hungry at all thirty or so minutes into the shift

#### Steps to reproduce
- Take Apex Metabolism
- Expect to end up super hungry super fast
- Not hungry at all.

#### Code Revision
- Server revision: B:release D:
Commit: 53e0b5d9f053dae5af8f8b8ef1589cce8a0da8b2

**Comment by Verkister** [comment]
If you need a gluttony demon tier speed, you can always pray for a little tweak, otherwise it's just 2x teshari hunger.

**Comment by SilverTalismen** [comment]
It always used to be super fast but I barely got hungry with it fourty or so minutes in, even fast metabolism was faster than so called apex, figured it was a bug.

**Comment by Verkister** [comment]
Hmm seems to be working fine on the server right now, even tested varedited numbers for some really fast results. Perhaps there might have been some external cause, like a xenobio slime or an artifact nearby?

Altho while looking into the code, I noticed the hunger rates weren't getting applied properly to mob vars, causing them to not affect the movement drain (only passive hunger), but that bug looks like it's been in since the very beginning.
