### ISSUE TITLE
No assisted vocal synthesizer Repair or surgery options

### ISSUE THREAD

**Issue by VictorZisthus** [VOREStation/VOREStation#8895]
#### Brief description of the bug
The assisted vocal synthesizer cannot be repaired or put back in a full synthentic.

#### What you expected to happen
Being able to repair or implant the voicebox

#### What actually happened
Nothing

#### Steps to reproduce
Did some code diving and putzing around ingame, there does not look like there is even an option to repair or implant the voicebox currently. Needs to be added!

**Comment by VictorZisthus** [comment]
It also appears subject to DECAY. Joy.

**Comment by Meghan-Rossi** [comment]
The decay part makes sense since assisted organs are mostly flesh, for a non-decaying organ you can set it to mechanical in character setup.  It's also currently possible to put an assisted voicebox into organic crew or a mechanical voicebox into synth/fbp crew, but putting assisted into synth/fbp gets caught by the same check as putting normal flesh organs in.  It definitely doesn't seem to make sense that assisted organs are both something synth/fbps can start with but not something they can have put into them, either they shouldn't be able to start with them or they should be able to have them implanted.
