### ISSUE TITLE
[BUG] Science Consoles Sync Problems

### ISSUE THREAD

**Issue by TheFurryFeline** [VOREStation/VOREStation#8901]
#### Brief description of the bug

This came up in the research discord channel. After testing in a private environment, I've found and seem to confirm that hitting the sync option winds up adding duplicate listings of any item that you can print off. This occurs for the Circuit Imprinter, ExoFab, Protolathe, and so on.

#### What you expected to happen

Just the one listing of any item.

#### What actually happened

At most 5 of each item listed. Upgraded state does not seem to be relevant as I saw 5 with basic parts installed.

#### Steps to reproduce
- (Step 1) Do R&D.
- (Step 2) Sync database.
- (Step 3) Blink in confusion at the increase in listings for Matter Bins and so on.

#### Code Revision
- Current Master branch. [f7553f7]
 

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/38586851/91638116-1ead3980-e9db-11ea-9c2e-e0bfee88439b.png)

- Mostly additional bugs I found....

- - Seems that the page changing doesn't quite work out right. Clicking the next page sometimes works, sometimes doesn't. when it does, the items randomly change. It can be just one item or five and the next page could have a more filled list barely resembling the original first page. 
![image](https://user-images.githubusercontent.com/38586851/91637944-f3761a80-e9d9-11ea-80f8-1b638008c63e.png)
The above image is one page and the prior page has one additional slime scanner listed.

- - Upgrading the Circuit Printer seems to make any Sulphuric Acid disappear. Glass stays, however. Also shows "No protolathe found" in the Circuit Imprinter tab while upgrading removes the connection.

**Comment by ShadowLarkens** [comment]
```
This came up in the research discord channel. After testing in a private environment, I've found and seem to confirm that hitting the sync option winds up adding duplicate listings of any item that you can print off. This occurs for the Circuit Imprinter, ExoFab, Protolathe, and so on.
```
Fixing this now, it was a problem with known_designs having duplicate entries because I didn't realize how stupid the tech tree is.

```
Seems that the page changing doesn't quite work out right. Clicking the next page sometimes works, sometimes doesn't. when it does, the items randomly change. It can be just one item or five and the next page could have a more filled list barely resembling the original first page.
```
This isn't exactly a bug, it's just the fact that some information isn't properly displayed to the user. The pagination chevrons allow you to scroll to an infinite number of pages, but once you reach the end of the list, the page contents won't change anymore. I'll add a readout of the current page number to the title to make it more clear why your button presses might not be doing anything if you're scrolled off into neverland. 
As for the "strange results", make sure that you click on the search bar and hit backspace-- sometimes it gets stuck with an invisible search term, unfortunately, and there's not a whole lot I can do to fix that.

```
    Upgrading the Circuit Printer seems to make any Sulphuric Acid disappear. Glass stays, however. Also shows "No protolathe found" in the Circuit Imprinter tab while upgrading removes the connection.
```
Funny enough, the sulphuric acid disappearing is an existing bug; you should probably file a separate bug report for it. I'll make it read the proper builder name for "no x found", though.

**Comment by TheFurryFeline** [comment]
Good kitty, doing the work of the gods. :3
