### ISSUE TITLE
Disallow micros from using guns

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#909]
#### Brief description of the issue
Based on the outcome of the vote here: http://forum.vore-station.net/viewtopic.php?f=20&t=835

**However** there should be some exceptions. Notably, the shrink ray shouldn't be restricted from micro use, or micros are fucked for using them. Same deal with any "gun" that is a utility device, such as the plant mutating gun, dart gun, or even the pneumatic cannon. I don't mind if micros stuff objects into that and launch them.

This will force micros to use different and more interesting tactics to remain competitive, using their size to their advantage rather than just straight up being an impossible to click target who can also shoot things at long range. The micro's battle, if it must be fought, must be fought up close and personal where the enemy cannot react quickly enough to fight back.

Although micros are planned to have their brute damage nerfed in https://github.com/VOREStation/VOREStation/pull/771, this will not nerf stun damage I don't think.

Discuss what other guns if any should be excluded from this nerf.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/94b621b3106703cf3788f62f427ddcd6abbbfb8f

**Comment by SpadesNeil** [comment]
If possible, micros should be given an evasiveness buff for projectiles once the damage edits go in. I know there's vars to do it, but it needs testing to decide what is actually balanced.

**Comment by Arokha** [comment]
Some e-guns might make sense for micros to use.

Tasers don't have recoil and I have a taser that is literally 1" long. Electricity dun care about size yo. Maybe micros should have special tasers that have fewer shots due to physically smaller batteries.

I would also argue that the pulse destroyer (aka the asset protection laser) should be usable by micros because if they are a micro ERT/AP trooper then they are already a certifiable badass and obviously know what they are doing. They probably have a tiny one or something who knows.

Here's a list of "guns" as the game considers them:
- **Energy**
-- Captain laser
-- Chameleon guns
-- E-Crossbow
-- Darkmatter gun (vox)
-- Decloner
-- Flora gun
-- Ion rifle
-- Laser
-- Laser cannon
-- Meteorgun (um)
-- Mindflayer
-- Plasma stun launcher
-- Pulse rifle (AP)
-- Retro laser
-- Sizegun
-- E-sniper
-- Sonic staff thing (vox)
-- Staffs (animate/focus)
-- Stunvolver
-- Taser
-- Tempgun
-- X-ray
- **'Launcher'**
-- Crossbow
-- Grenade launcher
-- Pneumatic cannon
-- Rocket launcher
-- Spikethrower
-- Syringe
- **Projectile**
-- All of these have recoil which would obliterate a micro so why list, except:
-- Dartgun
-- Derringer

**Comment by Screemonster** [comment]
The "not affecting stun damage" is why I proposed nerfing the maxhealth var to scale with size rather than modifying damage taken.

Also for those worried about micros chances in combat and being locked out of gateway missions, well. I'm about to fire up gimp for something you guys might like.

**Comment by Screemonster** [comment]
Also.

[9:43 PM] Dhaelcat: We need
[9:43 PM] Dhaelcat: like
[9:43 PM] Dhaelcat: an ANTI Shrink Laser divice
[9:43 PM] Dhaelcat: Like, An item Security officers can use on their wrists like a glove
[9:43 PM] Scree: Dhael - do you mean an item that just resists the sizegun?
[9:44 PM] Scree: That should be easy enough.
[9:44 PM] Dhaelcat: yes
[9:44 PM] Dhaelcat: I think it should be
[9:44 PM] Dhaelcat: Like a normal item
[9:44 PM] Dhaelcat: that anyone can get
[9:44 PM] Dhaelcat: So people and officers that are worried about getting shrink can just use it
[9:44 PM] Scree: just in the proc for the sizelazer... "if *THIS THING in target.contents) return 0"
[9:45 PM] Dhaelcat: Cuz MUH PREFS and also "Oh look now micros cant use guns" shrinks the officer trying to arrest you

**Comment by Wickedtemp** [comment]
Remember, there's other ways to shrink people. Macro, Micro and Normal-cillin are all chemicals that can be made in any chem dispenser, or obtained through botany. Loaded into an autoinjector, you have an instant shrinking tool that penetrates voidsuits/hardsuits.

**Comment by SpadesNeil** [comment]
That still requires you to get in range of punching, Wickedtemp. If you pull off such a stunt, I ain't even mad.

**Comment by Screemonster** [comment]
Loading it into an autoinjector also requires you to hit them _twice_ before a normal crewmember will be too small to use a gun, unless you have a huge dose of a phenomenal amount of microcillin that takes a buttload of work to pull off, while a shrink ray can double-tap someone at range in a matter of seconds.

If you pull of a double-shrink on someone with chems without their being able to react, I ain't mad either.

**Comment by Wickedtemp** [comment]
Shrinking someone at range with micro-cillin is, right now, easy to do. All you need is an Ody mech or a syringe gun. A single unit of micro-cillin can be diluted to be used 5 times. For example, if I loaded a hypospray with 1u microcillin and the rest with water, I'd easily be able to shrink an officer down to being unable to use a weapon, with ease.

Ody mech's also, at the moment, are able to mass-produce the size-changing chems, so getting a large amount of them really isn't difficult.

**Comment by SpadesNeil** [comment]
Reallllly need to blacklist certain chems from the Ody....

**Comment by Wickedtemp** [comment]
It's better to make a different issue for that, but just because it's brought up here, if you remove phoron, micro, normal and macro Cillin and blood, that should cover most of the exploitable reagents. 

The Ody's ability to mass produce the size changing chems won't really come into play with this, as 1u, when utilized properly, can still shrink a macro to a micro. From range, if you use a syringe gun.

**Comment by Repede** [comment]
For chems with microcilin. I've noticed a smoke grenade with 1 unit of microcilin will actually affect everyone caught in the radius multiple times. You could make a entire room of macros into micros with a single one if they stay in the smoke for the whole duration.

**Comment by SpadesNeil** [comment]
this is still a desired thing
