### ISSUE TITLE
New cooking machines. 

### ISSUE THREAD

**Issue by Fluffy74** [VOREStation/VOREStation#9268]
So, seems like grill/fryer fail to properly work in some cases. 
Recipes are from https://vore-station.net/infodump/recipes_food.html
Seems like for the fryer some recipes are wrong. Mostly one ingredient recipes. Some are missing Battering part, others are not working at all. 
Quick testing: Chilli and Sausage need battering to work. Plump helmet doesn't work with/without battering. Two bananas doesn't work.

It's possible to drop something like flour in the Fryer basket and... it just gets stuck inside. You can't alt-click to remove it (red message appears), but Fryer itself detects something in the basket and tries to fry the flour for zero effect.

**Comment by Huenererschrecker** [comment]
Not actually a bug in the code, this the recipe-dropper ignoring that stuff needs to be battered now since the aurora cooking change. This is also why I kept saying since before that change got live to actually update the wiki and all that on that, which still isn't entirely done. 

As for reagents in baskets and the likes, you can dump that into a sink by click-dragging the container on it.
