### ISSUE TITLE
Protean blob cannot eat simplemobs (mice, lizards)

### ISSUE THREAD

**Issue by Runa-Dacino** [VOREStation/VOREStation#9380]
#### Brief description of the bug
Proteans, when using their blob-form, cannot put simple mobs (mice, lizards) into their vorebelly.

#### What you expected to happen
For the protean to be able to eat simple mobs when using the goop form.

#### What actually happened
Was unable to eat mobs, could only be force fed

#### Steps to reproduce
- Be protean
- Find a mouse 
- Go into nanite goop form
- Try to eat it as you would a carbon mob

#### Code Revision
 Server revision: B:release D:
Commit: 0735df0f9aacc24143c8f7f89dcad2769dc2a9f3 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by H0lySquirr3l** [comment]
testing shows that they seem to be able to still put the mobs in their vore bellies... But any attempt to swallow them will first have you slash them. Which is wierd because its the "grab" intent not harm.... this grab intent also lets blobs break tables.

![image](https://user-images.githubusercontent.com/34927367/107556825-7e208f80-6b9e-11eb-8f20-b129e8060672.png)

![image](https://user-images.githubusercontent.com/34927367/107556867-87a9f780-6b9e-11eb-984c-1e8f568db63c.png)

![image](https://user-images.githubusercontent.com/34927367/107556897-909ac900-6b9e-11eb-8a13-2c83da3864d3.png)

![image](https://user-images.githubusercontent.com/34927367/107556962-a27c6c00-6b9e-11eb-920e-9f92f78df20d.png)

![image](https://user-images.githubusercontent.com/34927367/107556985-a9a37a00-6b9e-11eb-8c26-9513784744d7.png)

![image](https://user-images.githubusercontent.com/34927367/107557032-b627d280-6b9e-11eb-8ad6-e03d3f6fb4e9.png)
