### ISSUE TITLE
Talon eats the excursion shuttle if they go to the same place

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#9390]
#### Brief description of the bug
it seems like when the talon and the explorer team go to the same place, the excursion shuttle's overmap landmark doesn't always return to the overmap andthat causes problems, like exploration being stranded in nothingness forever

#### What you expected to happen
not that

#### Steps to reproduce
- bring talon to virgo 2
- bring explo to virgo 2
- try to leave

#### Code Revision
-  B:release D:
Commit: 0735df0f9aacc24143c8f7f89dcad2769dc2a9f3 
 

#### Anything else you may wish to add:
- the MC also crashed and wouldn't restart after that happened, but I'm not sure if that's related

**Comment by dwinters99** [comment]
working as intended, don't scene stomp the talon
/s

i could swear that this didn't used to happen so I don't know what's going on here
like, this must be a recent problem because if it wasn't how did it take this long for it to happen

**Comment by Verkister** [comment]
Fix tossed upstream. Bug caused by the shuttle locking onto the talon lifeboat's landmark instead of the planet's landmark, and docking the lifeboat moves the landmark into talon (or the planet's) landmark's contents and thus removes it from the overmap itself and that causes the spacetravel proc to runtime and die.
