### ISSUE TITLE
Request Consoles should print out premade forms for people

### ISSUE THREAD

**Issue by JoanRisu** [VOREStation/VOREStation#969]
So someone asked if we could have the Request consoles have the ability to print out template paperwork forms for people to save them a few clicks looking for paperwork and I thought it was a good idea so I'm putting this ticket up for thoughts.

Also, I thought we had a suggestion label but we don't ;w;

**Comment by Vorrarkul** [comment]
How many request consoles do we have? I'm only aware of the cargo console, which sort of prints its own forms (that fill themselves out too.)

**Comment by Screemonster** [comment]
Not the cargo ordering console. There are request consoles in nearly every department, mounted on the walls. People hardly ever use them as it's easier to PDA the department or ask over the radio usually, but IIRC they work without the need for telecoms.
You can use them to anonymously tip off security to things and everything. Hell, the ability to send an anonymous message to medbay would be a pretty useful thing too for preds that want to get their prey cloned without security snooping.

**Comment by Vorrarkul** [comment]
I understand now. With regards to this suggestion, the only sticking point I see is what format these forms are in. I have my own forms, which could be used. There is a sampling of my work [**here**](https://wiki.vore-station.net/Guide_to_Paperwork#Prettier_Sample_Forms). I should note, I actually have more _and_ more updated forms than this, I have just been unable to post them to the wiki due to its broken authentication system (**https://github.com/VOREStation/VOREStation/issues/950**).
