### ISSUE TITLE
Smelting Stacker Stacks Singles

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#9842]
#### Brief description of the bug
The sheet-stacker in mining does not stack sheets like it used to. It not spits them out in nice singles, resulting in a few hundred items laying on the floor that need to be sorted manualy

#### What you expected to happen
Nice stacks of 50

#### What actually happened
Not nice stacks of 1

#### Steps to reproduce
- Mine
- Smelt
- Rage

#### Code Revision
- df54d624d8083743d84055dc81d83b02c61ae601 
 

#### Anything else you may wish to add:
- This doesn't seem to happen with marble, oddly enough

**Comment by TheFurryFeline** [comment]
After checking the stacker's edit history, seems https://github.com/VOREStation/VOREStation/commit/3e804dc7991228bd412a2d2e00d72f2b04002d6e#diff-5c2c2dc410634c51ef8e7bc5c2cab1cf386a67b7f28e0bdbf38849f6458fbcb2 is the most recent change to this. Looks like typesof was changed to subtypesof. Dunno if that's what the problem is. Am on mobile and reading the code in mobile web sucks
