### ISSUE TITLE
Heartbeat still plays even if you're in a mining hardsuit or voidsuit

### ISSUE THREAD

**Issue by Midaychi** [VOREStation/VOREStation#987]
#### Brief description of the issue
Your heartbeat sound, that cannot be disabled by any means, and still plays if you're in space in a mining void suit or hardsuit. The problem is that it can bother people with synesthesia, specifically because it's something you can't just avoid, and is constant so you can't just take headphones off or whatever for a short period. It effectively disables them from using sound while in vacuum. 

#### What you expected to happen
Not to be forced to basically exit the game the moment I stepped into a vacuum, or disable **completely** an integral part of the game (the sound).

#### What actually happened
I quit.

#### Steps to reproduce
- (Step 1) Wear mining voidsuit or  hardsuit
- (Step 2) Go into vacuum
- (Step 3) THUMP-THUMP

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: release - 2017-02-21
1001be5b2eb5bbdc528935ae9fce3606aa5833ec 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
:C

**Comment by SpadesNeil** [comment]
IIRC synesthesia is that thing where you see colors when you hear certain sounds. Is that accurate?

**Comment by Midaychi** [comment]
It doesn't specifically have to be seeing or colours, but yes. It's a the linkage of a separate sense to some degree with another sense.

**Comment by Midaychi** [comment]
Sorry it got me a bit worked up and I used inappropriate and intentionally confrontational language in a bug report.

**Comment by Cameron653** [comment]
Marking this as moderate as it's annoying and should be able to be toggled off, and misc as it _is_ a feature, just not a great one and should be reworked.

Code area in question:
https://github.com/VOREStation/VOREStation/blob/5702752b9ebb0d95740d648a8f2aebf0eab83ea9/code/modules/mob/living/carbon/human/life.dm#L1513-L1532

**Comment by ArbyTheDragon** [comment]
I totally understand regarding the synesthesia- there's a few accessibility options I wish the game had- along with the dreamseeker. (I want white text on black background! Or maybe even compatibility with a text to speech system for people with trouble reading like me?)

I don't want the heartbeat (or breathing if that's still there. I haven't EVA'd in a long time) to go away as a feature though. I think it helps emphasize the silence of space and a vacuum, because your ears become more sensitive to quieter sounds the lower the dB of the background is. Maybe put in a check prior to playing the sound script to see if X option is on or off.
