### ISSUE TITLE
Pushing canisters isn't smooth anymore

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#9880]
#### Brief description of the bug
when you push something it jumps to the next tile, rather than smoothly sliding with you

#### What you expected to happen
pushing things got changed some time ago to move  them smoothly along with you

#### Steps to reproduce
- Push a canister

#### Code Revision
- B:release D:
Commit: df54d624d8083743d84055dc81d83b02c61ae601

**Comment by Heroman3003** [comment]
I'm actually a bit uncertain about this fix, in part because of the fact that ONLY canisters were objects smoothly pushable, while everything else was pushed same way as before. Having consistency in whether you want to move with objects you're pushing or just pushing it away from you is nice, as would be having actual option to choose which you want to do via preference.
