### ISSUE TITLE
Robotic Limb Detachment gives limbs no sprite

### ISSUE THREAD

**Issue by Huenererschrecker** [VOREStation/VOREStation#9993]
#### Brief description of the bug
See Title

#### What you expected to happen
The detached limb to have their usual sprite

#### What actually happened
No sprite, see attached picture

#### Steps to reproduce
- Spawn as a synthetic
- Object tab -> Remove Limb
- You have no sprite in your hand but your arm or whatever is in your hand.

#### Code Revision
- 02e68ec65214ef8f44775ee3bcd0ade94f0f835a 
 

#### Anything else you may wish to add:
- https://i.gyazo.com/9c3134093143805caad589e67a67720b.png
- No I cannot take it out of my satchel because of that.

**Comment by dwinters99** [comment]
This perplexes me, because I got it to work first try despite having it occur to me on live before. It seems to be bound to the specific type of limb. Will test more in a while with different manufacturers.
![image](https://user-images.githubusercontent.com/65516417/115464508-300db500-a1fb-11eb-8f16-818d79d60e37.png)

**Comment by dwinters99** [comment]
More info. Seems it only happens to left limbs. Right legs and right arms work fine.
![image](https://user-images.githubusercontent.com/65516417/115465138-1faa0a00-a1fc-11eb-8ed2-fbacae05d646.png)
![image](https://user-images.githubusercontent.com/65516417/115465412-93e4ad80-a1fc-11eb-8d13-7908b9e3bda4.png)
